package main

import (
	"bytes"
	"flag"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"testing"
)

// updateGolden refreshes the committed goldens under testdata/golden/.
// Run with
//
//	go test ./src/protocol/yang/cmd/yanggen -run TestEmitFixtureGolden -update-golden
//
// after intentional emitter changes and audit the diff.
var updateGolden = flag.Bool("update-golden", false, "rewrite testdata/golden/* with the current emitter output")

const fixtureGoldenImportBase = "go.aledante.io/FlowSeer/src/protocol/yang/cmd/yanggen/testdata/golden/fixture"

func emitOne(vs *VendorSet, m *LoadedModule) (string, error) {
	plan, err := buildEmissionPlan(vs, fixtureGoldenImportBase)
	if err != nil {
		return "", err
	}
	files, err := emitModuleFiles(plan, plan.packages[m.Name])
	if err != nil {
		return "", err
	}
	var b strings.Builder
	for _, name := range sortedKeys(files) {
		b.Write(files[name])
	}
	return b.String(), nil
}

func TestContainsIdentifierIgnoresComments(t *testing.T) {
	if containsIdentifier("// /native:pim.\n", "pim") {
		t.Fatal("comment text was treated as a package reference")
	}
	if !containsIdentifier("// comment\nvar _ = pim.Schema\n", "pim") {
		t.Fatal("package reference was not detected")
	}
}

// TestEmitFixtureGolden renders every fixture module and compares
// byte-for-byte against the committed goldens.
func TestEmitFixtureGolden(t *testing.T) {
	vs := fixtureVendor(t)
	for _, m := range vs.Modules {
		got, err := emitOne(vs, m)
		if err != nil {
			t.Fatalf("emit %s: %v", m.Name, err)
		}
		goldenPath := filepath.Join("testdata", "golden", "fixture", m.Package, m.Package+".go")
		if *updateGolden {
			if err := os.MkdirAll(filepath.Dir(goldenPath), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(goldenPath, []byte(got), 0o644); err != nil {
				t.Fatal(err)
			}
			t.Logf("updated %s (%d bytes)", goldenPath, len(got))
			continue
		}
		want, err := os.ReadFile(goldenPath)
		if err != nil {
			t.Fatalf("read golden for %s (rerun with -update-golden if first time): %v", m.Name, err)
		}
		if string(want) != got {
			candidate := goldenPath + ".got"
			_ = os.WriteFile(candidate, []byte(got), 0o644)
			t.Errorf("golden mismatch for %s; candidate written to %s — rerun with -update-golden after auditing", m.Name, candidate)
		}
	}
}

// TestEmitFixtureParses ensures each emitted file is syntactically
// valid Go even when goldens are stale.
func TestEmitFixtureParses(t *testing.T) {
	vs := fixtureVendor(t)
	for _, m := range vs.Modules {
		got, err := emitOne(vs, m)
		if err != nil {
			t.Fatalf("emit %s: %v", m.Name, err)
		}
		fset := token.NewFileSet()
		if _, err := parser.ParseFile(fset, m.Package+".go", got, parser.AllErrors); err != nil {
			t.Fatalf("emitted %s does not parse: %v\n--- src ---\n%s", m.Name, err, got)
		}
	}
}

// TestEmitFixtureSurface pins the load-bearing emitted symbols
// without demanding byte-exactness: the golden test owns that.
func TestEmitFixtureSurface(t *testing.T) {
	vs := fixtureVendor(t)
	main := moduleByName(t, vs, "fixture-main")
	src, err := emitOne(vs, main)
	if err != nil {
		t.Fatal(err)
	}

	wantRE := []string{
		`Listen\s+\*yang\.Value`,
		`Proto\s+\*yang\.Identity`,
		`Ratio\s+\*yang\.Value`,
		`ServerRef\s+\*string`,
		`ServerName\s+string`,
		`Presence:\s+true`,
	}
	want := []string{
		"Code generated by yanggen. DO NOT EDIT.",
		"module: fixture-main revision: 2026-01-02",
		// Structs, schemas, and descriptors.
		"type Servers struct",
		"type ServersServer struct",
		"var ServersServerSchemaX",
		"type ServerKey struct",
		"func ServerDescriptor() yang.ListDescriptor",
		// Nested list: flat row with the ancestor key, schema chain,
		// nested decode.
		"type Endpoint struct",
		"type EndpointFlatRow struct",
		"yang.NestedRowCodec(",
		"yang.JoinPath(",
		// Deviation applied: the deviated leaf is gone (asserted via
		// notWant below); presence, unions, identityref, and the
		// leafref key are asserted by wantRE above.
		// Synthetic-row descriptor for a container.
		"func ServersDescriptor() yang.ListDescriptor",
		"yang.SubtreeDescriptor[Servers]",
		// Name collision resolved deterministically with a hash
		// suffix, not silently merged.
		"type AlarmState",
		"type AlarmStateX",
	}
	notWant := []string{
		"LegacyFlag", // removed by fixture-dev's deviate not-supported
	}
	for _, w := range want {
		if !strings.Contains(src, w) {
			t.Errorf("emitted fixture-main missing %q", w)
		}
	}
	for _, pat := range wantRE {
		if !regexp.MustCompile(pat).MatchString(src) {
			t.Errorf("emitted fixture-main missing pattern %q", pat)
		}
	}
	for _, w := range notWant {
		if strings.Contains(src, w) {
			t.Errorf("emitted fixture-main unexpectedly contains %q", w)
		}
	}
	if t.Failed() {
		t.Logf("--- src ---\n%s", src)
	}
}

// TestEmitAugmentModule asserts that augmenting nodes are emitted in a
// package-owned group and that the target package references that group.
func TestEmitAugmentModule(t *testing.T) {
	vs := fixtureVendor(t)
	mainSrc, err := emitOne(vs, moduleByName(t, vs, "fixture-main"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(mainSrc, "FixtureAug  *fixtureaug.ServerAugment") {
		t.Error("fixture-main server is missing the fixture-aug group field")
	}
	if !strings.Contains(mainSrc, "FixtureAug2 *fixtureaug2.ServerAugment") {
		t.Error("fixture-main server is missing the fixture-aug2 group field")
	}
	if regexp.MustCompile(`Module:\s+moduleFixtureAug`).MatchString(mainSrc) {
		t.Error("plain fields still carry foreign-module qualification")
	}
	if strings.Contains(mainSrc, "var moduleFixtureAug ") {
		t.Error("fixture-main declares an unused fixture-aug module variable")
	}

	typesSrc, err := emitOne(vs, moduleByName(t, vs, "fixture-types"))
	if err != nil {
		t.Fatal(err)
	}
	for _, w := range []string{"IdentityTCP", "IdentityUDP", "IdentityProtocol"} {
		if !strings.Contains(typesSrc, w) {
			t.Errorf("fixture-types missing identity value %s", w)
		}
	}
}

// TestEmitGroupingInstantiatingModule asserts that nodes instantiated from
// a grouping in another module take the instantiating module's name.
func TestEmitGroupingInstantiatingModule(t *testing.T) {
	vs := fixtureVendor(t)
	mainSrc, err := emitOne(vs, moduleByName(t, vs, "fixture-main"))
	if err != nil {
		t.Fatal(err)
	}

	if strings.Contains(mainSrc, `"fixture-grp"`) {
		t.Error("emitted fixture-main unexpectedly contains defining module fixture-grp")
	}

	// The shared item schema literal names fixture-main.
	pat := `ItemSchema\s*=\s*&yang\.Schema\{[\s\S]*?Module:\s+(?:"fixture-main"|moduleFixtureMain)`
	if !regexp.MustCompile(pat).MatchString(mainSrc) {
		t.Errorf("emitted fixture-main missing fixture-main Module on ItemSchema")
	}
}

// TestEmitGroupingSharedShape asserts that a grouping used under
// two containers of fixture-main generates one struct for the two instances.
func TestEmitGroupingSharedShape(t *testing.T) {
	vs := fixtureVendor(t)
	mainSrc, err := emitOne(vs, moduleByName(t, vs, "fixture-main"))
	if err != nil {
		t.Fatal(err)
	}

	if !strings.Contains(mainSrc, "type Item struct") {
		t.Error("type Item struct not found in emitted fixture-main")
	}
	if strings.Contains(mainSrc, "PrimaryGroupItem") || strings.Contains(mainSrc, "SecondaryGroupItem") {
		t.Error("emitted separate structs for grouping instances instead of shared Item")
	}
	wantComment := "Item is the fixture-main node shape instantiated at 2 schema paths, such as /fixture-main:primary-group/item."
	if !strings.Contains(mainSrc, wantComment) {
		t.Errorf("emitted fixture-main missing doc comment %q", wantComment)
	}
}

func TestEmitMergesIdenticalGroupShapes(t *testing.T) {
	dir := t.TempDir()
	writeYangModule(t, dir, "group-base.yang", `module group-base {
  yang-version 1.1;
  namespace "urn:flowseer:group-base";
  prefix gb;
  container first { container target; }
  container second { container target; }
}`)
	writeYangModule(t, dir, "group-aug.yang", `module group-aug {
  yang-version 1.1;
  namespace "urn:flowseer:group-aug";
  prefix ga;
  import group-base { prefix gb; }
  augment "/gb:first/gb:target" { leaf value { type string; } }
  augment "/gb:second/gb:target" { leaf value { type string; } }
}`)
	vs, err := LoadVendor(&Vendor{Name: "groups", Paths: []string{dir}})
	if err != nil {
		t.Fatalf("LoadVendor: %v", err)
	}
	plan, err := buildEmissionPlan(vs, "example.test/groups")
	if err != nil {
		t.Fatalf("buildEmissionPlan: %v", err)
	}
	if got := len(plan.packages["group-aug"].groups); got != 1 {
		t.Fatalf("group shapes = %d, want one shared shape", got)
	}
	files, err := emitModuleFiles(plan, plan.packages["group-aug"])
	if err != nil {
		t.Fatalf("emit group-aug: %v", err)
	}
	var src strings.Builder
	for _, name := range sortedKeys(files) {
		src.Write(files[name])
	}
	if got := strings.Count(src.String(), "type TargetAugment struct"); got != 1 {
		t.Fatalf("TargetAugment declarations = %d, want one", got)
	}
}

// TestEmitShapeKeySeparatesDifferingNodes asserts that same-named nodes
// with the same child names get separate types when they differ in a
// property the codecs read (a leaf's type, presence, a child's module, or
// the node's own module),
// and that a keyed list shared through a grouping keeps one struct but a
// Key and a Descriptor per instance, each on its own path. A shared type
// for nodes that decode differently would lose data at one of its paths.
func TestEmitShapeKeySeparatesDifferingNodes(t *testing.T) {
	vs := fixtureVendor(t)
	src, err := emitOne(vs, moduleByName(t, vs, "fixture-main"))
	if err != nil {
		t.Fatal(err)
	}
	file, err := parser.ParseFile(token.NewFileSet(), "fixturemain.go", src, 0)
	if err != nil {
		t.Fatal(err)
	}

	fieldTypes := make(map[string]map[string]string) // struct -> field -> type
	descriptors := make(map[string]*ast.FuncDecl)    // func -> decl, for ListDescriptor[Peer, _]
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.GenDecl:
			for _, spec := range d.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				fields := make(map[string]string)
				for _, f := range st.Fields.List {
					for _, n := range f.Names {
						fields[n.Name] = src[f.Type.Pos()-1 : f.Type.End()-1]
					}
				}
				fieldTypes[ts.Name.Name] = fields
			}
		case *ast.FuncDecl:
			if d.Type.Results == nil || len(d.Type.Results.List) != 1 {
				continue
			}
			ret, ok := d.Type.Results.List[0].Type.(*ast.IndexListExpr)
			if !ok || !isYangSelector(ret.X, "ListDescriptor") {
				continue
			}
			if row, ok := ret.Indices[0].(*ast.Ident); ok && row.Name == "Peer" {
				descriptors[d.Name.Name] = d
			}
		}
	}

	for _, pair := range []struct{ property, a, b, field string }{
		{"leaf type", "ByTypeA", "ByTypeB", "Setting"},
		{"presence", "ByPresenceA", "ByPresenceB", "Marker"},
		{"child module", "ByModuleA", "ByModuleB", "Slot"},
	} {
		ta, tb := fieldTypes[pair.a][pair.field], fieldTypes[pair.b][pair.field]
		if ta == "" || tb == "" {
			t.Errorf("%s: %s.%s = %q, %s.%s = %q; want both emitted", pair.property, pair.a, pair.field, ta, pair.b, pair.field, tb)
			continue
		}
		if ta == tb {
			t.Errorf("%s: %s.%s and %s.%s share type %s; nodes that differ in %s must not share a type",
				pair.property, pair.a, pair.field, pair.b, pair.field, ta, pair.property)
		}
	}
	if got := fieldTypes["ByOwnerB"]["FixtureAug"]; !strings.Contains(got, "fixtureaug.ByOwnerBAugment") {
		t.Errorf("ByOwnerB.FixtureAug = %q, want fixtureaug.ByOwnerBAugment", got)
	}

	if got, want := fieldTypes["PrimaryGroup"]["Peer"], "[]Peer"; got != want {
		t.Errorf("PrimaryGroup.Peer = %q, want %q", got, want)
	}
	if got, want := fieldTypes["SecondaryGroup"]["Peer"], "[]Peer"; got != want {
		t.Errorf("SecondaryGroup.Peer = %q, want %q", got, want)
	}
	if len(descriptors) != 2 {
		t.Fatalf("got %d descriptors over Peer, want one per grouping instance (2)", len(descriptors))
	}
	keys := make(map[string]bool)
	containers := make(map[string]bool)
	for name, d := range descriptors {
		key := d.Type.Results.List[0].Type.(*ast.IndexListExpr).Indices[1].(*ast.Ident).Name
		keys[key] = true
		body := src[d.Body.Pos()-1 : d.Body.End()-1]
		for _, c := range []string{"primary-group", "secondary-group"} {
			if strings.Contains(body, `"`+c+`", "peer"`) {
				containers[c] = true
			}
		}
		if strings.Contains(body, `"primary-group"`) == strings.Contains(body, `"secondary-group"`) {
			t.Errorf("%s path names both or neither grouping container: %s", name, body)
		}
	}
	if len(keys) != 2 {
		t.Errorf("Peer descriptors share key types %v, want one Key per instance", keys)
	}
	if !containers["primary-group"] || !containers["secondary-group"] {
		t.Errorf("Peer descriptor paths cover %v, want both primary-group and secondary-group", containers)
	}
}

// TestEmitModuleOrderIndependent asserts that emitting the fixture modules
// with the module list reversed produces byte-identical packages, so no
// emission state carries over from one module to the next.
func TestEmitModuleOrderIndependent(t *testing.T) {
	emitAll := func(reverse bool) map[string]string {
		vs := fixtureVendor(t)
		mods := slices.Clone(vs.Modules)
		if reverse {
			slices.Reverse(mods)
		}
		vs.Modules = mods
		out := make(map[string]string, len(mods))
		for _, m := range mods {
			src, err := emitOne(vs, m)
			if err != nil {
				t.Fatalf("emit %s: %v", m.Name, err)
			}
			out[m.Name] = src
		}
		return out
	}
	forward, reversed := emitAll(false), emitAll(true)
	for name, src := range forward {
		if reversed[name] != src {
			t.Errorf("%s differs when the module list is reversed", name)
		}
	}
}

// TestEmitFixtureRepeatedLoadsDeterministic proves that goyang's augment
// survivor does not affect the emitted package bytes.
func TestEmitFixtureRepeatedLoadsDeterministic(t *testing.T) {
	var want map[string]string
	survivors := make(map[string]bool)
	for i := 0; i < 20; i++ {
		vs := fixtureVendor(t)
		main := moduleByName(t, vs, "fixture-main")
		server := main.Entry.Dir["servers"].Dir["server"]
		survivor, err := server.Dir["owner"].InstantiatingModule()
		if err != nil {
			t.Fatalf("owner survivor module: %v", err)
		}
		if survivor != "fixture-aug" && survivor != "fixture-aug2" {
			t.Fatalf("owner survivor module = %q, want one of the augmenting modules", survivor)
		}
		survivors[survivor] = true
		got := make(map[string]string, len(vs.Modules))
		for _, module := range vs.Modules {
			src, err := emitOne(vs, module)
			if err != nil {
				t.Fatalf("emit %s: %v", module.Name, err)
			}
			got[module.Name] = src
		}
		if i == 0 {
			want = got
			continue
		}
		for name, src := range want {
			if got[name] != src {
				t.Fatalf("%s output changed on load %d", name, i)
			}
		}
	}
	if !survivors["fixture-aug"] || !survivors["fixture-aug2"] {
		t.Fatalf("owner survivor modules = %v, want both augmenting modules", survivors)
	}
}

func TestEmitValidatesBeforeClearingOutput(t *testing.T) {
	vs := fixtureVendor(t)
	vs.Modules[0].Entry = nil
	tempDir, err := os.MkdirTemp(".", ".yanggen-emit-test-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(tempDir) })
	outDir := filepath.Join(tempDir, "generated")
	sentinel := filepath.Join(outDir, "fixture", "sentinel")
	if err := os.MkdirAll(filepath.Dir(sentinel), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(sentinel, []byte("keep"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := Emit([]*VendorSet{vs}, outDir); err == nil {
		t.Fatal("Emit accepted a module without an entry tree")
	}
	if got, err := os.ReadFile(sentinel); err != nil {
		t.Fatalf("read sentinel after failed Emit: %v", err)
	} else if string(got) != "keep" {
		t.Fatalf("sentinel = %q, want it preserved", got)
	}
}

func TestEmitFileRenderFailurePreservesExistingOutput(t *testing.T) {
	tempDir, err := os.MkdirTemp(".", ".yanggen-emit-test-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(tempDir) })
	outDir := filepath.Join(tempDir, "generated")

	vsGood := fixtureVendor(t)
	if err := Emit([]*VendorSet{vsGood}, outDir); err != nil {
		t.Fatalf("initial Emit: %v", err)
	}

	vendorDir := filepath.Join(outDir, vsGood.Vendor)
	before := make(map[string][]byte)
	err = filepath.Walk(vendorDir, func(p string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			rel, err := filepath.Rel(vendorDir, p)
			if err != nil {
				return err
			}
			data, err := os.ReadFile(p)
			if err != nil {
				return err
			}
			before[rel] = data
		}
		return nil
	})
	if err != nil {
		t.Fatalf("snapshot vendorDir: %v", err)
	}
	if len(before) == 0 {
		t.Fatal("initial Emit produced no files")
	}

	vsBad := fixtureVendor(t)
	mainMod := moduleByName(t, vsBad, "fixture-main")
	server := mainMod.Entry.Dir["servers"].Dir["server"]
	server.Key = "nonexistent-key"

	err = Emit([]*VendorSet{vsBad}, outDir)
	if err == nil {
		t.Fatal("Emit with invalid list key succeeded, want error")
	}
	if !strings.Contains(err.Error(), "not a leaf child") {
		t.Fatalf("unexpected error: %v", err)
	}

	after := make(map[string][]byte)
	err = filepath.Walk(vendorDir, func(p string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			rel, err := filepath.Rel(vendorDir, p)
			if err != nil {
				return err
			}
			data, err := os.ReadFile(p)
			if err != nil {
				return err
			}
			after[rel] = data
		}
		return nil
	})
	if err != nil {
		t.Fatalf("read vendorDir after failed Emit: %v", err)
	}

	for rel, prev := range before {
		curr, ok := after[rel]
		if !ok {
			t.Errorf("file %s missing after failed Emit", rel)
			continue
		}
		if !bytes.Equal(prev, curr) {
			t.Errorf("file %s content changed after failed Emit", rel)
		}
	}
	for rel := range after {
		if _, ok := before[rel]; !ok {
			t.Errorf("unexpected new file %s found after failed Emit", rel)
		}
	}

	entries, err := os.ReadDir(outDir)
	if err != nil {
		t.Fatalf("ReadDir outDir: %v", err)
	}
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), ".") {
			t.Errorf("temporary directory/file %s leaked under outDir", e.Name())
		}
	}
}

// TestGoldenPackagesBuild compiles the committed golden packages, so
// the emitted code is known to type-check against the runtime — the
// go tool skips testdata in wildcard walks, so each package is built
// by explicit path.
func TestGoldenPackagesBuild(t *testing.T) {
	if testing.Short() {
		t.Skip("compilation exec test skipped in -short mode")
	}
	entries, err := os.ReadDir(filepath.Join("testdata", "golden", "fixture"))
	if err != nil {
		t.Skipf("no goldens yet: %v", err)
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		dir := "./" + filepath.Join("testdata", "golden", "fixture", e.Name())
		cmd := exec.Command("go", "build", dir)
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Errorf("go build %s: %v\n%s", dir, err, out)
		}
	}
}

// TestEmitNoUnderscores parses the golden fixture output with go/parser and
// walks every declaration, asserting: no identifier or struct field contains '_',
// Servers_Server is now ServersServer, and companion/child clash resolution holds,
// including a sibling struct (server-schema) whose name equals a list's schema var.
func TestEmitNoUnderscores(t *testing.T) {
	goldenRoot := filepath.Join("testdata", "golden", "fixture")
	entries, err := os.ReadDir(goldenRoot)
	if err != nil {
		t.Fatalf("read golden dir: %v", err)
	}

	foundServersServer := false
	foundServersSchema := false
	foundServerKey := false
	foundSchemaChild := false
	foundKeyChild := false
	foundSiblingStruct := false
	foundSchemaSiblingClash := false

	schemaSiblingRE := regexp.MustCompile(`^ServersServerSchemaX[0-9a-f]{6}$`)

	fset := token.NewFileSet()
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		pkgDir := filepath.Join(goldenRoot, e.Name())
		files, err := os.ReadDir(pkgDir)
		if err != nil {
			t.Fatalf("read %s: %v", pkgDir, err)
		}
		for _, f := range files {
			if f.IsDir() || !strings.HasSuffix(f.Name(), ".go") {
				continue
			}
			filePath := filepath.Join(pkgDir, f.Name())
			file, err := parser.ParseFile(fset, filePath, nil, 0)
			if err != nil {
				t.Fatalf("parse %s: %v", filePath, err)
			}
			for _, decl := range file.Decls {
				switch d := decl.(type) {
				case *ast.GenDecl:
					for _, spec := range d.Specs {
						switch s := spec.(type) {
						case *ast.TypeSpec:
							name := s.Name.Name
							if strings.Contains(name, "_") {
								t.Errorf("%s: type %q contains underscore", f.Name(), name)
							}
							if name == "ServersServer" {
								foundServersServer = true
							}
							if name == "Schema" {
								foundSchemaChild = true
							}
							if name == "Key" {
								foundKeyChild = true
							}
							if name == "ServerKey" {
								foundServerKey = true
							}
							if name == "ServersServerSchema" {
								foundSiblingStruct = true
							}
							if st, ok := s.Type.(*ast.StructType); ok {
								for _, field := range st.Fields.List {
									for _, id := range field.Names {
										if strings.Contains(id.Name, "_") {
											t.Errorf("%s: struct %s field %q contains underscore", f.Name(), name, id.Name)
										}
									}
								}
							}
						case *ast.ValueSpec:
							for _, id := range s.Names {
								name := id.Name
								if strings.Contains(name, "_") {
									t.Errorf("%s: var/const %q contains underscore", f.Name(), name)
								}
								if name == "ServersSchema" {
									foundServersSchema = true
								}
								if schemaSiblingRE.MatchString(name) {
									foundSchemaSiblingClash = true
								}
								if name == "ServersServerSchema" {
									t.Errorf("%s: var %q takes the sibling struct's name", f.Name(), name)
								}
							}
						}
					}
				case *ast.FuncDecl:
					name := d.Name.Name
					if strings.Contains(name, "_") {
						t.Errorf("%s: func %q contains underscore", f.Name(), name)
					}
				}
			}
		}
	}

	if !foundServersServer {
		t.Error("type ServersServer not found in golden fixtures")
	}
	if !foundServersSchema {
		t.Error("var ServersSchema companion not found in golden fixtures")
	}
	if !foundServerKey {
		t.Error("type ServerKey companion not found in golden fixtures")
	}
	if !foundSchemaChild {
		t.Error("child container Schema not found in golden fixtures")
	}
	if !foundKeyChild {
		t.Error("child container Key not found in golden fixtures")
	}
	if !foundSiblingStruct {
		t.Error("sibling container type ServersServerSchema not found in golden fixtures")
	}
	if !foundSchemaSiblingClash {
		t.Error("list schema var ServersServerSchemaX<hex> not found in golden fixtures")
	}
}

// TestGoldenCompanionCommentsAndSingleLineFields ensures every exported identifier has
// a doc comment, no companion comment contains a /-separated path, and simple
// field literals in Schema.Fields sit on a single line.
func TestGoldenCompanionCommentsAndSingleLineFields(t *testing.T) {
	goldenDir := filepath.Join("testdata", "golden", "fixture")
	entries, err := os.ReadDir(goldenDir)
	if err != nil {
		t.Fatal(err)
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		pkgDir := filepath.Join(goldenDir, entry.Name())
		files, err := os.ReadDir(pkgDir)
		if err != nil {
			t.Fatal(err)
		}
		for _, f := range files {
			if !strings.HasSuffix(f.Name(), ".go") {
				continue
			}
			filePath := filepath.Join(pkgDir, f.Name())
			content, err := os.ReadFile(filePath)
			if err != nil {
				t.Fatal(err)
			}
			fset := token.NewFileSet()
			file, err := parser.ParseFile(fset, filePath, content, parser.ParseComments)
			if err != nil {
				t.Fatalf("%s does not parse: %v", filePath, err)
			}

			// Companions are selected by declaration kind, not by name, so a
			// hash-suffixed companion (FooDescriptorX1a2b3c) is still checked:
			// funcs returning yang.ListDescriptor, the Key index of that
			// result, the Row index when it is a flat row (a struct with an
			// Entry field), and vars whose value is a &yang.Schema literal.
			flatRows := make(map[string]bool)
			for _, decl := range file.Decls {
				gd, ok := decl.(*ast.GenDecl)
				if !ok {
					continue
				}
				for _, spec := range gd.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					st, ok := ts.Type.(*ast.StructType)
					if !ok {
						continue
					}
					for _, fld := range st.Fields.List {
						for _, n := range fld.Names {
							if n.Name == "Entry" {
								flatRows[ts.Name.Name] = true
							}
						}
					}
				}
			}
			companionFuncs := make(map[string]bool)
			companionTypes := make(map[string]bool)
			for _, decl := range file.Decls {
				fn, ok := decl.(*ast.FuncDecl)
				if !ok || fn.Type.Results == nil || len(fn.Type.Results.List) != 1 {
					continue
				}
				ret, ok := fn.Type.Results.List[0].Type.(*ast.IndexListExpr)
				if !ok || !isYangSelector(ret.X, "ListDescriptor") || len(ret.Indices) != 2 {
					continue
				}
				companionFuncs[fn.Name.Name] = true
				if row, ok := ret.Indices[0].(*ast.Ident); ok && flatRows[row.Name] {
					companionTypes[row.Name] = true
				}
				if key, ok := ret.Indices[1].(*ast.Ident); ok {
					companionTypes[key.Name] = true
				}
			}

			for _, decl := range file.Decls {
				switch d := decl.(type) {
				case *ast.GenDecl:
					for _, spec := range d.Specs {
						switch s := spec.(type) {
						case *ast.TypeSpec:
							if !ast.IsExported(s.Name.Name) {
								continue
							}
							doc := d.Doc.Text()
							if doc == "" && s.Doc != nil {
								doc = s.Doc.Text()
							}
							if strings.TrimSpace(doc) == "" {
								t.Errorf("%s: exported type %s missing doc comment", f.Name(), s.Name.Name)
							}
							if companionTypes[s.Name.Name] && strings.Contains(doc, "/") {
								t.Errorf("%s: companion type %s comment contains '/': %q", f.Name(), s.Name.Name, doc)
							}
						case *ast.ValueSpec:
							for i, id := range s.Names {
								if !ast.IsExported(id.Name) {
									continue
								}
								doc := d.Doc.Text()
								if doc == "" && s.Doc != nil {
									doc = s.Doc.Text()
								}
								if strings.TrimSpace(doc) == "" {
									t.Errorf("%s: exported var %s missing doc comment", f.Name(), id.Name)
								}
								if i < len(s.Values) && isSchemaLiteral(s.Values[i]) && strings.Contains(doc, "/") {
									t.Errorf("%s: companion var %s comment contains '/': %q", f.Name(), id.Name, doc)
								}
							}
						}
					}
				case *ast.FuncDecl:
					if !ast.IsExported(d.Name.Name) {
						continue
					}
					doc := d.Doc.Text()
					if strings.TrimSpace(doc) == "" {
						t.Errorf("%s: exported func %s missing doc comment", f.Name(), d.Name.Name)
					}
					if companionFuncs[d.Name.Name] && strings.Contains(doc, "/") {
						t.Errorf("%s: companion func %s comment contains '/': %q", f.Name(), d.Name.Name, doc)
					}
				}
			}

			// Verify single-line field literals in schema Fields slices.
			ast.Inspect(file, func(n ast.Node) bool {
				cl, ok := n.(*ast.CompositeLit)
				if !ok {
					return true
				}
				if arrType, ok := cl.Type.(*ast.ArrayType); ok {
					if sel, ok := arrType.Elt.(*ast.SelectorExpr); ok && sel.Sel.Name == "Field" {
						for _, elt := range cl.Elts {
							fieldLit, ok := elt.(*ast.CompositeLit)
							if !ok {
								continue
							}
							hasMultiLineType := false
							for _, eltItem := range fieldLit.Elts {
								if kv, ok := eltItem.(*ast.KeyValueExpr); ok {
									if k, ok := kv.Key.(*ast.Ident); ok && k.Name == "Type" {
										if _, isComp := kv.Value.(*ast.UnaryExpr); isComp {
											hasMultiLineType = true
										}
									}
								}
							}
							if hasMultiLineType {
								continue
							}
							startPos := fset.Position(fieldLit.Pos())
							endPos := fset.Position(fieldLit.End())
							if startPos.Line != endPos.Line {
								t.Errorf("%s: line %d: field literal spans multiple lines (%d to %d)",
									f.Name(), startPos.Line, startPos.Line, endPos.Line)
							}
						}
					}
				}
				return true
			})
		}
	}
}

// isYangSelector reports whether e is the selector yang.<name>.
func isYangSelector(e ast.Expr, name string) bool {
	sel, ok := e.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != name {
		return false
	}
	pkg, ok := sel.X.(*ast.Ident)
	return ok && pkg.Name == "yang"
}

// isSchemaLiteral reports whether e is a &yang.Schema{...} literal.
func isSchemaLiteral(e ast.Expr) bool {
	u, ok := e.(*ast.UnaryExpr)
	if !ok || u.Op != token.AND {
		return false
	}
	cl, ok := u.X.(*ast.CompositeLit)
	return ok && isYangSelector(cl.Type, "Schema")
}
