package main

import (
	"fmt"
	"go/format"
	"slices"
	"strings"

	"github.com/dave/jennifer/jen"
	goyang "github.com/openconfig/goyang/pkg/yang"
)

// emit_module.go renders one module's binding package: typed structs
// for containers and lists, one yang.Schema descriptor per struct,
// identity values, composite key structs (ancestor keys included for
// flattened nested lists), and descriptor functions — one
// per list, plus one per top-level container (deeper subtrees compose
// yang.SubtreeDescriptor from the exported schema and a path). Wire
// codecs are the runtime's generic schema-driven implementations, so
// generated code consumes only src/protocol/yang's public API and
// one struct serves all three wire forms.
//
// Two scale rules shaped this emitter (the IOS-XE native module is a
// quarter-million-line package):
//   - descriptors are functions, not vars — a var per descriptor
//     turns package init into one function large enough to break the
//     Go compiler's SSA passes;
//   - output is chunked into multiple files of bounded size, since
//     schema vars are pure static data but a single-file module of
//     hundreds of megabytes is unusable for every tool downstream.

// chunkByteBudget bounds one emitted file's pre-format size.
const chunkByteBudget = 2 << 20

// pathSeg is one ancestry step used for descriptor paths.
type pathSeg struct {
	module    string
	namespace string
	name      string
}

// ancestorList records one enclosing list level for nested-list
// flattening.
type ancestorList struct {
	entryName  string   // YANG list name
	structName string   // generated struct name
	keys       []string // key leaf names in YANG order
}

// moduleEmitter carries the per-module emission state. Top-level
// declarations accumulate as fragments that assembleChunks later
// groups into files.
type moduleEmitter struct {
	m     *LoadedModule
	scope *nameScope
	frags []string
}

// addCommented renders a doc comment plus declaration as one
// fragment.
func (em *moduleEmitter) addCommented(comment string, code jen.Code) {
	em.frags = append(em.frags, fmt.Sprintf("// %s\n%#v", comment, code))
}

// emitModuleFiles renders the module's binding package as one or more
// chunked files, keyed by filename.
func emitModuleFiles(m *LoadedModule) (map[string][]byte, error) {
	em := &moduleEmitter{m: m, scope: newNameScope()}
	em.emitIdentities()

	for _, child := range sortedChildren(m.Entry) {
		if !isDataDir(child) {
			continue
		}
		if err := em.emitNode(child, "", nil, nil); err != nil {
			return nil, err
		}
	}
	return em.assembleChunks()
}

// assembleChunks groups fragments into files within the byte budget
// and formats each.
func (em *moduleEmitter) assembleChunks() (map[string][]byte, error) {
	var chunks [][]string
	var cur []string
	size := 0
	for _, frag := range em.frags {
		if size > 0 && size+len(frag) > chunkByteBudget {
			chunks = append(chunks, cur)
			cur, size = nil, 0
		}
		cur = append(cur, frag)
		size += len(frag) + 2
	}
	chunks = append(chunks, cur) // always at least one file, even if empty

	header := fmt.Sprintf(`// Code generated by yanggen. DO NOT EDIT.
// generator: %s
// module: %s revision: %s
// source sha256: %s

`, generatorVersion, em.m.Name, em.m.Revision, em.m.SourceSHA)

	out := make(map[string][]byte, len(chunks))
	for i, chunk := range chunks {
		var b strings.Builder
		b.WriteString(header)
		if i == 0 {
			fmt.Fprintf(&b, "// Package %s binds the YANG module %s.\n", em.m.Package, em.m.Name)
		}
		fmt.Fprintf(&b, "package %s\n\n", em.m.Package)
		body := strings.Join(chunk, "\n\n")
		if strings.Contains(body, "yang.") {
			fmt.Fprintf(&b, "import yang %q\n\n", yangPkg)
		}
		b.WriteString(body)
		b.WriteString("\n")

		src, err := format.Source([]byte(b.String()))
		if err != nil {
			return nil, &LoadError{Vendor: em.m.Vendor, Module: em.m.Name, Issue: fmt.Sprintf("format chunk %d", i), wrapped: err}
		}
		name := em.m.Package + ".go"
		if len(chunks) > 1 {
			name = fmt.Sprintf("%s_p%03d.go", em.m.Package, i)
		}
		out[name] = src
	}
	return out, nil
}

// emitIdentities renders one yang.Identity value per identity the
// module defines.
func (em *moduleEmitter) emitIdentities() {
	ids := em.m.Module.Identity
	sorted := make([]string, 0, len(ids))
	for _, id := range ids {
		sorted = append(sorted, id.Name)
	}
	slices.Sort(sorted)
	for _, name := range sorted {
		goName := em.scope.claim("Identity_"+camel(name), "identity:"+name)
		em.addCommented(
			fmt.Sprintf("%s is the %s identity %q.", goName, em.m.Name, name),
			jen.Var().Id(goName).Op("=").Qual(yangPkg, "Identity").Values(jen.Dict{
				jen.Id("Module"): jen.Lit(em.m.Name),
				jen.Id("Name"):   jen.Lit(name),
			}),
		)
	}
}

// emitNode renders the struct, schema, and descriptors for one
// container or list entry, then recurses into its child directories.
func (em *moduleEmitter) emitNode(e *goyang.Entry, parentStruct string, path []pathSeg, ancestors []ancestorList) error {
	structName := em.structName(e, parentStruct)
	nodePath := append(append([]pathSeg{}, path...), em.segFor(e))

	children := dataChildren(e)
	fieldScope := newNameScope()

	// Claim child struct names up front so field types can reference
	// them before the children are rendered.
	childStructs := make(map[string]string)
	for _, c := range children {
		if isDataDir(c) {
			childStructs[c.Name] = em.structName(c, structName)
		}
	}

	structFields, schemaFields := em.emitFields(e, children, childStructs, fieldScope)

	em.addCommented(
		fmt.Sprintf("%s is the %s node %s.", structName, em.m.Name, e.Path()),
		jen.Type().Id(structName).Struct(structFields...),
	)

	em.emitSchema(e, structName, schemaFields)

	if e.IsList() {
		if err := em.emitListArtifacts(e, structName, nodePath, ancestors, fieldScope); err != nil {
			return err
		}
	} else if len(nodePath) == 1 {
		em.emitContainerDescriptor(structName, nodePath)
	}

	nextAncestors := ancestors
	if e.IsList() {
		nextAncestors = append(append([]ancestorList{}, ancestors...), ancestorList{
			entryName:  e.Name,
			structName: structName,
			keys:       strings.Fields(e.Key),
		})
	}
	for _, c := range children {
		if isDataDir(c) {
			if err := em.emitNode(c, structName, nodePath, nextAncestors); err != nil {
				return err
			}
		}
	}
	return nil
}

// emitFields renders e's data children into the parent struct's field
// list and the matching [yang.Field] literals for its schema, in one
// pass so the two stay index-for-index aligned. childStructs maps a
// container or list child's entry name to the Go struct name already
// claimed for it; fieldScope keeps the Go field names unique within
// the parent struct.
func (em *moduleEmitter) emitFields(
	e *goyang.Entry, children []*goyang.Entry, childStructs map[string]string, fieldScope *nameScope,
) (structFields, schemaFields []jen.Code) {
	structFields = make([]jen.Code, 0, len(children))
	schemaFields = make([]jen.Code, 0, len(children))

	for _, c := range children {
		goName := fieldScope.claim(camel(c.Name), c.Path())

		dict := jen.Dict{
			jen.Id("GoName"): jen.Lit(goName),
			jen.Id("Name"):   jen.Lit(c.Name),
		}
		if mod := em.moduleOf(c); mod != em.moduleOf(e) {
			dict[jen.Id("Module")] = jen.Lit(mod)
			dict[jen.Id("Namespace")] = jen.Lit(namespaceOf(c))
		}

		switch {
		case isDataDir(c):
			childName := childStructs[c.Name]
			dict[jen.Id("Child")] = jen.Id(schemaVarName(childName))
			var ft *jen.Statement
			if c.IsList() {
				dict[jen.Id("List")] = jen.True()
				ft = jen.Index().Id(childName)
			} else {
				ft = jen.Op("*").Id(childName)
			}
			structFields = append(structFields, jen.Id(goName).Add(ft))
		case c.IsLeafList():
			lt := mapLeafType(c)
			dict[jen.Id("LeafList")] = jen.True()
			dict[jen.Id("Type")] = lt.typeExpr()
			structFields = append(structFields, jen.Id(goName).Index().Add(lt.goType()))
		case c.IsLeaf():
			lt := mapLeafType(c)
			dict[jen.Id("Type")] = lt.typeExpr()
			ft := lt.goType()
			if lt.pointer {
				ft = jen.Op("*").Add(ft)
			}
			structFields = append(structFields, jen.Id(goName).Add(ft))
		default:
			continue
		}
		schemaFields = append(schemaFields, jen.Values(dict))
	}

	return structFields, schemaFields
}

// emitSchema renders the package-level [yang.Schema] var describing e,
// the descriptor every generic codec reads at runtime.
func (em *moduleEmitter) emitSchema(e *goyang.Entry, structName string, schemaFields []jen.Code) {
	schemaDict := jen.Dict{
		jen.Id("Module"):    jen.Lit(em.moduleOf(e)),
		jen.Id("Namespace"): jen.Lit(namespaceOf(e)),
		jen.Id("Name"):      jen.Lit(e.Name),
		jen.Id("Fields"):    jen.Index().Qual(yangPkg, "Field").Values(schemaFields...),
	}
	if e.IsList() && e.Key != "" {
		keyLits := make([]jen.Code, 0, 4)
		for _, k := range strings.Fields(e.Key) {
			keyLits = append(keyLits, jen.Lit(k))
		}
		schemaDict[jen.Id("Keys")] = jen.Index().String().Values(keyLits...)
	}
	if isPresence(e) {
		schemaDict[jen.Id("Presence")] = jen.True()
	}

	em.addCommented(
		fmt.Sprintf("%s describes %s for the generic codecs.", schemaVarName(structName), e.Path()),
		jen.Var().Id(schemaVarName(structName)).Op("=").Op("&").Qual(yangPkg, "Schema").Values(schemaDict),
	)
}

// emitContainerDescriptor renders the synthetic-row descriptor
// function for a top-level container (the synthetic non-list
// subtree row).
// Deeper subtrees compose yang.SubtreeDescriptor from the exported
// schema and path.
func (em *moduleEmitter) emitContainerDescriptor(structName string, path []pathSeg) {
	descName := em.scope.claim(structName+"Descriptor", "desc:"+structName)
	em.addCommented(
		fmt.Sprintf("%s watches the %s subtree as one synthetic row.", descName, structName),
		jen.Func().Id(descName).Params().Qual(yangPkg, "ListDescriptor").Index(jen.List(jen.Id(structName), jen.Struct())).Block(
			jen.Return(jen.Qual(yangPkg, "SubtreeDescriptor").Index(jen.Id(structName)).Call(
				jen.Id(schemaVarName(structName)), em.pathExpr(path))),
		),
	)
}

// emitListArtifacts renders a list's key struct, flat-row wrapper for
// nested lists, and descriptor function.
func (em *moduleEmitter) emitListArtifacts(e *goyang.Entry, structName string, path []pathSeg, ancestors []ancestorList, fieldScope *nameScope) error {
	keyNames := strings.Fields(e.Key)
	if len(keyNames) == 0 {
		// A keyless list (config false) has no stable row identity;
		// no descriptor is emitted.
		return nil
	}

	keyStructName := em.scope.claim(structName+"Key", "key:"+structName)
	keyScope := newNameScope()

	type ancKeyField struct{ goName, listName, keyName string }
	type ownKeyField struct {
		goName, leafName string
		lt               leafType
		fieldGo          string
	}
	var ancFields []ancKeyField
	var ownFields []ownKeyField

	for _, a := range ancestors {
		for _, k := range a.keys {
			goName := keyScope.claim(camel(a.entryName)+"_"+camel(k), "anc:"+a.structName+":"+k)
			ancFields = append(ancFields, ancKeyField{goName: goName, listName: a.entryName, keyName: k})
		}
	}
	for _, k := range keyNames {
		child := e.Dir[k]
		if child == nil || !child.IsLeaf() {
			return &LoadError{
				Vendor: em.m.Vendor, Module: em.m.Name,
				Issue: fmt.Sprintf("list %s key %q is not a leaf child", e.Path(), k),
			}
		}
		goName := keyScope.claim(camel(k), "own:"+k)
		ownFields = append(ownFields, ownKeyField{
			goName: goName, leafName: k,
			lt:      mapLeafType(child),
			fieldGo: fieldScope.claim(camel(k), child.Path()),
		})
	}

	keyFields := make([]jen.Code, 0, len(ancFields)+len(ownFields))
	for _, af := range ancFields {
		keyFields = append(keyFields, jen.Id(af.goName).String())
	}
	for _, of := range ownFields {
		if of.lt.keyString {
			keyFields = append(keyFields, jen.Id(of.goName).String())
			continue
		}
		keyFields = append(keyFields, jen.Id(of.goName).Add(of.lt.goType()))
	}
	em.addCommented(
		fmt.Sprintf("%s is %s's row identity (ancestor keys in canonical form).", keyStructName, structName),
		jen.Type().Id(keyStructName).Struct(keyFields...),
	)

	// ownKeyAssigns renders the own-key extraction statements from a
	// value expression yielding *<structName>.
	ownKeyAssigns := func(recv func() *jen.Statement) []jen.Code {
		stmts := make([]jen.Code, 0, len(ownFields))
		for _, of := range ownFields {
			field := func() *jen.Statement { return recv().Dot(of.fieldGo) }
			switch {
			case of.lt.keyString:
				stmts = append(stmts, jen.If(field().Clone().Op("!=").Nil()).Block(
					jen.Id("k").Dot(of.goName).Op("=").Qual(yangPkg, "CanonicalKey").Call(field()),
				))
			case of.lt.pointer:
				stmts = append(stmts, jen.If(field().Clone().Op("!=").Nil()).Block(
					jen.Id("k").Dot(of.goName).Op("=").Op("*").Add(field()),
				))
			default:
				stmts = append(stmts, jen.Id("k").Dot(of.goName).Op("=").Add(field()))
			}
		}
		return stmts
	}

	descName := em.scope.claim(structName+"Descriptor", "desc:"+structName)

	if len(ancestors) == 0 {
		em.addCommented(
			fmt.Sprintf("%s is the list descriptor callers hand to a protocol library.", descName),
			jen.Func().Id(descName).Params().Qual(yangPkg, "ListDescriptor").Index(jen.List(jen.Id(structName), jen.Id(keyStructName))).Block(
				jen.Return(jen.Qual(yangPkg, "ListDescriptor").Index(jen.List(jen.Id(structName), jen.Id(keyStructName))).Values(jen.Dict{
					jen.Id("Path"): em.pathExpr(path),
					jen.Id("Codec"): jen.Qual(yangPkg, "StructRowCodec").Call(
						jen.Id(schemaVarName(structName)),
						jen.Func().Params(jen.Id("r").Op("*").Id(structName)).Id(keyStructName).Block(
							append([]jen.Code{jen.Var().Id("k").Id(keyStructName)},
								append(ownKeyAssigns(func() *jen.Statement { return jen.Id("r") }),
									jen.Return(jen.Id("k")))...)...,
						),
					),
				})),
			),
		)
		return nil
	}

	// Nested list: flat-row wrapper carrying ancestor keys.
	flatName := em.scope.claim(structName+"FlatRow", "flat:"+structName)
	flatFields := make([]jen.Code, 0, len(ancFields)+1)
	for _, af := range ancFields {
		flatFields = append(flatFields, jen.Id(af.goName).String())
	}
	flatFields = append(flatFields, jen.Id("Entry").Id(structName))
	em.addCommented(
		fmt.Sprintf("%s flattens one %s entry with its ancestor list keys.", flatName, structName),
		jen.Type().Id(flatName).Struct(flatFields...),
	)

	chainExpr := func() *jen.Statement {
		chainElems := make([]jen.Code, 0, len(ancestors)+1)
		for _, a := range ancestors {
			chainElems = append(chainElems, jen.Id(schemaVarName(a.structName)))
		}
		chainElems = append(chainElems, jen.Id(schemaVarName(structName)))
		return jen.Index().Op("*").Qual(yangPkg, "Schema").Values(chainElems...)
	}

	levelOf := func(af ancKeyField) int {
		for i, a := range ancestors {
			if a.entryName == af.listName {
				return i
			}
		}
		return 0
	}

	flatAssigns := func(entryVar string) jen.Dict {
		d := jen.Dict{jen.Id("Entry"): jen.Id(entryVar).Dot("Entry")}
		for _, af := range ancFields {
			d[jen.Id(af.goName)] = jen.Qual(yangPkg, "AncestorKey").Call(
				jen.Id(entryVar).Dot("AncestorKeys"), jen.Lit(levelOf(af)), jen.Lit(af.keyName))
		}
		return d
	}

	decodeFn := func(runtimeFn string) *jen.Statement {
		return jen.Func().Params(jen.Id("data").Index().Byte()).Params(jen.Index().Id(flatName), jen.Error()).Block(
			jen.Id("chain").Op(":=").Add(chainExpr()),
			jen.List(jen.Id("entries"), jen.Err()).Op(":=").Qual(yangPkg, runtimeFn).Index(jen.Id(structName)).Call(jen.Id("chain"), jen.Id("data")),
			jen.If(jen.Err().Op("!=").Nil()).Block(jen.Return(jen.Nil(), jen.Err())),
			jen.Id("rows").Op(":=").Make(jen.Index().Id(flatName), jen.Lit(0), jen.Len(jen.Id("entries"))),
			jen.For(jen.List(jen.Id("_"), jen.Id("en")).Op(":=").Range().Id("entries")).Block(
				jen.Id("rows").Op("=").Append(jen.Id("rows"), jen.Id(flatName).Values(flatAssigns("en"))),
			),
			jen.Return(jen.Id("rows"), jen.Nil()),
		)
	}

	keyFnStmts := []jen.Code{jen.Var().Id("k").Id(keyStructName)}
	for _, af := range ancFields {
		keyFnStmts = append(keyFnStmts, jen.Id("k").Dot(af.goName).Op("=").Id("r").Dot(af.goName))
	}
	keyFnStmts = append(keyFnStmts, ownKeyAssigns(func() *jen.Statement { return jen.Id("r").Dot("Entry") })...)
	keyFnStmts = append(keyFnStmts, jen.Return(jen.Id("k")))

	em.addCommented(
		fmt.Sprintf("%s is the flattened-row descriptor for the nested list %s.", descName, structName),
		jen.Func().Id(descName).Params().Qual(yangPkg, "ListDescriptor").Index(jen.List(jen.Id(flatName), jen.Id(keyStructName))).Block(
			jen.Return(jen.Qual(yangPkg, "ListDescriptor").Index(jen.List(jen.Id(flatName), jen.Id(keyStructName))).Values(jen.Dict{
				jen.Id("Path"): em.pathExpr(path),
				jen.Id("Codec"): jen.Qual(yangPkg, "RowCodec").Index(jen.List(jen.Id(flatName), jen.Id(keyStructName))).Values(jen.Dict{
					jen.Id("DecodeXML"):  decodeFn("DecodeXMLNested"),
					jen.Id("DecodeJSON"): decodeFn("DecodeJSONNested"),
					jen.Id("Equal"): jen.Func().Params(jen.Id("a"), jen.Id("b").Id(flatName)).Bool().Block(
						jen.Return(jen.Qual(yangPkg, "EqualStructs").Call(jen.Id("a"), jen.Id("b"))),
					),
					jen.Id("Merge"): jen.Func().Params(jen.Id("base"), jen.Id("update").Id(flatName)).Id(flatName).Block(
						jen.Id("base").Dot("Entry").Op("=").Qual(yangPkg, "MergeStructs").Call(
							jen.Id(schemaVarName(structName)), jen.Id("base").Dot("Entry"), jen.Id("update").Dot("Entry")),
						jen.Return(jen.Id("base")),
					),
					jen.Id("Key"): jen.Func().Params(jen.Id("r").Id(flatName)).Id(keyStructName).Block(keyFnStmts...),
				}),
			})),
		),
	)
	return nil
}

// structName claims the deterministic struct name for e.
func (em *moduleEmitter) structName(e *goyang.Entry, parent string) string {
	want := camel(e.Name)
	if parent != "" {
		want = parent + "_" + want
	}
	return em.scope.claim(want, e.Path())
}

// schemaVarName derives the schema variable's name from a struct
// name.
func schemaVarName(structName string) string { return structName + "Schema" }

// segFor builds the descriptor path segment for e.
func (em *moduleEmitter) segFor(e *goyang.Entry) pathSeg {
	return pathSeg{name: e.Name, module: em.moduleOf(e), namespace: namespaceOf(e)}
}

// pathExpr renders a yang.Path literal for the node's ancestry, with
// Module/Namespace set on module boundaries only.
func (em *moduleEmitter) pathExpr(path []pathSeg) *jen.Statement {
	segs := make([]jen.Code, 0, len(path))
	prevMod := ""
	for _, s := range path {
		d := jen.Dict{jen.Id("Name"): jen.Lit(s.name)}
		if s.module != prevMod {
			d[jen.Id("Module")] = jen.Lit(s.module)
			d[jen.Id("Namespace")] = jen.Lit(s.namespace)
			prevMod = s.module
		}
		segs = append(segs, jen.Values(d))
	}
	return jen.Qual(yangPkg, "Path").Values(jen.Dict{
		jen.Id("Segments"): jen.Index().Qual(yangPkg, "Segment").Values(segs...),
	})
}

// moduleOf returns the defining module's name for an entry.
func (em *moduleEmitter) moduleOf(e *goyang.Entry) string {
	if e == nil || e.Node == nil {
		return em.m.Name
	}
	if root := goyang.RootNode(e.Node); root != nil {
		return root.Name
	}
	return em.m.Name
}

// namespaceOf returns the entry's XML namespace URI.
func namespaceOf(e *goyang.Entry) string {
	if ns := e.Namespace(); ns != nil {
		return ns.Name
	}
	return ""
}

// isDataDir reports whether e is a container or list data node.
func isDataDir(e *goyang.Entry) bool {
	if e.RPC != nil || e.Kind != goyang.DirectoryEntry {
		return false
	}
	if _, isNotification := e.Node.(*goyang.Notification); isNotification {
		return false
	}
	return true
}

// dataChildren returns e's data children sorted by name, with
// choice/case layers flattened away.
func dataChildren(e *goyang.Entry) []*goyang.Entry {
	var out []*goyang.Entry
	var collect func(dir map[string]*goyang.Entry)
	collect = func(dir map[string]*goyang.Entry) {
		for _, name := range sortedKeys(dir) {
			c := dir[name]
			switch {
			case c.IsChoice() || c.IsCase():
				collect(c.Dir)
			case c.RPC != nil, isNonData(c):
			default:
				out = append(out, c)
			}
		}
	}
	collect(e.Dir)
	slices.SortFunc(out, func(a, b *goyang.Entry) int { return strings.Compare(a.Name, b.Name) })
	return out
}

// isNonData filters notification/anydata/anyxml children.
func isNonData(e *goyang.Entry) bool {
	switch e.Kind {
	case goyang.AnyDataEntry, goyang.AnyXMLEntry:
		return true
	}
	_, isNotification := e.Node.(*goyang.Notification)
	return isNotification
}

// isPresence reports whether e is a presence container.
func isPresence(e *goyang.Entry) bool {
	cont, ok := e.Node.(*goyang.Container)
	return ok && cont.Presence != nil
}

// sortedChildren returns e.Dir's entries sorted by name.
func sortedChildren(e *goyang.Entry) []*goyang.Entry {
	out := make([]*goyang.Entry, 0, len(e.Dir))
	for _, name := range sortedKeys(e.Dir) {
		out = append(out, e.Dir[name])
	}
	return out
}
