package main

import (
	"fmt"
	"go/format"
	"regexp"
	"slices"
	"strings"

	"github.com/dave/jennifer/jen"
	goyang "github.com/openconfig/goyang/pkg/yang"
)

// emit_module.go renders one module's binding package. Nodes defined by an
// augmenting module are emitted in that module's package, while the target
// package owns the group field and descriptors for lists below the target.

// chunkByteBudget bounds one emitted file's pre-format size.
const chunkByteBudget = 2 << 20

type pathSeg struct {
	module    string
	namespace string
	name      string
}

type moduleEmitter struct {
	plan  *emissionPlan
	p     *packagePlan
	frags []string
}

// addCommented renders a doc comment plus declaration as one fragment.
func (em *moduleEmitter) addCommented(comment string, code jen.Code) {
	em.frags = append(em.frags, fmt.Sprintf("// %s\n%#v", comment, code))
}

// emitModuleFiles renders a package as one or more chunked files, keyed by
// filename.
func emitModuleFiles(plan *emissionPlan, p *packagePlan) (map[string][]byte, error) {
	em := &moduleEmitter{plan: plan, p: p}
	em.emitModuleVars()
	em.emitIdentities()
	em.emitShapes()
	em.emitGroups()
	if err := em.emitListArtifacts(); err != nil {
		return nil, err
	}
	em.emitTopContainerDescriptors()
	return em.assembleChunks()
}

// assembleChunks groups fragments into files within the byte budget and
// formats each. Imports are selected per chunk so a cross-package reference
// never relies on an import from another chunk.
func (em *moduleEmitter) assembleChunks() (map[string][]byte, error) {
	var chunks [][]string
	var cur []string
	size := 0
	for _, frag := range em.frags {
		if size > 0 && size+len(frag) > chunkByteBudget {
			chunks = append(chunks, cur)
			cur, size = nil, 0
		}
		cur = append(cur, frag)
		size += len(frag) + 2
	}
	chunks = append(chunks, cur)

	header := fmt.Sprintf(`// Code generated by yanggen. DO NOT EDIT.
// generator: %s
// module: %s revision: %s
// source sha256: %s

`, generatorVersion, em.p.module.Name, em.p.module.Revision, em.p.module.SourceSHA)

	out := make(map[string][]byte, len(chunks))
	for i, chunk := range chunks {
		var b strings.Builder
		b.WriteString(header)
		if i == 0 {
			fmt.Fprintf(&b, "// Package %s binds the YANG module %s.\n", em.p.module.Package, em.p.module.Name)
		}
		fmt.Fprintf(&b, "package %s\n\n", em.p.module.Package)
		body := strings.Join(chunk, "\n\n")
		imports := em.chunkImports(body)
		if len(imports) == 1 {
			fmt.Fprintf(&b, "import %s %q\n\n", imports[0].alias, imports[0].path)
		} else if len(imports) > 1 {
			b.WriteString("import (\n")
			for _, imp := range imports {
				fmt.Fprintf(&b, "\t%s %q\n", imp.alias, imp.path)
			}
			b.WriteString(")\n\n")
		}
		b.WriteString(body)
		b.WriteString("\n")

		src, err := format.Source([]byte(b.String()))
		if err != nil {
			return nil, &LoadError{Vendor: em.p.module.Vendor, Module: em.p.module.Name, Issue: fmt.Sprintf("format chunk %d", i), wrapped: err}
		}
		name := em.p.module.Package + ".go"
		if len(chunks) > 1 {
			name = fmt.Sprintf("%s_p%03d.go", em.p.module.Package, i)
		}
		out[name] = src
	}
	return out, nil
}

type generatedImport struct {
	alias string
	path  string
}

func (em *moduleEmitter) chunkImports(body string) []generatedImport {
	var imports []generatedImport
	if strings.Contains(body, "yang.") {
		imports = append(imports, generatedImport{alias: "yang", path: yangPkg})
	}
	for _, p := range em.plan.packages {
		if p == em.p || !containsIdentifier(body, p.module.Package) {
			continue
		}
		imports = append(imports, generatedImport{
			alias: p.module.Package,
			path:  em.plan.importBase + "/" + p.module.Package,
		})
	}
	slices.SortFunc(imports, func(a, b generatedImport) int { return strings.Compare(a.alias, b.alias) })
	return imports
}

var identifierBoundary = regexp.MustCompile(`[A-Za-z0-9_]`)

func containsIdentifier(body, identifier string) bool {
	start := 0
	for {
		index := strings.Index(body[start:], identifier+".")
		if index < 0 {
			return false
		}
		index += start
		if index == 0 || !identifierBoundary.MatchString(body[index-1:index]) {
			return true
		}
		start = index + len(identifier) + 1
	}
}

// emitModuleVars renders package-level *yang.Module variables for every
// module referenced by schemas or descriptor paths in this package.
func (em *moduleEmitter) emitModuleVars() {
	modules := make(map[string]string)
	add := func(name, namespace string) {
		if name == "" {
			return
		}
		if namespace != "" || modules[name] == "" {
			modules[name] = namespace
		}
	}
	for _, shape := range em.p.shapes {
		add(shape.module, shape.namespace)
		for _, group := range shape.representative.groups {
			add(group.module.Name, namespaceOf(group.module.Entry))
		}
	}
	for _, group := range em.p.groups {
		add(group.module.Name, namespaceOf(group.module.Entry))
		for _, child := range group.group.children {
			add(child.module.Name, namespaceOf(child.entry))
		}
	}
	for _, li := range em.p.listInstances {
		for _, segment := range li.path {
			add(segment.module, segment.namespace)
		}
	}
	for _, tc := range em.p.topContainers {
		for _, segment := range tc.path {
			add(segment.module, segment.namespace)
		}
	}

	names := make([]string, 0, len(modules))
	for name := range modules {
		names = append(names, name)
	}
	slices.Sort(names)
	for _, name := range names {
		em.addCommented(
			fmt.Sprintf("%s identifies the %s YANG module.", moduleVarName(name), name),
			jen.Var().Id(moduleVarName(name)).Op("=").Op("&").Qual(yangPkg, "Module").Values(jen.Dict{
				jen.Id("Name"):      jen.Lit(name),
				jen.Id("Namespace"): jen.Lit(modules[name]),
			}),
		)
	}
}

// emitIdentities renders one yang.Identity value per identity the module defines.
func (em *moduleEmitter) emitIdentities() {
	if em.p.module.Module == nil {
		return
	}
	ids := em.p.module.Module.Identity
	sorted := make([]string, 0, len(ids))
	for _, id := range ids {
		sorted = append(sorted, id.Name)
	}
	slices.Sort(sorted)
	for _, name := range sorted {
		goName := em.p.scope.byPath["identity:"+name]
		em.addCommented(
			fmt.Sprintf("%s is the %s identity %q.", goName, em.p.module.Name, name),
			jen.Var().Id(goName).Op("=").Qual(yangPkg, "Identity").Values(jen.Dict{
				jen.Id("Module"): jen.Lit(em.p.module.Name),
				jen.Id("Name"):   jen.Lit(name),
			}),
		)
	}
}

func (em *moduleEmitter) emitShapes() {
	slices.SortFunc(em.p.shapes, func(a, b *nodeShape) int { return strings.Compare(em.p.structName(a.key), em.p.structName(b.key)) })
	for _, shape := range em.p.shapes {
		em.emitShape(shape)
	}
}

func (em *moduleEmitter) emitShape(shape *nodeShape) {
	structName := em.p.structName(shape.key)
	schemaName := em.p.schemaName(shape.key)
	instance := shape.instances[0]
	comment := fmt.Sprintf("%s is the %s node %s.", structName, shape.module, instance.node.dataPath)
	if len(shape.instances) > 1 {
		comment = fmt.Sprintf("%s is the %s node shape instantiated at %d schema paths, such as %s.", structName, shape.module, len(shape.instances), instance.node.dataPath)
	}
	structFields, schemaFields := em.fieldsForNode(shape.representative)
	em.addCommented(comment, jen.Type().Id(structName).Struct(structFields...))

	schemaDict := jen.Dict{
		jen.Id("Fields"): jen.Index().Qual(yangPkg, "Field").Custom(
			jen.Options{Open: "{", Close: "}", Separator: ",", Multi: true}, schemaFields...),
		jen.Id("Module"): jen.Id(moduleVarName(shape.module)),
		jen.Id("Name"):   jen.Lit(shape.name),
	}
	if shape.kind == "list" && shape.representative.entry.Key != "" {
		var keyLits []jen.Code
		for _, key := range strings.Fields(shape.representative.entry.Key) {
			keyLits = append(keyLits, jen.Lit(key))
		}
		schemaDict[jen.Id("Keys")] = jen.Index().String().Values(keyLits...)
	}
	if shape.kind == "presence_container" {
		schemaDict[jen.Id("Presence")] = jen.True()
	}
	em.addCommented(fmt.Sprintf("%s describes %s for the generic codecs.", schemaName, structName), jen.Var().Id(schemaName).Op("=").Op("&").Qual(yangPkg, "Schema").Values(schemaDict))
}

func (em *moduleEmitter) emitGroups() {
	slices.SortFunc(em.p.groups, func(a, b *groupShape) int { return strings.Compare(a.name, b.name) })
	for _, group := range em.p.groups {
		fieldNames := groupFieldNames(group.group)
		var structFields []jen.Code
		var schemaFields []jen.Code
		for _, child := range group.group.children {
			goName := fieldNames[child]
			childSchema, childType, leafList, list, lt := em.childReferences(child)
			if childSchema != nil {
				if list {
					structFields = append(structFields, jen.Id(goName).Index().Add(childType))
				} else {
					structFields = append(structFields, jen.Id(goName).Op("*").Add(childType))
				}
			} else if leafList {
				structFields = append(structFields, jen.Id(goName).Index().Add(lt.goType()))
			} else {
				fieldType := lt.goType()
				if lt.pointer {
					fieldType = jen.Op("*").Add(fieldType)
				}
				structFields = append(structFields, jen.Id(goName).Add(fieldType))
			}

			var parts []jen.Code
			if childSchema != nil {
				parts = append(parts, jen.Id("Child").Op(":").Add(childSchema))
			}
			parts = append(parts, jen.Id("GoName").Op(":").Lit(goName))
			if leafList {
				parts = append(parts, jen.Id("LeafList").Op(":").True())
			}
			if list {
				parts = append(parts, jen.Id("List").Op(":").True())
			}
			parts = append(parts, jen.Id("Name").Op(":").Lit(child.entry.Name))
			if lt.typeExpr != nil {
				parts = append(parts, jen.Id("Type").Op(":").Add(lt.typeExpr()))
			}
			schemaFields = append(schemaFields, jen.Custom(jen.Options{Open: "{", Close: "}", Separator: ", ", Multi: false}, parts...))
		}

		em.addCommented(fmt.Sprintf("%s is the %s augment group at %s.", group.name, group.module.Name, group.target.dataPath), jen.Type().Id(group.name).Struct(structFields...))
		em.addCommented(fmt.Sprintf("%s describes %s group fields with no codec root.", group.schemaName, group.name), jen.Var().Id(group.schemaName).Op("=").Op("&").Qual(yangPkg, "Schema").Values(jen.Dict{
			jen.Id("Fields"): jen.Index().Qual(yangPkg, "Field").Custom(jen.Options{Open: "{", Close: "}", Separator: ",", Multi: true}, schemaFields...),
			jen.Id("Module"): jen.Id(moduleVarName(group.module.Name)),
		}))
	}
}

func (em *moduleEmitter) fieldsForNode(node *dataNodeView) ([]jen.Code, []jen.Code) {
	fieldNames, groupNames := nodeFieldNames(node)
	var structFields []jen.Code
	var schemaFields []jen.Code
	for _, child := range node.children {
		goName := fieldNames[child]
		childSchema, childType, leafList, list, lt := em.childReferences(child)
		if childSchema != nil {
			if list {
				structFields = append(structFields, jen.Id(goName).Index().Add(childType))
			} else {
				structFields = append(structFields, jen.Id(goName).Op("*").Add(childType))
			}
		} else if leafList {
			structFields = append(structFields, jen.Id(goName).Index().Add(lt.goType()))
		} else {
			fieldType := lt.goType()
			if lt.pointer {
				fieldType = jen.Op("*").Add(fieldType)
			}
			structFields = append(structFields, jen.Id(goName).Add(fieldType))
		}
		parts := em.schemaFieldParts(child, goName, childSchema, leafList, list, lt)
		schemaFields = append(schemaFields, parts)
	}
	for _, group := range node.groups {
		goName := groupNames[group]
		groupShape := em.plan.groups[group]
		structFields = append(structFields, jen.Id(goName).Op("*").Add(em.typeRef(groupShape.owner, groupShape.name)))
		schemaFields = append(schemaFields, jen.Custom(jen.Options{Open: "{", Close: "}", Separator: ", ", Multi: false},
			jen.Id("Child").Op(":").Add(em.schemaRef(groupShape.owner, groupShape.schemaName)),
			jen.Id("GoName").Op(":").Lit(goName),
			jen.Id("Group").Op(":").True(),
		))
	}
	return structFields, schemaFields
}

func (em *moduleEmitter) schemaFieldParts(child *dataNodeView, goName string, childSchema *jen.Statement, leafList, list bool, lt leafType) jen.Code {
	var parts []jen.Code
	if childSchema != nil {
		parts = append(parts, jen.Id("Child").Op(":").Add(childSchema))
	}
	parts = append(parts, jen.Id("GoName").Op(":").Lit(goName))
	if leafList {
		parts = append(parts, jen.Id("LeafList").Op(":").True())
	}
	if list {
		parts = append(parts, jen.Id("List").Op(":").True())
	}
	parts = append(parts, jen.Id("Name").Op(":").Lit(child.entry.Name))
	if lt.typeExpr != nil {
		parts = append(parts, jen.Id("Type").Op(":").Add(lt.typeExpr()))
	}
	return jen.Custom(jen.Options{Open: "{", Close: "}", Separator: ", ", Multi: false}, parts...)
}

func (em *moduleEmitter) childReferences(child *dataNodeView) (*jen.Statement, *jen.Statement, bool, bool, leafType) {
	if isDataDir(child.entry) {
		shape := em.plan.nodeShapes[child]
		owner := em.plan.packages[child.module.Name]
		return em.schemaRef(owner, owner.schemaName(shape.key)), em.typeRef(owner, owner.structName(shape.key)), false, child.entry.IsList(), leafType{}
	}
	if child.entry.IsLeafList() {
		return nil, nil, true, false, mapLeafType(child.entry)
	}
	return nil, nil, false, false, mapLeafType(child.entry)
}

func (em *moduleEmitter) emitListArtifacts() error {
	slices.SortFunc(em.p.listInstances, func(a, b *listInstance) int { return strings.Compare(a.node.dataPath, b.node.dataPath) })
	for _, li := range em.p.listInstances {
		if err := em.emitOneList(li); err != nil {
			return err
		}
	}
	return nil
}

func findChildNode(node *dataNodeView, name string) *dataNodeView {
	for _, child := range node.children {
		if child.entry.Name == name {
			return child
		}
	}
	return nil
}

func (em *moduleEmitter) emitOneList(li *listInstance) error {
	e := li.node.entry
	keyNames := strings.Fields(e.Key)
	if len(keyNames) == 0 {
		return nil
	}
	rowOwner := li.rowOwner
	shapeName := rowOwner.structName(li.shapeKey)
	rowType := em.typeRef(rowOwner, shapeName)
	keyStructName := em.p.scope.byPath["key:"+li.node.dataPath]
	keyScope := newNameScope()

	type ancKeyField struct {
		goName  string
		level   int
		keyName string
	}
	type ownKeyField struct {
		goName, leafName string
		lt               leafType
		fieldGo          string
	}
	var ancFields []ancKeyField
	var ownFields []ownKeyField
	for i, ancestor := range li.ancestors {
		for _, key := range ancestor.keys {
			goName := keyScope.claim(camel(ancestor.entryName)+camel(key), fmt.Sprintf("anc:%d:%s:%s", i, ancestor.entryName, key))
			ancFields = append(ancFields, ancKeyField{goName: goName, level: i, keyName: key})
		}
	}
	fieldScope := newNameScope()
	for _, child := range li.node.children {
		fieldScope.claim(camel(child.entry.Name), child.dataPath)
	}
	for _, key := range keyNames {
		child := findChildNode(li.node, key)
		if child == nil || !child.entry.IsLeaf() {
			return &LoadError{Vendor: em.p.module.Vendor, Module: em.p.module.Name, Issue: fmt.Sprintf("list %s key %q is not a leaf child", li.node.dataPath, key)}
		}
		goName := keyScope.claim(camel(key), "own:"+key)
		ownFields = append(ownFields, ownKeyField{goName: goName, leafName: key, lt: mapLeafType(child.entry), fieldGo: fieldScope.claim(camel(key), child.dataPath)})
	}

	var keyFields []jen.Code
	for _, field := range ancFields {
		keyFields = append(keyFields, jen.Id(field.goName).String())
	}
	for _, field := range ownFields {
		if field.lt.keyString {
			keyFields = append(keyFields, jen.Id(field.goName).String())
		} else {
			keyFields = append(keyFields, jen.Id(field.goName).Add(field.lt.goType()))
		}
	}
	em.addCommented(fmt.Sprintf("%s is %s's row identity (ancestor keys in canonical form).", keyStructName, shapeName), jen.Type().Id(keyStructName).Struct(keyFields...))

	ownKeyAssigns := func(recv func() *jen.Statement) []jen.Code {
		var statements []jen.Code
		for _, field := range ownFields {
			fieldExpr := func() *jen.Statement { return recv().Dot(field.fieldGo) }
			switch {
			case field.lt.keyString:
				statements = append(statements, jen.If(fieldExpr().Clone().Op("!=").Nil()).Block(jen.Id("k").Dot(field.goName).Op("=").Qual(yangPkg, "CanonicalKey").Call(fieldExpr())))
			case field.lt.pointer:
				statements = append(statements, jen.If(fieldExpr().Clone().Op("!=").Nil()).Block(jen.Id("k").Dot(field.goName).Op("=").Op("*").Add(fieldExpr())))
			default:
				statements = append(statements, jen.Id("k").Dot(field.goName).Op("=").Add(fieldExpr()))
			}
		}
		return statements
	}

	descName := em.p.scope.byPath["desc:"+li.node.dataPath]
	if len(li.ancestors) == 0 {
		em.addCommented(fmt.Sprintf("%s is the list descriptor callers hand to a protocol library.", descName), jen.Func().Id(descName).Params().Qual(yangPkg, "ListDescriptor").Index(jen.List(rowType, jen.Id(keyStructName))).Block(
			jen.Return(jen.Qual(yangPkg, "ListDescriptor").Index(jen.List(rowType, jen.Id(keyStructName))).Values(jen.Dict{
				jen.Id("Path"):  em.pathExpr(li.path),
				jen.Id("Codec"): jen.Qual(yangPkg, "StructRowCodec").Call(em.schemaRef(rowOwner, rowOwner.schemaName(li.shapeKey)), jen.Func().Params(jen.Id("r").Op("*").Add(em.typeRef(rowOwner, shapeName))).Id(keyStructName).Block(append([]jen.Code{jen.Var().Id("k").Id(keyStructName)}, append(ownKeyAssigns(func() *jen.Statement { return jen.Id("r") }), jen.Return(jen.Id("k")))...)...)),
			})),
		))
		return nil
	}

	flatName := em.p.scope.byPath["flat:"+li.node.dataPath]
	var flatFields []jen.Code
	for _, field := range ancFields {
		flatFields = append(flatFields, jen.Id(field.goName).String())
	}
	flatFields = append(flatFields, jen.Id("Entry").Add(rowType))
	em.addCommented(fmt.Sprintf("%s flattens one %s entry with its ancestor list keys.", flatName, shapeName), jen.Type().Id(flatName).Struct(flatFields...))

	var chain []jen.Code
	for _, ancestor := range li.ancestors {
		owner := em.plan.packages[ancestor.node.module.Name]
		chain = append(chain, em.schemaRef(owner, owner.schemaName(ancestor.shapeKey)))
	}
	chain = append(chain, em.schemaRef(rowOwner, rowOwner.schemaName(li.shapeKey)))
	chainExpr := jen.Index().Op("*").Qual(yangPkg, "Schema").Values(chain...)
	flatAssigns := jen.Dict{jen.Id("Entry"): jen.Id("e")}
	for _, field := range ancFields {
		flatAssigns[jen.Id(field.goName)] = jen.Qual(yangPkg, "AncestorKey").Call(jen.Id("anc"), jen.Lit(field.level), jen.Lit(field.keyName))
	}
	keyStatements := []jen.Code{jen.Var().Id("k").Id(keyStructName)}
	for _, field := range ancFields {
		keyStatements = append(keyStatements, jen.Id("k").Dot(field.goName).Op("=").Id("r").Dot(field.goName))
	}
	keyStatements = append(keyStatements, ownKeyAssigns(func() *jen.Statement { return jen.Id("r").Dot("Entry") })...)
	keyStatements = append(keyStatements, jen.Return(jen.Id("k")))
	em.addCommented(fmt.Sprintf("%s is the flattened-row descriptor for the nested list %s.", descName, shapeName), jen.Func().Id(descName).Params().Qual(yangPkg, "ListDescriptor").Index(jen.List(jen.Id(flatName), jen.Id(keyStructName))).Block(
		jen.Return(jen.Qual(yangPkg, "ListDescriptor").Index(jen.List(jen.Id(flatName), jen.Id(keyStructName))).Values(jen.Dict{
			jen.Id("Codec"): jen.Qual(yangPkg, "NestedRowCodec").Call(chainExpr,
				jen.Func().Params(jen.Id("anc").Index().Index().Qual(yangPkg, "KeyValue"), jen.Id("e").Add(em.typeRef(rowOwner, shapeName))).Id(flatName).Block(jen.Return(jen.Id(flatName).Values(flatAssigns))),
				jen.Func().Params(jen.Id("r").Op("*").Id(flatName)).Op("*").Add(em.typeRef(rowOwner, shapeName)).Block(jen.Return(jen.Op("&").Id("r").Dot("Entry"))),
				jen.Func().Params(jen.Id("r").Op("*").Id(flatName)).Id(keyStructName).Block(keyStatements...),
			),
			jen.Id("Path"): em.pathExpr(li.path),
		})),
	))
	return nil
}

func (em *moduleEmitter) emitTopContainerDescriptors() {
	slices.SortFunc(em.p.topContainers, func(a, b *topContainerInstance) int { return strings.Compare(a.node.dataPath, b.node.dataPath) })
	for _, container := range em.p.topContainers {
		shape := em.plan.nodeShapes[container.node]
		structName := em.p.structName(shape.key)
		schemaName := em.p.schemaName(shape.key)
		descName := em.p.scope.byPath["desc:"+container.node.dataPath]
		em.addCommented(fmt.Sprintf("%s watches the %s subtree as one synthetic row.", descName, structName), jen.Func().Id(descName).Params().Qual(yangPkg, "ListDescriptor").Index(jen.List(jen.Id(structName), jen.Id("struct{}"))).Block(jen.Return(jen.Qual(yangPkg, "SubtreeDescriptor").Index(jen.Id(structName)).Call(jen.Id(schemaName), em.pathExpr(container.path)))))
	}
}

func (em *moduleEmitter) typeRef(owner *packagePlan, name string) *jen.Statement {
	if owner == em.p {
		return jen.Id(name)
	}
	return jen.Qual(em.plan.importBase+"/"+owner.module.Package, name)
}

func (em *moduleEmitter) schemaRef(owner *packagePlan, name string) *jen.Statement {
	return em.typeRef(owner, name)
}

// pathExpr renders a yang.Path literal using yang.JoinPath and yang.In.
func (em *moduleEmitter) pathExpr(path []pathSeg) *jen.Statement {
	if len(path) == 0 {
		return jen.Qual(yangPkg, "Path").Values()
	}
	type modGroup struct {
		module string
		names  []string
	}
	var groups []modGroup
	for _, segment := range path {
		module := segment.module
		if module == "" {
			module = em.p.module.Name
		}
		if len(groups) == 0 || groups[len(groups)-1].module != module {
			groups = append(groups, modGroup{module: module, names: []string{segment.name}})
		} else {
			groups[len(groups)-1].names = append(groups[len(groups)-1].names, segment.name)
		}
	}
	var calls []jen.Code
	for _, group := range groups {
		args := []jen.Code{jen.Id(moduleVarName(group.module))}
		for _, name := range group.names {
			args = append(args, jen.Lit(name))
		}
		calls = append(calls, jen.Qual(yangPkg, "In").Call(args...))
	}
	return jen.Qual(yangPkg, "JoinPath").Call(calls...)
}

// moduleVarName derives the unexported package-level variable name for a module.
func moduleVarName(mod string) string {
	return "module" + camel(mod)
}

// namespaceOf returns the entry's XML namespace URI.
func namespaceOf(e *goyang.Entry) string {
	if ns := e.Namespace(); ns != nil {
		return ns.Name
	}
	return ""
}

// isDataDir reports whether e is a container or list data node.
func isDataDir(e *goyang.Entry) bool {
	if e.RPC != nil || e.Kind != goyang.DirectoryEntry {
		return false
	}
	if _, isNotification := e.Node.(*goyang.Notification); isNotification {
		return false
	}
	return true
}

// isNonData filters notification, anydata, and anyxml children.
func isNonData(e *goyang.Entry) bool {
	switch e.Kind {
	case goyang.AnyDataEntry, goyang.AnyXMLEntry:
		return true
	}
	_, isNotification := e.Node.(*goyang.Notification)
	return isNotification
}

// isPresence reports whether e is a presence container.
func isPresence(e *goyang.Entry) bool {
	cont, ok := e.Node.(*goyang.Container)
	return ok && cont.Presence != nil
}
