package main

import (
	"fmt"
	"go/format"
	"slices"
	"strings"

	"github.com/dave/jennifer/jen"
	goyang "github.com/openconfig/goyang/pkg/yang"
)

// emit_module.go renders one module's binding package: typed structs
// for containers and lists, one yang.Schema descriptor per struct,
// identity values, composite key structs (ancestor keys included for
// flattened nested lists), and descriptor functions — one
// per list, plus one per top-level container (deeper subtrees compose
// yang.SubtreeDescriptor from the exported schema and a path). Wire
// codecs are the runtime's generic schema-driven implementations, so
// generated code consumes only src/protocol/yang's public API and
// one struct serves all three wire forms.
//
// Two scale rules shaped this emitter (the IOS-XE native module is a
// quarter-million-line package):
//   - descriptors are functions, not vars — a var per descriptor
//     turns package init into one function large enough to break the
//     Go compiler's SSA passes;
//   - output is chunked into multiple files of bounded size, since
//     schema vars are pure static data but a single-file module of
//     hundreds of megabytes is unusable for every tool downstream.

// chunkByteBudget bounds one emitted file's pre-format size.
const chunkByteBudget = 2 << 20

// pathSeg is one ancestry step used for descriptor paths.
type pathSeg struct {
	module    string
	namespace string
	name      string
}

// ancestorList records one enclosing list level for nested-list
// flattening.
type ancestorList struct {
	entryName string   // YANG list name
	shapeKey  string   // shape key of the ancestor list
	keys      []string // key leaf names in YANG order
}

// moduleEmitter carries the per-module emission state. Top-level
// declarations accumulate as fragments that assembleChunks later
// groups into files.
type moduleEmitter struct {
	m             *LoadedModule
	scope         *nameScope
	shapes        []*nodeShape
	listInstances []*listInstance
	topContainers []*topContainerInstance
	memo          map[*goyang.Entry]string
	frags         []string
}

// addCommented renders a doc comment plus declaration as one
// fragment.
func (em *moduleEmitter) addCommented(comment string, code jen.Code) {
	em.frags = append(em.frags, fmt.Sprintf("// %s\n%#v", comment, code))
}

// emitModuleFiles renders the module's binding package as one or more
// chunked files, keyed by filename.
func emitModuleFiles(m *LoadedModule) (map[string][]byte, error) {
	em := &moduleEmitter{m: m}
	scope, shapes, listInstances, topContainers, memo := resolvePackageNaming(m, em.moduleOf)
	em.scope = scope
	em.shapes = shapes
	em.listInstances = listInstances
	em.topContainers = topContainers
	em.memo = memo

	em.emitModuleVars()
	em.emitIdentities()
	em.emitShapes()
	if err := em.emitListArtifacts(); err != nil {
		return nil, err
	}
	em.emitTopContainerDescriptors()

	return em.assembleChunks()
}

// assembleChunks groups fragments into files within the byte budget
// and formats each.
func (em *moduleEmitter) assembleChunks() (map[string][]byte, error) {
	var chunks [][]string
	var cur []string
	size := 0
	for _, frag := range em.frags {
		if size > 0 && size+len(frag) > chunkByteBudget {
			chunks = append(chunks, cur)
			cur, size = nil, 0
		}
		cur = append(cur, frag)
		size += len(frag) + 2
	}
	chunks = append(chunks, cur) // always at least one file, even if empty

	header := fmt.Sprintf(`// Code generated by yanggen. DO NOT EDIT.
// generator: %s
// module: %s revision: %s
// source sha256: %s

`, generatorVersion, em.m.Name, em.m.Revision, em.m.SourceSHA)

	out := make(map[string][]byte, len(chunks))
	for i, chunk := range chunks {
		var b strings.Builder
		b.WriteString(header)
		if i == 0 {
			fmt.Fprintf(&b, "// Package %s binds the YANG module %s.\n", em.m.Package, em.m.Name)
		}
		fmt.Fprintf(&b, "package %s\n\n", em.m.Package)
		body := strings.Join(chunk, "\n\n")
		if strings.Contains(body, "yang.") {
			fmt.Fprintf(&b, "import yang %q\n\n", yangPkg)
		}
		b.WriteString(body)
		b.WriteString("\n")

		src, err := format.Source([]byte(b.String()))
		if err != nil {
			return nil, &LoadError{Vendor: em.m.Vendor, Module: em.m.Name, Issue: fmt.Sprintf("format chunk %d", i), wrapped: err}
		}
		name := em.m.Package + ".go"
		if len(chunks) > 1 {
			name = fmt.Sprintf("%s_p%03d.go", em.m.Package, i)
		}
		out[name] = src
	}
	return out, nil
}

// moduleVarName derives the unexported package-level variable name for a module.
func moduleVarName(mod string) string {
	return "module" + camel(mod)
}

// emitModuleVars renders package-level *yang.Module variables for each
// module referenced by schemas, fields, or descriptor paths.
func (em *moduleEmitter) emitModuleVars() {
	modules := make(map[string]string)
	if em.m.Name != "" {
		modules[em.m.Name] = namespaceOf(em.m.Entry)
	}
	for _, s := range em.shapes {
		if s.module != "" {
			if s.namespace != "" || modules[s.module] == "" {
				modules[s.module] = s.namespace
			}
		}
		for _, c := range dataChildren(s.representative) {
			mod := em.moduleOf(c)
			if mod != "" {
				if ns := namespaceOf(c); ns != "" || modules[mod] == "" {
					modules[mod] = ns
				}
			}
		}
	}
	for _, li := range em.listInstances {
		for _, p := range li.path {
			if p.module != "" {
				if p.namespace != "" || modules[p.module] == "" {
					modules[p.module] = p.namespace
				}
			}
		}
	}
	for _, tc := range em.topContainers {
		for _, p := range tc.path {
			if p.module != "" {
				if p.namespace != "" || modules[p.module] == "" {
					modules[p.module] = p.namespace
				}
			}
		}
	}

	names := make([]string, 0, len(modules))
	for name := range modules {
		names = append(names, name)
	}
	slices.Sort(names)

	for _, name := range names {
		varName := moduleVarName(name)
		ns := modules[name]
		em.addCommented(
			fmt.Sprintf("%s identifies the %s YANG module.", varName, name),
			jen.Var().Id(varName).Op("=").Op("&").Qual(yangPkg, "Module").Values(jen.Dict{
				jen.Id("Name"):      jen.Lit(name),
				jen.Id("Namespace"): jen.Lit(ns),
			}),
		)
	}
}

// emitIdentities renders one yang.Identity value per identity the
// module defines.
func (em *moduleEmitter) emitIdentities() {
	if em.m.Module == nil {
		return
	}
	ids := em.m.Module.Identity
	sorted := make([]string, 0, len(ids))
	for _, id := range ids {
		sorted = append(sorted, id.Name)
	}
	slices.Sort(sorted)
	for _, name := range sorted {
		goName := em.scope.byPath["identity:"+name]
		em.addCommented(
			fmt.Sprintf("%s is the %s identity %q.", goName, em.m.Name, name),
			jen.Var().Id(goName).Op("=").Qual(yangPkg, "Identity").Values(jen.Dict{
				jen.Id("Module"): jen.Lit(em.m.Name),
				jen.Id("Name"):   jen.Lit(name),
			}),
		)
	}
}

// emitShapes renders one struct and one schema var per unique structural shape.
func (em *moduleEmitter) emitShapes() {
	slices.SortFunc(em.shapes, func(a, b *nodeShape) int {
		return strings.Compare(em.structName(a.key), em.structName(b.key))
	})
	for _, s := range em.shapes {
		em.emitShape(s)
	}
}

func (em *moduleEmitter) emitShape(s *nodeShape) {
	structName := em.structName(s.key)
	schemaName := em.schemaVar(s.key)

	var comment string
	if len(s.instances) == 1 {
		comment = fmt.Sprintf("%s is the %s node %s.", structName, s.module, s.instances[0].entry.Path())
	} else {
		comment = fmt.Sprintf("%s is the %s node shape instantiated at %d schema paths, such as %s.",
			structName, s.module, len(s.instances), s.instances[0].entry.Path())
	}

	children := dataChildren(s.representative)
	fieldScope := newNameScope()

	var structFields []jen.Code
	var schemaFields []jen.Code

	for _, c := range children {
		goName := fieldScope.claim(camel(c.Name), c.Path())

		var childSchema string
		var lt leafType
		var ft *jen.Statement
		isList := false
		isLeafList := false

		switch {
		case isDataDir(c):
			childKey := em.memo[c]
			childStruct := em.structName(childKey)
			childSchema = em.schemaVar(childKey)
			if c.IsList() {
				isList = true
				ft = jen.Index().Id(childStruct)
			} else {
				ft = jen.Op("*").Id(childStruct)
			}
			structFields = append(structFields, jen.Id(goName).Add(ft))
		case c.IsLeafList():
			isLeafList = true
			lt = mapLeafType(c)
			structFields = append(structFields, jen.Id(goName).Index().Add(lt.goType()))
		case c.IsLeaf():
			lt = mapLeafType(c)
			ft = lt.goType()
			if lt.pointer {
				ft = jen.Op("*").Add(ft)
			}
			structFields = append(structFields, jen.Id(goName).Add(ft))
		default:
			continue
		}

		var fieldParts []jen.Code
		if childSchema != "" {
			fieldParts = append(fieldParts, jen.Id("Child").Op(":").Id(childSchema))
		}
		fieldParts = append(fieldParts, jen.Id("GoName").Op(":").Lit(goName))
		if isLeafList {
			fieldParts = append(fieldParts, jen.Id("LeafList").Op(":").True())
		}
		if isList {
			fieldParts = append(fieldParts, jen.Id("List").Op(":").True())
		}
		if mod := em.moduleOf(c); mod != "" && mod != em.moduleOf(s.representative) {
			fieldParts = append(fieldParts, jen.Id("Module").Op(":").Id(moduleVarName(mod)))
		}
		fieldParts = append(fieldParts, jen.Id("Name").Op(":").Lit(c.Name))
		if lt.typeExpr != nil {
			fieldParts = append(fieldParts, jen.Id("Type").Op(":").Add(lt.typeExpr()))
		}

		schemaFields = append(schemaFields, jen.Custom(
			jen.Options{Open: "{", Close: "}", Separator: ", ", Multi: false},
			fieldParts...,
		))
	}

	em.addCommented(comment, jen.Type().Id(structName).Struct(structFields...))

	schemaDict := jen.Dict{
		jen.Id("Fields"): jen.Index().Qual(yangPkg, "Field").Custom(
			jen.Options{Open: "{", Close: "}", Separator: ",", Multi: true},
			schemaFields...,
		),
		jen.Id("Module"): jen.Id(moduleVarName(s.module)),
		jen.Id("Name"):   jen.Lit(s.name),
	}
	if s.kind == "list" && s.representative.Key != "" {
		keyLits := make([]jen.Code, 0, 4)
		for _, k := range strings.Fields(s.representative.Key) {
			keyLits = append(keyLits, jen.Lit(k))
		}
		schemaDict[jen.Id("Keys")] = jen.Index().String().Values(keyLits...)
	}
	if s.kind == "presence_container" {
		schemaDict[jen.Id("Presence")] = jen.True()
	}

	em.addCommented(
		fmt.Sprintf("%s describes %s for the generic codecs.", schemaName, structName),
		jen.Var().Id(schemaName).Op("=").Op("&").Qual(yangPkg, "Schema").Values(schemaDict),
	)
}

// emitListArtifacts renders Key, FlatRow, and Descriptor for list instances.
func (em *moduleEmitter) emitListArtifacts() error {
	slices.SortFunc(em.listInstances, func(a, b *listInstance) int {
		return strings.Compare(a.entry.Path(), b.entry.Path())
	})
	for _, li := range em.listInstances {
		if err := em.emitOneList(li); err != nil {
			return err
		}
	}
	return nil
}

func (em *moduleEmitter) emitOneList(li *listInstance) error {
	e := li.entry
	keyNames := strings.Fields(e.Key)
	if len(keyNames) == 0 {
		return nil
	}

	structName := em.structName(li.shapeKey)
	keyStructName := em.listKey(e.Path())
	keyScope := newNameScope()

	type ancKeyField struct {
		goName  string
		level   int
		keyName string
	}
	type ownKeyField struct {
		goName, leafName string
		lt               leafType
		fieldGo          string
	}
	var ancFields []ancKeyField
	var ownFields []ownKeyField

	for i, a := range li.ancestors {
		for _, k := range a.keys {
			goName := keyScope.claim(camel(a.entryName)+camel(k), fmt.Sprintf("anc:%d:%s:%s", i, a.entryName, k))
			ancFields = append(ancFields, ancKeyField{goName: goName, level: i, keyName: k})
		}
	}

	fieldScope := newNameScope()
	for _, c := range dataChildren(e) {
		fieldScope.claim(camel(c.Name), c.Path())
	}

	for _, k := range keyNames {
		child := e.Dir[k]
		if child == nil || !child.IsLeaf() {
			return &LoadError{
				Vendor: em.m.Vendor, Module: em.m.Name,
				Issue: fmt.Sprintf("list %s key %q is not a leaf child", e.Path(), k),
			}
		}
		goName := keyScope.claim(camel(k), "own:"+k)
		ownFields = append(ownFields, ownKeyField{
			goName: goName, leafName: k,
			lt:      mapLeafType(child),
			fieldGo: fieldScope.claim(camel(k), child.Path()),
		})
	}

	keyFields := make([]jen.Code, 0, len(ancFields)+len(ownFields))
	for _, af := range ancFields {
		keyFields = append(keyFields, jen.Id(af.goName).String())
	}
	for _, of := range ownFields {
		if of.lt.keyString {
			keyFields = append(keyFields, jen.Id(of.goName).String())
			continue
		}
		keyFields = append(keyFields, jen.Id(of.goName).Add(of.lt.goType()))
	}
	em.addCommented(
		fmt.Sprintf("%s is %s's row identity (ancestor keys in canonical form).", keyStructName, structName),
		jen.Type().Id(keyStructName).Struct(keyFields...),
	)

	ownKeyAssigns := func(recv func() *jen.Statement) []jen.Code {
		stmts := make([]jen.Code, 0, len(ownFields))
		for _, of := range ownFields {
			field := func() *jen.Statement { return recv().Dot(of.fieldGo) }
			switch {
			case of.lt.keyString:
				stmts = append(stmts, jen.If(field().Clone().Op("!=").Nil()).Block(
					jen.Id("k").Dot(of.goName).Op("=").Qual(yangPkg, "CanonicalKey").Call(field()),
				))
			case of.lt.pointer:
				stmts = append(stmts, jen.If(field().Clone().Op("!=").Nil()).Block(
					jen.Id("k").Dot(of.goName).Op("=").Op("*").Add(field()),
				))
			default:
				stmts = append(stmts, jen.Id("k").Dot(of.goName).Op("=").Add(field()))
			}
		}
		return stmts
	}

	descName := em.listDescriptor(e.Path())

	if len(li.ancestors) == 0 {
		em.addCommented(
			fmt.Sprintf("%s is the list descriptor callers hand to a protocol library.", descName),
			jen.Func().Id(descName).Params().Qual(yangPkg, "ListDescriptor").Index(jen.List(jen.Id(structName), jen.Id(keyStructName))).Block(
				jen.Return(jen.Qual(yangPkg, "ListDescriptor").Index(jen.List(jen.Id(structName), jen.Id(keyStructName))).Values(jen.Dict{
					jen.Id("Path"): em.pathExpr(li.path),
					jen.Id("Codec"): jen.Qual(yangPkg, "StructRowCodec").Call(
						jen.Id(em.schemaVar(li.shapeKey)),
						jen.Func().Params(jen.Id("r").Op("*").Id(structName)).Id(keyStructName).Block(
							append([]jen.Code{jen.Var().Id("k").Id(keyStructName)},
								append(ownKeyAssigns(func() *jen.Statement { return jen.Id("r") }),
									jen.Return(jen.Id("k")))...)...,
						),
					),
				})),
			),
		)
		return nil
	}

	// Nested list: flat-row wrapper carrying ancestor keys.
	flatName := em.listFlatRow(e.Path())
	flatFields := make([]jen.Code, 0, len(ancFields)+1)
	for _, af := range ancFields {
		flatFields = append(flatFields, jen.Id(af.goName).String())
	}
	flatFields = append(flatFields, jen.Id("Entry").Id(structName))
	em.addCommented(
		fmt.Sprintf("%s flattens one %s entry with its ancestor list keys.", flatName, structName),
		jen.Type().Id(flatName).Struct(flatFields...),
	)

	chainExpr := func() *jen.Statement {
		chainElems := make([]jen.Code, 0, len(li.ancestors)+1)
		for _, a := range li.ancestors {
			chainElems = append(chainElems, jen.Id(em.schemaVar(a.shapeKey)))
		}
		chainElems = append(chainElems, jen.Id(em.schemaVar(li.shapeKey)))
		return jen.Index().Op("*").Qual(yangPkg, "Schema").Values(chainElems...)
	}

	flatAssigns := jen.Dict{jen.Id("Entry"): jen.Id("e")}
	for _, af := range ancFields {
		flatAssigns[jen.Id(af.goName)] = jen.Qual(yangPkg, "AncestorKey").Call(
			jen.Id("anc"), jen.Lit(af.level), jen.Lit(af.keyName))
	}

	keyFnStmts := []jen.Code{jen.Var().Id("k").Id(keyStructName)}
	for _, af := range ancFields {
		keyFnStmts = append(keyFnStmts, jen.Id("k").Dot(af.goName).Op("=").Id("r").Dot(af.goName))
	}
	keyFnStmts = append(keyFnStmts, ownKeyAssigns(func() *jen.Statement { return jen.Id("r").Dot("Entry") })...)
	keyFnStmts = append(keyFnStmts, jen.Return(jen.Id("k")))

	em.addCommented(
		fmt.Sprintf("%s is the flattened-row descriptor for the nested list %s.", descName, structName),
		jen.Func().Id(descName).Params().Qual(yangPkg, "ListDescriptor").Index(jen.List(jen.Id(flatName), jen.Id(keyStructName))).Block(
			jen.Return(jen.Qual(yangPkg, "ListDescriptor").Index(jen.List(jen.Id(flatName), jen.Id(keyStructName))).Values(jen.Dict{
				jen.Id("Codec"): jen.Qual(yangPkg, "NestedRowCodec").Call(
					chainExpr(),
					jen.Func().Params(
						jen.Id("anc").Index().Index().Qual(yangPkg, "KeyValue"),
						jen.Id("e").Id(structName),
					).Id(flatName).Block(
						jen.Return(jen.Id(flatName).Values(flatAssigns)),
					),
					jen.Func().Params(
						jen.Id("r").Op("*").Id(flatName),
					).Op("*").Id(structName).Block(
						jen.Return(jen.Op("&").Id("r").Dot("Entry")),
					),
					jen.Func().Params(
						jen.Id("r").Op("*").Id(flatName),
					).Id(keyStructName).Block(keyFnStmts...),
				),
				jen.Id("Path"): em.pathExpr(li.path),
			})),
		),
	)
	return nil
}

// emitTopContainerDescriptors renders synthetic-row descriptors for top-level containers.
func (em *moduleEmitter) emitTopContainerDescriptors() {
	slices.SortFunc(em.topContainers, func(a, b *topContainerInstance) int {
		return strings.Compare(a.entry.Path(), b.entry.Path())
	})
	for _, tc := range em.topContainers {
		structName := em.structName(tc.shapeKey)
		schemaName := em.schemaVar(tc.shapeKey)
		descName := em.containerDescriptor(tc.entry.Path())
		em.addCommented(
			fmt.Sprintf("%s watches the %s subtree as one synthetic row.", descName, structName),
			jen.Func().Id(descName).Params().Qual(yangPkg, "ListDescriptor").Index(jen.List(jen.Id(structName), jen.Id("struct{}"))).Block(
				jen.Return(jen.Qual(yangPkg, "SubtreeDescriptor").Index(jen.Id(structName)).Call(
					jen.Id(schemaName),
					em.pathExpr(tc.path),
				)),
			),
		)
	}
}

func (em *moduleEmitter) structName(shapeKey string) string {
	return em.scope.byPath[shapeKey]
}

func (em *moduleEmitter) schemaVar(shapeKey string) string {
	return em.scope.byPath["schema:"+shapeKey]
}

func (em *moduleEmitter) listKey(path string) string {
	return em.scope.byPath["key:"+path]
}

func (em *moduleEmitter) listDescriptor(path string) string {
	return em.scope.byPath["desc:"+path]
}

func (em *moduleEmitter) listFlatRow(path string) string {
	return em.scope.byPath["flat:"+path]
}

func (em *moduleEmitter) containerDescriptor(path string) string {
	return em.scope.byPath["desc:"+path]
}

// pathExpr renders a yang.Path literal using yang.JoinPath and yang.In.
func (em *moduleEmitter) pathExpr(path []pathSeg) *jen.Statement {
	if len(path) == 0 {
		return jen.Qual(yangPkg, "Path").Values()
	}
	type modGroup struct {
		module string
		names  []string
	}
	var groups []modGroup
	for _, s := range path {
		mod := s.module
		if mod == "" {
			mod = em.m.Name
		}
		if len(groups) == 0 || groups[len(groups)-1].module != mod {
			groups = append(groups, modGroup{module: mod, names: []string{s.name}})
		} else {
			groups[len(groups)-1].names = append(groups[len(groups)-1].names, s.name)
		}
	}
	var inCalls []jen.Code
	for _, g := range groups {
		args := []jen.Code{jen.Id(moduleVarName(g.module))}
		for _, name := range g.names {
			args = append(args, jen.Lit(name))
		}
		inCalls = append(inCalls, jen.Qual(yangPkg, "In").Call(args...))
	}
	return jen.Qual(yangPkg, "JoinPath").Call(inCalls...)
}

// moduleOf returns the instantiating module's name for an entry.
func (em *moduleEmitter) moduleOf(e *goyang.Entry) string {
	if e != nil {
		if mod, err := e.InstantiatingModule(); err == nil && mod != "" {
			return mod
		}
	}
	return em.m.Name
}

// namespaceOf returns the entry's XML namespace URI.
func namespaceOf(e *goyang.Entry) string {
	if ns := e.Namespace(); ns != nil {
		return ns.Name
	}
	return ""
}

// isDataDir reports whether e is a container or list data node.
func isDataDir(e *goyang.Entry) bool {
	if e.RPC != nil || e.Kind != goyang.DirectoryEntry {
		return false
	}
	if _, isNotification := e.Node.(*goyang.Notification); isNotification {
		return false
	}
	return true
}

// dataChildren returns e's data children sorted by name, with
// choice/case layers flattened away.
func dataChildren(e *goyang.Entry) []*goyang.Entry {
	var out []*goyang.Entry
	var collect func(dir map[string]*goyang.Entry)
	collect = func(dir map[string]*goyang.Entry) {
		for _, name := range sortedKeys(dir) {
			c := dir[name]
			switch {
			case c.IsChoice() || c.IsCase():
				collect(c.Dir)
			case c.RPC != nil, isNonData(c):
			default:
				out = append(out, c)
			}
		}
	}
	collect(e.Dir)
	slices.SortFunc(out, func(a, b *goyang.Entry) int { return strings.Compare(a.Name, b.Name) })
	return out
}

// isNonData filters notification/anydata/anyxml children.
func isNonData(e *goyang.Entry) bool {
	switch e.Kind {
	case goyang.AnyDataEntry, goyang.AnyXMLEntry:
		return true
	}
	_, isNotification := e.Node.(*goyang.Notification)
	return isNotification
}

// isPresence reports whether e is a presence container.
func isPresence(e *goyang.Entry) bool {
	cont, ok := e.Node.(*goyang.Container)
	return ok && cont.Presence != nil
}
