package main

import (
	"flag"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// updateGolden refreshes the committed goldens under testdata/golden/.
// Run with
//
//	go test ./src/protocol/yang/cmd/yanggen -run TestEmitFixtureGolden -update-golden
//
// after intentional emitter changes and audit the diff.
var updateGolden = flag.Bool("update-golden", false, "rewrite testdata/golden/* with the current emitter output")

// TestEmitFixtureGolden renders every fixture module and compares
// byte-for-byte against the committed goldens.
func TestEmitFixtureGolden(t *testing.T) {
	vs := fixtureVendor(t)
	for _, m := range vs.Modules {
		got, err := emitOne(m)
		if err != nil {
			t.Fatalf("emit %s: %v", m.Name, err)
		}
		goldenPath := filepath.Join("testdata", "golden", "fixture", m.Package, m.Package+".go")
		if *updateGolden {
			if err := os.MkdirAll(filepath.Dir(goldenPath), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(goldenPath, []byte(got), 0o644); err != nil {
				t.Fatal(err)
			}
			t.Logf("updated %s (%d bytes)", goldenPath, len(got))
			continue
		}
		want, err := os.ReadFile(goldenPath)
		if err != nil {
			t.Fatalf("read golden for %s (rerun with -update-golden if first time): %v", m.Name, err)
		}
		if string(want) != got {
			candidate := goldenPath + ".got"
			_ = os.WriteFile(candidate, []byte(got), 0o644)
			t.Errorf("golden mismatch for %s; candidate written to %s — rerun with -update-golden after auditing", m.Name, candidate)
		}
	}
}

// TestEmitFixtureParses ensures each emitted file is syntactically
// valid Go even when goldens are stale.
func TestEmitFixtureParses(t *testing.T) {
	vs := fixtureVendor(t)
	for _, m := range vs.Modules {
		got, err := emitOne(m)
		if err != nil {
			t.Fatalf("emit %s: %v", m.Name, err)
		}
		fset := token.NewFileSet()
		if _, err := parser.ParseFile(fset, m.Package+".go", got, parser.AllErrors); err != nil {
			t.Fatalf("emitted %s does not parse: %v\n--- src ---\n%s", m.Name, err, got)
		}
	}
}

// TestEmitFixtureSurface pins the load-bearing emitted symbols
// without demanding byte-exactness: the golden test owns that.
func TestEmitFixtureSurface(t *testing.T) {
	vs := fixtureVendor(t)
	main := moduleByName(t, vs, "fixture-main")
	src, err := emitOne(main)
	if err != nil {
		t.Fatal(err)
	}

	wantRE := []string{
		`Listen\s+\*yang\.Value`,
		`Proto\s+\*yang\.Identity`,
		`Ratio\s+\*yang\.Value`,
		`ServerRef\s+\*string`,
		`ServerName\s+string`,
		`Presence:\s+true`,
	}
	want := []string{
		"Code generated by yanggen. DO NOT EDIT.",
		"module: fixture-main revision: 2026-01-02",
		// Structs, schemas, and descriptors.
		"type Servers struct",
		"type ServersServer struct",
		"var ServersServerSchemaX4d76e3 =",
		"type ServersServerKey struct",
		"func ServersServerDescriptor() yang.ListDescriptor",
		// Nested list: flat row with the ancestor key, schema chain,
		// nested decode.
		"type ServersServerEndpoint struct",
		"type ServersServerEndpointFlatRow struct",
		"yang.DecodeXMLNested[ServersServerEndpoint]",
		"yang.DecodeJSONNested[ServersServerEndpoint]",
		// Deviation applied: the deviated leaf is gone (asserted via
		// notWant below); presence, unions, identityref, and the
		// leafref key are asserted by wantRE above.
		// Synthetic-row descriptor for a container.
		"func ServersDescriptor() yang.ListDescriptor",
		"yang.SubtreeDescriptor[Servers]",
		// Name collision resolved deterministically with a hash
		// suffix, not silently merged.
		"type AlarmState",
		"type AlarmStateX",
	}
	notWant := []string{
		"LegacyFlag", // removed by fixture-dev's deviate not-supported
	}
	for _, w := range want {
		if !strings.Contains(src, w) {
			t.Errorf("emitted fixture-main missing %q", w)
		}
	}
	for _, pat := range wantRE {
		if !regexp.MustCompile(pat).MatchString(src) {
			t.Errorf("emitted fixture-main missing pattern %q", pat)
		}
	}
	for _, w := range notWant {
		if strings.Contains(src, w) {
			t.Errorf("emitted fixture-main unexpectedly contains %q", w)
		}
	}
	if t.Failed() {
		t.Logf("--- src ---\n%s", src)
	}
}

// TestEmitAugmentModule asserts the augmenting module's own emission
// and that its augmented-in nodes live in the target module's package
// with foreign-module qualification.
func TestEmitAugmentModule(t *testing.T) {
	vs := fixtureVendor(t)
	mainSrc, err := emitOne(moduleByName(t, vs, "fixture-main"))
	if err != nil {
		t.Fatal(err)
	}
	if !regexp.MustCompile(`Module:\s+"fixture-aug"`).MatchString(mainSrc) {
		t.Error("augmented-in owner leaf lost its defining-module qualification")
	}
	if !regexp.MustCompile(`Owner\s+\*string`).MatchString(mainSrc) {
		t.Error("augmented-in owner leaf missing from the target struct")
	}

	typesSrc, err := emitOne(moduleByName(t, vs, "fixture-types"))
	if err != nil {
		t.Fatal(err)
	}
	for _, w := range []string{"IdentityTCP", "IdentityUDP", "IdentityProtocol"} {
		if !strings.Contains(typesSrc, w) {
			t.Errorf("fixture-types missing identity value %s", w)
		}
	}
}

// TestEmitGroupingInstantiatingModule asserts that nodes instantiated from
// a grouping in another module take the instantiating module's name.
func TestEmitGroupingInstantiatingModule(t *testing.T) {
	vs := fixtureVendor(t)
	mainSrc, err := emitOne(moduleByName(t, vs, "fixture-main"))
	if err != nil {
		t.Fatal(err)
	}

	if strings.Contains(mainSrc, `"fixture-grp"`) {
		t.Error("emitted fixture-main unexpectedly contains defining module fixture-grp")
	}

	// Each instance's schema/field literal names fixture-main.
	for _, schema := range []string{"PrimaryGroupItemSchema", "SecondaryGroupItemSchema"} {
		pat := schema + `\s*=\s*&yang\.Schema\{[\s\S]*?Module:\s+(?:"fixture-main"|moduleFixtureMain)`
		if !regexp.MustCompile(pat).MatchString(mainSrc) {
			t.Errorf("emitted fixture-main missing fixture-main Module on %s", schema)
		}
	}
}

// TestGoldenPackagesBuild compiles the committed golden packages, so
// the emitted code is known to type-check against the runtime — the
// go tool skips testdata in wildcard walks, so each package is built
// by explicit path.
func TestGoldenPackagesBuild(t *testing.T) {
	if testing.Short() {
		t.Skip("compilation exec test skipped in -short mode")
	}
	entries, err := os.ReadDir(filepath.Join("testdata", "golden", "fixture"))
	if err != nil {
		t.Skipf("no goldens yet: %v", err)
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		dir := "./" + filepath.Join("testdata", "golden", "fixture", e.Name())
		cmd := exec.Command("go", "build", dir)
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Errorf("go build %s: %v\n%s", dir, err, out)
		}
	}
}

// TestEmitNoUnderscores parses the golden fixture output with go/parser and
// walks every declaration, asserting: no identifier or struct field contains '_',
// Servers_Server is now ServersServer, and companion/child clash resolution holds,
// including a sibling struct (server-schema) whose name equals a list's schema var.
func TestEmitNoUnderscores(t *testing.T) {
	goldenRoot := filepath.Join("testdata", "golden", "fixture")
	entries, err := os.ReadDir(goldenRoot)
	if err != nil {
		t.Fatalf("read golden dir: %v", err)
	}

	foundServersServer := false
	foundServersSchema := false
	foundServersServerKey := false
	foundSchemaChildClash := false
	foundKeyChildClash := false
	foundSiblingStruct := false
	foundSchemaSiblingClash := false

	schemaChildRE := regexp.MustCompile(`^ServersSchemaX[0-9a-f]{6}$`)
	keyChildRE := regexp.MustCompile(`^ServersServerKeyX[0-9a-f]{6}$`)
	schemaSiblingRE := regexp.MustCompile(`^ServersServerSchemaX[0-9a-f]{6}$`)

	fset := token.NewFileSet()
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		pkgDir := filepath.Join(goldenRoot, e.Name())
		files, err := os.ReadDir(pkgDir)
		if err != nil {
			t.Fatalf("read %s: %v", pkgDir, err)
		}
		for _, f := range files {
			if f.IsDir() || !strings.HasSuffix(f.Name(), ".go") {
				continue
			}
			filePath := filepath.Join(pkgDir, f.Name())
			file, err := parser.ParseFile(fset, filePath, nil, 0)
			if err != nil {
				t.Fatalf("parse %s: %v", filePath, err)
			}
			for _, decl := range file.Decls {
				switch d := decl.(type) {
				case *ast.GenDecl:
					for _, spec := range d.Specs {
						switch s := spec.(type) {
						case *ast.TypeSpec:
							name := s.Name.Name
							if strings.Contains(name, "_") {
								t.Errorf("%s: type %q contains underscore", f.Name(), name)
							}
							if name == "ServersServer" {
								foundServersServer = true
							}
							if schemaChildRE.MatchString(name) {
								foundSchemaChildClash = true
							}
							if keyChildRE.MatchString(name) {
								foundKeyChildClash = true
							}
							if name == "ServersServerKey" {
								foundServersServerKey = true
							}
							if name == "ServersServerSchema" {
								foundSiblingStruct = true
							}
							if st, ok := s.Type.(*ast.StructType); ok {
								for _, field := range st.Fields.List {
									for _, id := range field.Names {
										if strings.Contains(id.Name, "_") {
											t.Errorf("%s: struct %s field %q contains underscore", f.Name(), name, id.Name)
										}
									}
								}
							}
						case *ast.ValueSpec:
							for _, id := range s.Names {
								name := id.Name
								if strings.Contains(name, "_") {
									t.Errorf("%s: var/const %q contains underscore", f.Name(), name)
								}
								if name == "ServersSchema" {
									foundServersSchema = true
								}
								if schemaSiblingRE.MatchString(name) {
									foundSchemaSiblingClash = true
								}
								if name == "ServersServerSchema" {
									t.Errorf("%s: var %q takes the sibling struct's name", f.Name(), name)
								}
							}
						}
					}
				case *ast.FuncDecl:
					name := d.Name.Name
					if strings.Contains(name, "_") {
						t.Errorf("%s: func %q contains underscore", f.Name(), name)
					}
				}
			}
		}
	}

	if !foundServersServer {
		t.Error("type ServersServer not found in golden fixtures")
	}
	if !foundServersSchema {
		t.Error("var ServersSchema companion not found in golden fixtures")
	}
	if !foundServersServerKey {
		t.Error("type ServersServerKey companion not found in golden fixtures")
	}
	if !foundSchemaChildClash {
		t.Error("child container ServersSchemaX<hex> not found in golden fixtures")
	}
	if !foundKeyChildClash {
		t.Error("child container ServersServerKeyX<hex> not found in golden fixtures")
	}
	if !foundSiblingStruct {
		t.Error("sibling container type ServersServerSchema not found in golden fixtures")
	}
	if !foundSchemaSiblingClash {
		t.Error("list schema var ServersServerSchemaX<hex> not found in golden fixtures")
	}
}
