package main

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"strings"

	"golang.org/x/mod/modfile"

	"go.aledante.io/FlowSeer/src/common/errs"
)

// rootModulePath is the module the generated packages import
// src/protocol/yang from.
const rootModulePath = "go.aledante.io/FlowSeer"

// rootPlaceholderVersion is the version the output module requires the
// root module at. The replace directive resolves it to the checkout, so
// the version itself names nothing; it is the one `go mod tidy` writes
// for a replaced module without a real version.
const rootPlaceholderVersion = "v0.0.0-00010101000000-000000000000"

// goModName is the output module's go.mod basename.
const goModName = "go.mod"

// outputModule describes the module yanggen writes around its output
// directory. The output is a module of its own so the root module's
// `./...` stops at it and a build compiles only the binding packages it
// imports.
type outputModule struct {
	// Path is the output directory's module path. It keeps the root
	// module's prefix, so import paths match what they would be inside
	// the root module.
	Path string
	// GoVersion is the root module's go directive.
	GoVersion string
	// RootRel is the slash-separated path from the output directory to
	// the root module's directory.
	RootRel string
}

// resolveOutputModule finds the root module in an ancestor of outDir
// and derives the output module from it.
func resolveOutputModule(outDir string) (outputModule, error) {
	abs, err := filepath.Abs(outDir)
	if err != nil {
		return outputModule{}, errs.Wrapf(err, "resolve output directory %s", outDir)
	}
	for dir := filepath.Dir(abs); ; dir = filepath.Dir(dir) {
		file := filepath.Join(dir, goModName)
		data, err := os.ReadFile(file)
		switch {
		case err == nil:
			f, err := modfile.ParseLax(file, data, nil)
			if err != nil {
				return outputModule{}, errs.Wrapf(err, "parse %s", file)
			}
			if f.Module == nil || f.Module.Mod.Path != rootModulePath || f.Go == nil {
				break
			}
			rel, err := filepath.Rel(dir, abs)
			if err != nil {
				return outputModule{}, errs.Wrapf(err, "relate %s to %s", abs, dir)
			}
			rootRel, err := filepath.Rel(abs, dir)
			if err != nil {
				return outputModule{}, errs.Wrapf(err, "relate %s to %s", dir, abs)
			}
			return outputModule{
				Path:      path.Join(rootModulePath, filepath.ToSlash(rel)),
				GoVersion: f.Go.Version,
				RootRel:   filepath.ToSlash(rootRel),
			}, nil
		case !errors.Is(err, os.ErrNotExist):
			return outputModule{}, errs.Wrapf(err, "read %s", file)
		}
		if filepath.Dir(dir) == dir {
			return outputModule{}, errs.New().Msgf("no %s module above %s", rootModulePath, abs)
		}
	}
}

// render returns the go.mod yanggen writes before `go mod tidy` adds
// the indirect requirements and the require block layout.
func (m outputModule) render() []byte {
	var b strings.Builder
	b.WriteString("// Code generated by yanggen. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// The YANG bindings are a module of their own so the root module's\n")
	b.WriteString("// `go build ./...` and `go vet ./...` do not compile all of them. A\n")
	b.WriteString("// root package that imports a binding package compiles only that one.\n")
	fmt.Fprintf(&b, "module %s\n\n", m.Path)
	fmt.Fprintf(&b, "go %s\n\n", m.GoVersion)
	fmt.Fprintf(&b, "require %s %s\n\n", rootModulePath, rootPlaceholderVersion)
	fmt.Fprintf(&b, "replace %s => %s\n", rootModulePath, m.RootRel)
	return []byte(b.String())
}

// writeGoMod writes the output module's go.mod under outDir and runs
// `go mod tidy` there, which adds the indirect requirements and writes
// go.sum.
func writeGoMod(outDir string) error {
	m, err := resolveOutputModule(outDir)
	if err != nil {
		return err
	}
	file := filepath.Join(outDir, goModName)
	if err := os.WriteFile(file, m.render(), 0o644); err != nil {
		return errs.Wrapf(err, "write %s", file)
	}
	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = outDir
	if out, err := cmd.CombinedOutput(); err != nil {
		return errs.Wrapf(err, "go mod tidy in %s: %s", outDir, strings.TrimSpace(string(out)))
	}
	return nil
}

// checkGoMod reports how the committed go.mod under outDir differs from
// the statements yanggen owns: the module path, the go directive, and
// the root module's require and replace. The indirect requirements are
// `go mod tidy`'s and are not compared.
func checkGoMod(outDir string) ([]string, error) {
	m, err := resolveOutputModule(outDir)
	if err != nil {
		return nil, err
	}
	file := filepath.Join(outDir, goModName)
	data, err := os.ReadFile(file)
	if errors.Is(err, os.ErrNotExist) {
		return []string{"go.mod is missing"}, nil
	}
	if err != nil {
		return nil, errs.Wrapf(err, "read %s", file)
	}
	f, err := modfile.Parse(file, data, nil)
	if err != nil {
		return []string{fmt.Sprintf("go.mod does not parse: %v", err)}, nil
	}

	var drift []string
	if f.Module == nil || f.Module.Mod.Path != m.Path {
		drift = append(drift, fmt.Sprintf("module path is not %s", m.Path))
	}
	if f.Go == nil || f.Go.Version != m.GoVersion {
		drift = append(drift, fmt.Sprintf("go directive is not %s", m.GoVersion))
	}
	required := false
	for _, r := range f.Require {
		if r.Mod.Path == rootModulePath && r.Mod.Version == rootPlaceholderVersion {
			required = true
		}
	}
	if !required {
		drift = append(drift, fmt.Sprintf("no require %s %s", rootModulePath, rootPlaceholderVersion))
	}
	replaced := false
	for _, r := range f.Replace {
		if r.Old.Path == rootModulePath && r.Old.Version == "" && r.New.Path == m.RootRel && r.New.Version == "" {
			replaced = true
		}
	}
	if !replaced {
		drift = append(drift, fmt.Sprintf("no replace %s => %s", rootModulePath, m.RootRel))
	}
	return drift, nil
}
