// Code generated by mibgen; DO NOT EDIT.
//
// Source MIB:    FAKE-MIB
// Source path:   testdata/mibs/FAKE-MIB.mib
// Source SHA-256: d7a61033db860789a6a9f9d77b049561dd46eb130a03a7186a75ed43c3cf6f49
//
// Regenerate with `go generate ./...` or `go tool mibgen`.

package fakemib

import (
	"bytes"
	"context"
	"fmt"
	"iter"
	"net"

	snmp "go.aledante.io/FlowSeer/src/common/snmp"
	ae "go.aledante.io/ae"
)

// FakeStatusValue is the SMI enum fakeStatus (inline).
// An enum-typed scalar.
type FakeStatusValue int32

const (
	FakeStatusValueUp      FakeStatusValue = 1
	FakeStatusValueDown    FakeStatusValue = 2
	FakeStatusValueTesting FakeStatusValue = 3
)

func (v FakeStatusValue) String() string {
	switch v {
	case FakeStatusValueUp:
		return "up"
	case FakeStatusValueDown:
		return "down"
	case FakeStatusValueTesting:
		return "testing"
	}

	return fmt.Sprintf("FakeStatusValue(%d)", v)
}

// FakeScalarGet reads the SMIv2 scalar fakeScalar.
// A simple scalar.
func FakeScalarGet(ctx context.Context, sess snmp.Session) (int32, error) {
	vbs, err := sess.Get(ctx, []snmp.OID{snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 1, 0)})
	if err != nil {
		return 0, err
	}

	if len(vbs) == 0 {
		return 0, ae.Msg("empty Get response for fakeScalar")
	}

	return func(vb snmp.VarBind) (int32, error) {
		return snmp.DecodeInt32(vb)
	}(vbs[0])
}

// FakeStatusGet reads the SMIv2 scalar fakeStatus.
// An enum-typed scalar.
func FakeStatusGet(ctx context.Context, sess snmp.Session) (FakeStatusValue, error) {
	vbs, err := sess.Get(ctx, []snmp.OID{snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 2, 0)})
	if err != nil {
		return FakeStatusValue(0), err
	}

	if len(vbs) == 0 {
		return FakeStatusValue(0), ae.Msg("empty Get response for fakeStatus")
	}

	return func(vb snmp.VarBind) (FakeStatusValue, error) {
		v, err := snmp.DecodeInt32(vb)
		if err != nil {
			return FakeStatusValue(0), err
		}
		return FakeStatusValue(v), nil
	}(vbs[0])
}

// FakeName is the column fakeName of table fakeTable.
// Name.
var FakeName = snmp.NewColumn[string](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 2), snmp.KindOctetString, func(vb snmp.VarBind) (string, error) {
	return snmp.DecodeDisplayString(vb)
})

// FakeMac is the column fakeMac of table fakeTable.
// MAC address.
var FakeMac = snmp.NewColumn[net.HardwareAddr](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 3), snmp.KindOctetString, func(vb snmp.VarBind) (net.HardwareAddr, error) {
	return snmp.DecodeMacAddress(vb)
})

// FakeOctets is the column fakeOctets of table fakeTable.
// Counter.
var FakeOctets = snmp.NewColumn[uint64](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 4), snmp.KindCounter64, func(vb snmp.VarBind) (uint64, error) {
	return snmp.DecodeUint64(vb)
})

// FakeLastChange is the column fakeLastChange of table fakeTable.
// Per-row change indicator. The name-suffix heuristic classifies this
// column as TierIndicator at codegen time and structural discovery binds
// it to fakeTable.
var FakeLastChange = snmp.NewColumn[uint32](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 5), snmp.KindTimeTicks, func(vb snmp.VarBind) (uint32, error) {
	return snmp.DecodeUint32(vb)
})

// FakeTableRow is one row of fakeTable. Index carries the OID
// suffix beyond the table-entry prefix; the remaining fields are
// populated only for columns the caller passed to Walk().
type FakeTableRow struct {
	Index          snmp.OID
	FakeName       string
	FakeMac        net.HardwareAddr
	FakeOctets     uint64
	FakeLastChange uint32
}

// FakeTableWalker is a table-aware walker over fakeTable.
// Construct via FakeTable.Walk(ctx, sess, cols...).
type FakeTableWalker struct {
	rw    *snmp.RawWalker
	cols  []snmp.AnyColumn
	byCol map[uint32]snmp.AnyColumn
}

// Iter yields one (Index, Row) pair per row of the table walk. The
// full BulkWalk is buffered before any row is yielded, so the
// generated walker is correct over both column-major and row-major
// agent emission. Contracts:
//
//  1. Ordering: rows yield in the index's first-appearance position
//     in the agent's BulkWalk response — which for a well-behaved
//     agent equals lexicographic OID order over the index suffix.
//     This is NOT numerical order for composite-index tables
//     (e.g. ipAddrTable indexed by IP-as-OID: 192.168.0.10 sorts
//     before 192.168.0.2). Integer-keyed tables (ifTable,
//     hrProcessorTable) get numeric order for free.
//
//  2. Row presence: every index observed under the entry prefix
//     yields a row, even when only unrequested columns landed on
//     that index. The row's requested-column fields stay at zero.
//
//  3. Decode error: rows for indexes strictly before the failing
//     index in appearance order flush before Walker.Fail is set,
//     preserving partial-progress visibility for the operator.
//     The failing row and anything after it are not yielded.
//     Check Err() afterwards for the terminal cause.
//
//  4. Memory profile: O(rows × requested columns) buffered before
//     the first yield. Bounded by table size, not walk position —
//     callers that broke out early via 'for row := range Iter()'
//     still pay the full-walk buffer cost.
func (tw *FakeTableWalker) Iter() iter.Seq2[snmp.OID, FakeTableRow] {
	return func(yield func(snmp.OID, FakeTableRow) bool) {
		entryWire := snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1).WireBytes()
		buffer := make(map[string]*FakeTableRow)
		var orderIdx []snmp.OID
		var orderKey []string

		for rv := range tw.rw.Iter() {
			if !bytes.HasPrefix(rv.OID, entryWire) {
				continue
			}
			suffix := rv.OID[len(entryWire):]
			colID, colLen, okArc := snmp.RawFirstArc(suffix)
			if !okArc || colLen >= len(suffix) {
				continue
			}
			idxWire := suffix[colLen:]
			row, exists := buffer[string(idxWire)]
			if !exists {
				idx, idxErr := snmp.DecodeIndexArcs(idxWire)
				if idxErr != nil {
					continue
				}
				key := string(idxWire)
				row = &FakeTableRow{}
				buffer[key] = row
				orderIdx = append(orderIdx, idx)
				orderKey = append(orderKey, key)
			}
			_, ok := tw.byCol[colID]
			if !ok {
				continue
			}
			var derr error
			switch colID {
			case 2:
				vb, vbErr := rv.Decode()
				if vbErr != nil {
					derr = vbErr
				} else {
					dv, dErr := FakeName.Decode(vb)
					if dErr != nil {
						derr = dErr
					} else {
						row.FakeName = dv
					}
				}
			case 3:
				vb, vbErr := rv.Decode()
				if vbErr != nil {
					derr = vbErr
				} else {
					dv, dErr := FakeMac.Decode(vb)
					if dErr != nil {
						derr = dErr
					} else {
						row.FakeMac = dv
					}
				}
			case 4:
				if v, okRaw := snmp.RawCounter64(rv); okRaw {
					row.FakeOctets = uint64(v)
				} else {
					vb, vbErr := rv.Decode()
					if vbErr != nil {
						derr = vbErr
					} else {
						dv, dErr := FakeOctets.Decode(vb)
						if dErr != nil {
							derr = dErr
						} else {
							row.FakeOctets = dv
						}
					}
				}
			case 5:
				if v, okRaw := snmp.RawTimeTicks(rv); okRaw {
					row.FakeLastChange = uint32(v)
				} else {
					vb, vbErr := rv.Decode()
					if vbErr != nil {
						derr = vbErr
					} else {
						dv, dErr := FakeLastChange.Decode(vb)
						if dErr != nil {
							derr = dErr
						} else {
							row.FakeLastChange = dv
						}
					}
				}
			}
			if derr != nil {
				for i := 0; i < len(orderKey); i++ {
					if orderKey[i] == string(idxWire) {
						break
					}
					if !yield(orderIdx[i], *buffer[orderKey[i]]) {
						tw.rw.Fail(derr)
						return
					}
				}
				tw.rw.Fail(derr)
				return
			}
		}

		for i := 0; i < len(orderIdx); i++ {
			if !yield(orderIdx[i], *buffer[orderKey[i]]) {
				return
			}
		}
	}
}

// Err returns the underlying walker's terminal error, or nil if
// the walk completed naturally.
func (tw *FakeTableWalker) Err() error {
	return tw.rw.Err()
}

// fakeTableT is the singleton type of FakeTable.
type fakeTableT struct{}

// FakeTable is the descriptor for the fakeTable table.
var FakeTable fakeTableT

// Walk launches a BulkWalk over fakeTable and returns a
// table-aware iterator. Only the columns listed in cols are
// decoded; varbinds for unlisted columns are skipped. The walk
// rides the raw fast path (BulkWalkRaw); sessions or responses
// that cannot deliver raw bytes degrade transparently to the
// generic per-varbind decode.
func (fakeTableT) Walk(ctx context.Context, sess snmp.Session, cols ...snmp.AnyColumn) *FakeTableWalker {
	w := sess.BulkWalkRaw(ctx, snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3))
	byCol := make(map[uint32]snmp.AnyColumn, len(cols))

	for _, c := range cols {
		o := c.OID()
		if o.Len() == 0 {
			continue
		}
		byCol[o.At(o.Len()-1)] = c
	}

	return &FakeTableWalker{
		byCol: byCol,
		cols:  cols,
		rw:    w,
	}
}

// decodeFakeTableRow decodes one row of FakeTable from the supplied
// VarBinds. Each VarBind's OID determines which row field it populates
// (via the column's last sub-id). VarBinds with unknown column-ids are
// ignored. Absent columns leave their field at its zero value.
func decodeFakeTableRow(idx snmp.OID, vbs []snmp.VarBind) (FakeTableRow, error) {
	var row FakeTableRow
	row.Index = idx

	for _, vb := range vbs {
		o := vb.GetHeader().OID
		if o.Len() == 0 {
			continue
		}
		entryLen := snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1).Len()
		if o.Len() <= entryLen {
			continue
		}
		colID := o.At(entryLen)
		switch colID {
		case 2:
			dv, derr := FakeName.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeName = dv
		case 3:
			dv, derr := FakeMac.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeMac = dv
		case 4:
			dv, derr := FakeOctets.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeOctets = dv
		case 5:
			dv, derr := FakeLastChange.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeLastChange = dv
		}
	}

	return row, nil
}

// equalFakeTableRow compares two FakeTableRow values for equality.
// Used by [snmp.Watcher] to compute ChangeKindModified emits. Field-by-
// field with the type-appropriate comparator (bytes.Equal for []byte,
// OID.Equal for OID, time.Time.Equal for time.Time, == for everything else).
func equalFakeTableRow(a FakeTableRow, b FakeTableRow) bool {
	return a.Index.Equal(b.Index) && a.FakeName == b.FakeName && bytes.Equal(a.FakeMac, b.FakeMac) && a.FakeOctets == b.FakeOctets && a.FakeLastChange == b.FakeLastChange
}

// mergeFakeTableRow merges the values decoded from vbs into dst, leaving fields
// whose columns are not present in vbs unchanged. Used by [snmp.Watcher]
// to maintain per-row state under partial-column fetches (Counter-tier,
// Static-tier). Best-effort: individual VarBind decode failures are
// silently skipped rather than propagated, because partial-fetch ticks
// surface transient errors through [snmp.Watcher.LastTickErr] at the
// call-site granularity rather than per-VarBind.
func mergeFakeTableRow(dst *FakeTableRow, vbs []snmp.VarBind) {
	for _, vb := range vbs {
		o := vb.GetHeader().OID
		if o.Len() == 0 {
			continue
		}
		entryLen := snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1).Len()
		if o.Len() <= entryLen {
			continue
		}
		colID := o.At(entryLen)
		switch colID {
		case 2:
			dv, derr := FakeName.Decode(vb)
			if derr == nil {
				dst.FakeName = dv
			}
		case 3:
			dv, derr := FakeMac.Decode(vb)
			if derr == nil {
				dst.FakeMac = dv
			}
		case 4:
			dv, derr := FakeOctets.Decode(vb)
			if derr == nil {
				dst.FakeOctets = dv
			}
		case 5:
			dv, derr := FakeLastChange.Decode(vb)
			if derr == nil {
				dst.FakeLastChange = dv
			}
		}
	}
}

// FakeTableWatcher is a table-aware Watcher over FakeTable.
// Construct via FakeTable.Watch(ctx, sess, cols, opts...).
type FakeTableWatcher struct {
	w *snmp.Watcher[FakeTableRow]
}

// Iter returns the range-over-func view of the Watcher's event stream.
// See [snmp.Watcher.Iter] for the contract.
func (tw *FakeTableWatcher) Iter() iter.Seq2[snmp.OID, snmp.WatchEvent[FakeTableRow]] {
	return tw.w.Iter()
}

// Err returns the underlying Watcher's terminal error, or nil if it
// completed naturally. See [snmp.Watcher.Err].
func (tw *FakeTableWatcher) Err() error {
	return tw.w.Err()
}

// Close signals the Watcher's tick goroutine to terminate. Idempotent.
// See [snmp.Watcher.Close].
func (tw *FakeTableWatcher) Close() error {
	return tw.w.Close()
}

// Fallback reports whether the Watcher has transitioned to fallback
// mode. See [snmp.Watcher.Fallback].
func (tw *FakeTableWatcher) Fallback() bool {
	return tw.w.Fallback()
}

// LastTickErr returns the most-recent transient per-tick error.
// See [snmp.Watcher.LastTickErr].
func (tw *FakeTableWatcher) LastTickErr() error {
	return tw.w.LastTickErr()
}

// TableRoot returns the OID of the table this Watcher operates over.
func (tw *FakeTableWatcher) TableRoot() snmp.OID {
	return tw.w.TableRoot()
}

// Watch opens a long-lived watch on FakeTable.
//
// cols selects the columns whose values are reported on every emitted
// event. opts override cadence bounds, per-column tier classifications,
// fallback behavior, and other policy — see [snmp.WatchOption] for the
// full set.
//
// cols is a slice rather than variadic because opts is variadic and
// Go forbids two variadic parameters.
//
// Events emitted on this stream:
//   - ChangeKindAdded    — Row populated, Prev always nil.
//   - ChangeKindModified — Row is current state. Prev is nil unless
//     the caller passed [snmp.WithPrevRow]; when
//     set, Prev carries the previous Row.
//   - ChangeKindRemoved  — Row carries the last-known state at the
//     time the row disappeared. Prev is nil.
//
// The returned Watcher must be Closed when the caller is done; iteration
// exit alone does not free the underlying goroutine until Close.
//
// On validation failure (invalid cadence bounds, tier override of the
// indicator column, etc.) Watch returns a Watcher whose Err() returns
// the cause immediately; range loops exit without emitting events and
// Close is a no-op.
func (fakeTableT) Watch(ctx context.Context, sess snmp.Session, cols []snmp.AnyColumn, opts ...snmp.WatchOption) *FakeTableWatcher {
	allOpts := append([]snmp.WatchOption{snmp.WithTierLookup(ColumnTier)}, opts...)
	w, _ := snmp.NewWatcher[FakeTableRow](ctx, sess, FakeTableIndicator, cols, decodeFakeTableRow, equalFakeTableRow, mergeFakeTableRow, allOpts...)

	return &FakeTableWatcher{w: w}
}

// fAKEMIBOIDDispatch maps column wire keys ([snmp.OID.WireKey]) to their
// typed AnyColumn for fast
// lookup during table-walk decoding. Per-MIB-module — no global
// registry; cross-package callers should consult OIDDispatch().
var fAKEMIBOIDDispatch = map[string]snmp.AnyColumn{
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 2).WireKey(): FakeName,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 3).WireKey(): FakeMac,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 4).WireKey(): FakeOctets,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 5).WireKey(): FakeLastChange,
}

// OIDDispatch returns a shallow copy of the package's wire-key →
// AnyColumn map. The copy isolates callers from accidental mutation
// of the package-internal map (#12).
func OIDDispatch() map[string]snmp.AnyColumn {
	out := make(map[string]snmp.AnyColumn, len(fAKEMIBOIDDispatch))
	for k, v := range fAKEMIBOIDDispatch {
		out[k] = v
	}
	return out
}

// fAKEMIBColumnTiers maps column wire keys ([snmp.OID.WireKey]) to their
// snmp.Tier classification.
// Tier classification drives the Watcher's scheduler — counters fire
// on their own cadence, state columns refresh on indicator advance,
// and indicator columns drive the change-detection probe itself.
// See snmp.Tier and snmp.Watcher for the consumption contract.
var fAKEMIBColumnTiers = map[string]snmp.Tier{
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 2).WireKey(): snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 3).WireKey(): snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 4).WireKey(): snmp.TierCounter,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 5).WireKey(): snmp.TierIndicator,
}

// ColumnTier returns the codegen-classified [snmp.Tier] for col, or
// snmp.TierUnknown when col's OID is not known to this package. The
// generated Watch methods install this function via
// [snmp.WithTierLookup]; returning TierUnknown lets the runtime fall
// back to its wire-Kind heuristic for columns this package does not
// classify. Caller overrides via [snmp.WithColumnTier] still win.
func ColumnTier(col snmp.AnyColumn) snmp.Tier {
	if col == nil {
		return snmp.TierUnknown
	}
	t, ok := fAKEMIBColumnTiers[col.Key()]
	if !ok {
		return snmp.TierUnknown
	}
	return t
}

// FakeTableIndicator is the per-row change indicator for fakeTable.
// The Watcher probes the indicator column on each tick and only
// re-fetches a row's other state-tier columns when the row's
// indicator value advances. See [snmp.NewPerRowIndicator] and
// [snmp.Watcher] for the consumption contract.
// Discovered by mibgen structural rule: per-row column name matches indicator-suffix heuristic.
var FakeTableIndicator = snmp.MustChangeIndicator(snmp.NewPerRowIndicator(FakeLastChange, snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3)))
