// Code generated by yanggen. DO NOT EDIT.
// generator: yanggen-5
// module: fixture-aug revision: 2026-01-03
// source sha256: 814ff78e26ab46b435796b8adc9e53fd9a2a55070e1bdcab43815c29313a0082

// Package fixtureaug binds the YANG module fixture-aug.
package fixtureaug

import yang "go.aledante.io/FlowSeer/src/protocol/yang"

// moduleFixtureAug identifies the fixture-aug YANG module.
var moduleFixtureAug = &yang.Module{
	Name:      "fixture-aug",
	Namespace: "urn:flowseer:fixture-aug",
}
