// Code generated by yanggen. DO NOT EDIT.
// generator: yanggen-6
// module: fixture-aug revision: 2026-01-03
// source sha256: 814ff78e26ab46b435796b8adc9e53fd9a2a55070e1bdcab43815c29313a0082

// Package fixtureaug binds the YANG module fixture-aug.
package fixtureaug

import yang "go.aledante.io/FlowSeer/src/protocol/yang"

// moduleFixtureAug identifies the fixture-aug YANG module.
var moduleFixtureAug = &yang.Module{
	Name:      "fixture-aug",
	Namespace: "urn:flowseer:fixture-aug",
}

// Flag is the fixture-aug node /fixture-main:shape-probe/by-owner-b/fixture-aug:flag.
type Flag struct{}

// FlagSchema describes Flag for the generic codecs.
var FlagSchema = &yang.Schema{
	Fields: []yang.Field{},
	Module: moduleFixtureAug,
	Name:   "flag",
}

// ByOwnerBAugment is the fixture-aug augment group at /fixture-main:shape-probe/by-owner-b.
type ByOwnerBAugment struct {
	Flag *Flag
}

// ByOwnerBAugmentSchema describes ByOwnerBAugment group fields with no codec root.
var ByOwnerBAugmentSchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: FlagSchema, GoName: "Flag", Name: "flag"},
	},
	Module: moduleFixtureAug,
}

// ServerAugment is the fixture-aug augment group at /fixture-main:servers/server.
type ServerAugment struct {
	Owner *string
}

// ServerAugmentSchema describes ServerAugment group fields with no codec root.
var ServerAugmentSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Owner", Name: "owner", Type: yang.TString},
	},
	Module: moduleFixtureAug,
}

// SlotAugment is the fixture-aug augment group at /fixture-main:shape-probe/by-module-b/slot.
type SlotAugment struct {
	Value *uint32
}

// SlotAugmentSchema describes SlotAugment group fields with no codec root.
var SlotAugmentSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Value", Name: "value", Type: yang.TUint32},
	},
	Module: moduleFixtureAug,
}
