// Code generated by mibgen; DO NOT EDIT.
//
// Source MIB:    FAKE-KEYS-MIB
// Source path:   testdata/mibs/FAKE-KEYS-MIB.mib
// Source SHA-256: e0ce702916e31a55a7076a71770580a6581bf265687ee8119d7cab8799b3e6b9
//
// Regenerate with `go generate .` at the repository root.

// Package fakekeysmib binds the SMI objects declared by FAKE-KEYS-MIB.
package fakekeysmib

import (
	"context"
	"iter"

	errs "go.aledante.io/FlowSeer/src/common/errs"
	snmp "go.aledante.io/FlowSeer/src/protocol/snmp"
)

// FakeKeyIndex is the textual convention FakeKeyIndex. A value identifies one row of
// fakeKeyTable, and a column of this type in any table refers to that row.
// A unique value identifying one row of fakeKeyTable. A column of this
// type elsewhere refers to that row.
type FakeKeyIndex int32

// HomeTable returns the descriptor of fakeKeyTable, the table a FakeKeyIndex value
// identifies a row of.
func (FakeKeyIndex) HomeTable() snmp.TableDescriptor {
	return snmp.TableDescriptor{
		KeyType: "FakeKeyIndex",
		Root:    snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 2, 1),
	}
}

// FakeKeyName is the column fakeKeyName of table fakeKeyTable.
// Name.
var FakeKeyName = snmp.NewColumn[string](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 2, 1, 1, 2), snmp.KindOctetString, func(vb snmp.VarBind) (string, error) {
	return snmp.DecodeDisplayString(vb)
})

// FakeKeyTableKey is the decoded INDEX of one fakeKeyTable row, one field per
// part in INDEX order. It is comparable and usable as a map key.
type FakeKeyTableKey struct {
	FakeKeyIndex FakeKeyIndex
}

var fakeKeyTableIndexShapes = []snmp.IndexShape{{Kind: snmp.IndexInteger}}

// decodeFakeKeyTableKey decodes the instance suffix of one fakeKeyTable row. ok is false
// when the suffix does not match the declared INDEX; the key is then zero.
func decodeFakeKeyTableKey(idx snmp.OID) (FakeKeyTableKey, bool) {
	parts, ok := snmp.DecodeIndex(idx, fakeKeyTableIndexShapes)
	if !ok {
		return FakeKeyTableKey{}, false
	}
	return FakeKeyTableKey{FakeKeyIndex: FakeKeyIndex(parts[0].Integer)}, true
}

// FakeKeyTableRow is one row of fakeKeyTable. Key is the decoded INDEX; a
// suffix that does not match the declared INDEX leaves it zero, and
// [FakeKeyTableRow.KeyValid] reports which. The remaining fields are
// populated only for columns the caller passed to Walk(). Use
// [FakeKeyTableRow.Observed] to tell a reported zero from a column the
// agent never answered.
// The zero value has no observed columns. Concurrent reads are safe;
// callers must synchronize mutation of the row or its referenced data.
type FakeKeyTableRow struct {
	Key         FakeKeyTableKey
	keyValid    bool
	FakeKeyName string

	// observed carries one bit per column of this table, in
	// column-OID order, set when the walk decoded a value for
	// that column on this row.
	observed [1]uint64
}

// KeyValid reports whether the row's instance suffix decoded as the declared
// INDEX. A false result means Key is zero and the agent's suffix did not
// have the declared shape; the row's columns are still populated.
func (r FakeKeyTableRow) KeyValid() bool {
	return r.keyValid
}

// Observed reports whether col returned a value for this row. A column
// the agent answered reads true even when the answer was zero or empty;
// a column that was requested but never landed, one that was not passed
// to Walk, and any column of another table all read false.
func (r FakeKeyTableRow) Observed(col snmp.AnyColumn) bool {
	switch col.Key() {
	case FakeKeyName.Key():
		return r.observed[0]&(1<<0) != 0
	}

	return false
}

// FakeKeyTableWalker streams selected columns of fakeKeyTable.
// The zero value is not usable; construct via FakeKeyTable.Walk(ctx, sess, cols...).
// Iteration is single-use and single-consumer; Close and Err are safe concurrently.
type FakeKeyTableWalker struct {
	rw   *snmp.ColumnWalker
	cols []snmp.AnyColumn
}

// Iter yields complete selected-column rows in numeric OID suffix order
// (192.168.0.2 precedes 192.168.0.10). It retains one batch per selected
// column. Breaking iteration stops retrieval. A decode error omits the
// failing row and later rows; already delivered rows remain valid. Check Err.
// A row whose suffix does not decode as the declared INDEX is still yielded,
// with a zero Key and KeyValid false; the yielded OID is its raw suffix.
func (tw *FakeKeyTableWalker) Iter() iter.Seq2[snmp.OID, FakeKeyTableRow] {
	return func(yield func(snmp.OID, FakeKeyTableRow) bool) {
		for idx, cells := range tw.rw.Iter() {
			var row FakeKeyTableRow
			row.Key, row.keyValid = decodeFakeKeyTableKey(idx)
			for _, cell := range cells {
				rv := cell.Value
				var derr error
				switch tw.cols[cell.Column].Key() {
				case FakeKeyName.Key():
					vb, vbErr := rv.Decode()
					if vbErr != nil {
						derr = vbErr
					} else {
						dv, dErr := FakeKeyName.Decode(vb)
						if dErr != nil {
							derr = dErr
						} else {
							row.FakeKeyName = dv
							row.observed[0] |= 1 << 0
						}
					}
				}
				if derr != nil {
					tw.rw.Fail(derr)
					return
				}
			}
			if !yield(idx, row) {
				return
			}
		}
	}
}

// Err returns the underlying walker's terminal error, or nil if
// the walk completed naturally.
func (tw *FakeKeyTableWalker) Err() error {
	return tw.rw.Err()
}

// fakeKeyTableT is the singleton type of FakeKeyTable.
type fakeKeyTableT struct{}

// FakeKeyTable is the descriptor for the fakeKeyTable table.
var FakeKeyTable fakeKeyTableT

// Close stops retrieval. It is idempotent and safe during iteration.
func (tw *FakeKeyTableWalker) Close() {
	tw.rw.Close()
}

// Walk lazily retrieves only selected columns with bounded defaults.
// Rows are the union of selected values in numeric OID index order.
// No columns means no rows or requests. Duplicate selections are ignored.
// Unknown or foreign columns fail before I/O with [snmp.ErrForeignColumn].
func (t fakeKeyTableT) Walk(ctx context.Context, sess snmp.Session, cols ...snmp.AnyColumn) *FakeKeyTableWalker {
	return t.WalkWithOptions(ctx, sess, snmp.TableWalkOptions{}, cols...)
}

// WalkWithOptions is Walk with request sizing and per-call controls.
// SNMPv1 remains unsupported. Parent cancellation is an error; stopping iteration is successful.
func (fakeKeyTableT) WalkWithOptions(ctx context.Context, sess snmp.Session, options snmp.TableWalkOptions, cols ...snmp.AnyColumn) *FakeKeyTableWalker {
	seen := make(map[string]bool)
	var selected []snmp.AnyColumn
	var roots []snmp.OID
	for _, c := range cols {
		switch c.Key() {
		case FakeKeyName.Key():
		default:
			w := snmp.WalkColumns(ctx, sess, nil, options)
			w.Fail(errs.Wrapf(snmp.ErrForeignColumn, "fakeKeyTable.Walk: column %s", c.OID()))
			return &FakeKeyTableWalker{rw: w}
		}
		if seen[c.Key()] {
			continue
		}
		seen[c.Key()] = true
		selected = append(selected, c)
		roots = append(roots, c.OID())
	}
	return &FakeKeyTableWalker{
		cols: selected,
		rw:   snmp.WalkColumns(ctx, sess, roots, options),
	}
}

// fAKEKEYSMIBOIDDispatch maps column wire keys ([snmp.OID.WireKey]) to their
// typed AnyColumn for fast
// lookup during table-walk decoding. Per-MIB-module — no global
// registry; cross-package callers should consult OIDDispatch().
var fAKEKEYSMIBOIDDispatch = map[string]snmp.AnyColumn{snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 2, 1, 1, 2).WireKey(): FakeKeyName}

// OIDDispatch returns a shallow copy of the package's wire-key →
// AnyColumn map. The copy isolates callers from accidental mutation
// of the package-internal map.
func OIDDispatch() map[string]snmp.AnyColumn {
	out := make(map[string]snmp.AnyColumn, len(fAKEKEYSMIBOIDDispatch))
	for k, v := range fAKEKEYSMIBOIDDispatch {
		out[k] = v
	}
	return out
}
