// Code generated by mibgen; DO NOT EDIT.
//
// Source MIB:    FAKE-KEYS-MIB
// Source path:   testdata/mibs/FAKE-KEYS-MIB.mib
// Source SHA-256: e0ce702916e31a55a7076a71770580a6581bf265687ee8119d7cab8799b3e6b9
//
// Regenerate with `go generate .` at the repository root.

// Package fakekeysmib binds the SMI objects declared by FAKE-KEYS-MIB.
package fakekeysmib

import snmp "go.aledante.io/FlowSeer/src/protocol/snmp"

// FakeKeyIndex is the textual convention FakeKeyIndex. A value identifies one row of
// fakeKeyTable, and a column of this type in any table refers to that row.
// A unique value identifying one row of fakeKeyTable. A column of this
// type elsewhere refers to that row.
type FakeKeyIndex int32

// HomeTable returns the descriptor of fakeKeyTable, the table a FakeKeyIndex value
// identifies a row of.
func (FakeKeyIndex) HomeTable() snmp.TableDescriptor {
	return FakeKeyTable.Descriptor()
}

// FakeKeyName is the column fakeKeyName of table fakeKeyTable.
// Name.
var (
	FakeKeyName         = snmp.NewTableColumn[string](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 2, 1, 1, 2), snmp.KindOctetString, snmp.DecodeDisplayString, 0)
	fakeKeyTableColumns = []snmp.AnyColumn{FakeKeyName}
)

// FakeKeyTableKey is the decoded INDEX of one fakeKeyTable row, one field per
// part in INDEX order. It is comparable and usable as a map key.
type FakeKeyTableKey struct {
	FakeKeyIndex FakeKeyIndex
}

var fakeKeyTableIndexShapes = []snmp.IndexShape{{Kind: snmp.IndexInteger}}

// decodeFakeKeyTableKey decodes the instance suffix of one fakeKeyTable row. ok is false
// when the suffix does not match the declared INDEX; the key is then zero.
func decodeFakeKeyTableKey(idx snmp.OID) (FakeKeyTableKey, bool) {
	var parts [1]snmp.IndexValue
	if !snmp.DecodeIndexInto(parts[:], idx, fakeKeyTableIndexShapes) {
		return FakeKeyTableKey{}, false
	}
	return FakeKeyTableKey{FakeKeyIndex: FakeKeyIndex(parts[0].Integer)}, true
}

// FakeKeyTableRow is one row of fakeKeyTable. Key is the decoded INDEX; a
// suffix that does not match the declared INDEX leaves it zero, and
// [FakeKeyTableRow.KeyValid] reports which. The remaining fields are
// populated only for columns the caller passed to Walk(). Use
// [FakeKeyTableRow.Observed] to tell a reported zero from a column the
// agent never answered.
// The zero value has no observed columns. Concurrent reads are safe;
// callers must synchronize mutation of the row or its referenced data.
type FakeKeyTableRow struct {
	Key         FakeKeyTableKey
	keyValid    bool
	FakeKeyName string

	// observed carries one bit per column of this table, in
	// column-OID order, set when the walk decoded a value for
	// that column on this row.
	observed [1]uint64
}

// KeyValid reports whether the row's instance suffix decoded as the declared
// INDEX. A false result means Key is zero and the agent's suffix did not
// have the declared shape; the row's columns are still populated.
func (r FakeKeyTableRow) KeyValid() bool {
	return r.keyValid
}

// Observed reports whether col returned a value for this row. A column
// the agent answered reads true even when the answer was zero or empty;
// a column that was requested but never landed, one that was not passed
// to Walk, and any column of another table all read false.
func (r FakeKeyTableRow) Observed(col snmp.AnyColumn) bool {
	return snmp.ColumnObserved(r.observed[:], fakeKeyTableColumns, col)
}

// FakeKeyTableWalker streams selected columns of fakeKeyTable.
// The zero value is not usable; construct via FakeKeyTable.Walk(ctx, sess, cols...).
// Iteration is single-use and single-consumer; Close and Err are safe concurrently.
type FakeKeyTableWalker struct {
	snmp.TableWalker[FakeKeyTableRow]
}

// fakeKeyTableT is the singleton type of FakeKeyTable.
type fakeKeyTableT struct {
	snmp.Table[FakeKeyTableRow, *FakeKeyTableWalker]
}

// FakeKeyTable is the descriptor for the fakeKeyTable table.
var FakeKeyTable = fakeKeyTableT{Table: snmp.NewTable("fakeKeyTable", fakeKeyTableColumns, func(idx snmp.OID, row *FakeKeyTableRow) {
	row.Key, row.keyValid = decodeFakeKeyTableKey(idx)
}, func(row *FakeKeyTableRow, ordinal int, rv snmp.RawVarBind) error {
	switch ordinal {
	case 0:
		return snmp.DecodeColumn(rv, FakeKeyName, &row.FakeKeyName, row.observed[:])
	}
	return nil
}, func(tw snmp.TableWalker[FakeKeyTableRow]) *FakeKeyTableWalker {
	return &FakeKeyTableWalker{TableWalker: tw}
})}

// Descriptor returns the table as a [snmp.TableDescriptor]: its root OID, its
// change indicator when the MIB declares one, and the Go type of its row key.
// The descriptor is a value; hold it without the row or walker types to probe
// for the table or declare it as a dependency.
func (fakeKeyTableT) Descriptor() snmp.TableDescriptor {
	return snmp.TableDescriptor{
		KeyType: "FakeKeyTableKey",
		Root:    snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 2, 1),
	}
}

// fAKEKEYSMIBOIDDispatch maps column wire keys ([snmp.OID.WireKey]) to their
// typed AnyColumn for fast
// lookup during table-walk decoding. Per-MIB-module — no global
// registry; cross-package callers should consult OIDDispatch().
var fAKEKEYSMIBOIDDispatch = map[string]snmp.AnyColumn{snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 2, 1, 1, 2).WireKey(): FakeKeyName}

// OIDDispatch returns a shallow copy of the package's wire-key →
// AnyColumn map. The copy isolates callers from accidental mutation
// of the package-internal map.
func OIDDispatch() map[string]snmp.AnyColumn {
	out := make(map[string]snmp.AnyColumn, len(fAKEKEYSMIBOIDDispatch))
	for k, v := range fAKEKEYSMIBOIDDispatch {
		out[k] = v
	}
	return out
}
