// Code generated by mibgen; DO NOT EDIT.
//
// Source MIB:    FAKE-KEYS-MIB
// Source path:   testdata/mibs/FAKE-KEYS-MIB.mib
// Source SHA-256: e0ce702916e31a55a7076a71770580a6581bf265687ee8119d7cab8799b3e6b9
//
// Regenerate with `go generate .` at the repository root.

// Package fakekeysmib binds the SMI objects declared by FAKE-KEYS-MIB.
package fakekeysmib

import snmp "go.aledante.io/FlowSeer/src/protocol/snmp"

// FakeKeyIndex is the textual convention FakeKeyIndex. A value identifies one row of
// fakeKeyTable, and a column of this type in any table refers to that row.
// A unique value identifying one row of fakeKeyTable. A column of this
// type elsewhere refers to that row.
type FakeKeyIndex int32

// HomeTable returns the descriptor of fakeKeyTable, the table a FakeKeyIndex value
// identifies a row of.
func (FakeKeyIndex) HomeTable() snmp.TableDescriptor {
	return FakeKeyTable.Descriptor()
}

// FakeKeyName is fakeKeyName.
// Name.
var (
	FakeKeyName         = snmp.NewTableColumn[string](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 2, 1, 1, 2), snmp.KindOctetString, snmp.DecodeDisplayString, 0)
	fakeKeyTableColumns = []snmp.AnyColumn{FakeKeyName}
)

// FakeKeyTableKey is the decoded INDEX of one fakeKeyTable row, one field per
// part in INDEX order. It is comparable and usable as a map key.
type FakeKeyTableKey struct {
	FakeKeyIndex FakeKeyIndex
}

var fakeKeyTableIndexShapes = []snmp.IndexShape{{Kind: snmp.IndexInteger}}

// decodeFakeKeyTableKey decodes the instance suffix of one fakeKeyTable row. ok is false
// when the suffix does not match the declared INDEX; the key is then zero.
func decodeFakeKeyTableKey(idx snmp.OID) (FakeKeyTableKey, bool) {
	var parts [1]snmp.IndexValue
	if !snmp.DecodeIndexInto(parts[:], idx, fakeKeyTableIndexShapes) {
		return FakeKeyTableKey{}, false
	}
	return FakeKeyTableKey{FakeKeyIndex: FakeKeyIndex(parts[0].Integer)}, true
}

// FakeKeyTableRow is one row of fakeKeyTable; KeyValid reports index validity, use Observed for field presence, and concurrent reads are safe.
type FakeKeyTableRow struct {
	Key         FakeKeyTableKey
	keyValid    bool
	FakeKeyName string
	observed    [1]uint64
}

// KeyValid reports whether Key decoded from the row index.
func (r FakeKeyTableRow) KeyValid() bool {
	return r.keyValid
}

// Observed reports whether col supplied this row field, including a zero value.
func (r FakeKeyTableRow) Observed(col snmp.AnyColumn) bool {
	return snmp.ColumnObserved(r.observed[:], fakeKeyTableColumns, col)
}

// FakeKeyTableWalker streams one table walk; its zero value is unusable, and Err/Close are safe concurrently.
type FakeKeyTableWalker struct {
	snmp.TableWalker[FakeKeyTableRow]
}
type fakeKeyTableT struct {
	snmp.Table[FakeKeyTableRow, *FakeKeyTableWalker]
}

// FakeKeyTable is the descriptor for the fakeKeyTable table.
var FakeKeyTable = fakeKeyTableT{Table: snmp.NewTable("fakeKeyTable", fakeKeyTableColumns, func(idx snmp.OID, row *FakeKeyTableRow) {
	row.Key, row.keyValid = decodeFakeKeyTableKey(idx)
}, func(row *FakeKeyTableRow, ordinal int, rv snmp.RawVarBind) error {
	switch ordinal {
	case 0:
		return snmp.DecodeColumn(rv, FakeKeyName, &row.FakeKeyName, row.observed[:])
	}
	return nil
}, func(tw snmp.TableWalker[FakeKeyTableRow]) *FakeKeyTableWalker {
	return &FakeKeyTableWalker{TableWalker: tw}
})}

// Descriptor returns the table identity, change indicator, and row-key type.
func (fakeKeyTableT) Descriptor() snmp.TableDescriptor {
	return snmp.TableDescriptor{
		KeyType: "FakeKeyTableKey",
		Root:    snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 2, 1),
	}
}

// fAKEKEYSMIBOIDDispatch maps column wire keys ([snmp.OID.WireKey]) to their
// typed AnyColumn for fast
// lookup during table-walk decoding. Per-MIB-module — no global
// registry; cross-package callers should consult OIDDispatch().
var fAKEKEYSMIBOIDDispatch = map[string]snmp.AnyColumn{snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 2, 1, 1, 2).WireKey(): FakeKeyName}

// OIDDispatch returns a shallow copy of the package's wire-key →
// AnyColumn map. The copy isolates callers from accidental mutation
// of the package-internal map.
func OIDDispatch() map[string]snmp.AnyColumn {
	out := make(map[string]snmp.AnyColumn, len(fAKEKEYSMIBOIDDispatch))
	for k, v := range fAKEKEYSMIBOIDDispatch {
		out[k] = v
	}
	return out
}
