package main

import (
	"flag"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// updateGolden refreshes the committed goldens under testdata/golden/.
// Run with
//
//	go test ./src/common/yang/cmd/yanggen -run TestEmitFixtureGolden -update-golden
//
// after intentional emitter changes and audit the diff.
var updateGolden = flag.Bool("update-golden", false, "rewrite testdata/golden/* with the current emitter output")

// goldenPkgPrefix roots the fixture goldens as importable packages so
// the round-trip tests in golden_roundtrip_test.go exercise the real
// emitted schemas against the runtime codecs.
const goldenPkgPrefix = "go.aledante.io/FlowSeer/src/common/yang/cmd/yanggen/testdata/golden"

// TestEmitFixtureGolden renders every fixture module and compares
// byte-for-byte against the committed goldens.
func TestEmitFixtureGolden(t *testing.T) {
	vs := fixtureVendor(t)
	for _, m := range vs.Modules {
		got, err := emitOne(m, goldenPkgPrefix)
		if err != nil {
			t.Fatalf("emit %s: %v", m.Name, err)
		}
		goldenPath := filepath.Join("testdata", "golden", "fixture", m.Package, m.Package+".go")
		if *updateGolden {
			if err := os.MkdirAll(filepath.Dir(goldenPath), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(goldenPath, []byte(got), 0o644); err != nil {
				t.Fatal(err)
			}
			t.Logf("updated %s (%d bytes)", goldenPath, len(got))
			continue
		}
		want, err := os.ReadFile(goldenPath)
		if err != nil {
			t.Fatalf("read golden for %s (rerun with -update-golden if first time): %v", m.Name, err)
		}
		if string(want) != got {
			candidate := goldenPath + ".got"
			_ = os.WriteFile(candidate, []byte(got), 0o644)
			t.Errorf("golden mismatch for %s; candidate written to %s — rerun with -update-golden after auditing", m.Name, candidate)
		}
	}
}

// TestEmitFixtureParses ensures each emitted file is syntactically
// valid Go even when goldens are stale.
func TestEmitFixtureParses(t *testing.T) {
	vs := fixtureVendor(t)
	for _, m := range vs.Modules {
		got, err := emitOne(m, goldenPkgPrefix)
		if err != nil {
			t.Fatalf("emit %s: %v", m.Name, err)
		}
		fset := token.NewFileSet()
		if _, err := parser.ParseFile(fset, m.Package+".go", got, parser.AllErrors); err != nil {
			t.Fatalf("emitted %s does not parse: %v\n--- src ---\n%s", m.Name, err, got)
		}
	}
}

// TestEmitFixtureSurface pins the load-bearing emitted symbols
// without demanding byte-exactness: the golden test owns that.
func TestEmitFixtureSurface(t *testing.T) {
	vs := fixtureVendor(t)
	main := moduleByName(t, vs, "fixture-main")
	src, err := emitOne(main, goldenPkgPrefix)
	if err != nil {
		t.Fatal(err)
	}

	wantRE := []string{
		`Listen\s+\*yang\.Value`,
		`Proto\s+\*yang\.Identity`,
		`Ratio\s+\*yang\.Value`,
		`ServerRef\s+\*string`,
		`Server_Name\s+string`,
		`Presence:\s+true`,
	}
	want := []string{
		"Code generated by yanggen. DO NOT EDIT.",
		"module: fixture-main revision: 2026-01-02",
		// Structs, schemas, and descriptors.
		"type Servers struct",
		"type Servers_Server struct",
		"var Servers_ServerSchema =",
		"type Servers_ServerKey struct",
		"func Servers_ServerDescriptor() yang.ListDescriptor",
		// Nested list: flat row with the ancestor key, schema chain,
		// nested decode.
		"type Servers_Server_Endpoint struct",
		"type Servers_Server_EndpointFlatRow struct",
		"yang.DecodeXMLNested[Servers_Server_Endpoint]",
		"yang.DecodeJSONNested[Servers_Server_Endpoint]",
		// Deviation applied: the deviated leaf is gone (asserted via
		// notWant below); presence, unions, identityref, and the
		// leafref key are asserted by wantRE above.
		// Synthetic-row descriptor for a container.
		"func ServersDescriptor() yang.ListDescriptor",
		"yang.SubtreeDescriptor[Servers]",
		// Name collision resolved deterministically with a hash
		// suffix, not silently merged.
		"type AlarmState",
		"type AlarmState_",
	}
	notWant := []string{
		"LegacyFlag", // removed by fixture-dev's deviate not-supported
	}
	for _, w := range want {
		if !strings.Contains(src, w) {
			t.Errorf("emitted fixture-main missing %q", w)
		}
	}
	for _, pat := range wantRE {
		if !regexp.MustCompile(pat).MatchString(src) {
			t.Errorf("emitted fixture-main missing pattern %q", pat)
		}
	}
	for _, w := range notWant {
		if strings.Contains(src, w) {
			t.Errorf("emitted fixture-main unexpectedly contains %q", w)
		}
	}
	if t.Failed() {
		t.Logf("--- src ---\n%s", src)
	}
}

// TestEmitAugmentModule asserts the augmenting module's own emission
// and that its augmented-in nodes live in the target module's package
// with foreign-module qualification.
func TestEmitAugmentModule(t *testing.T) {
	vs := fixtureVendor(t)
	mainSrc, err := emitOne(moduleByName(t, vs, "fixture-main"), goldenPkgPrefix)
	if err != nil {
		t.Fatal(err)
	}
	if !regexp.MustCompile(`Module:\s+"fixture-aug"`).MatchString(mainSrc) {
		t.Error("augmented-in owner leaf lost its defining-module qualification")
	}
	if !regexp.MustCompile(`Owner\s+\*string`).MatchString(mainSrc) {
		t.Error("augmented-in owner leaf missing from the target struct")
	}

	typesSrc, err := emitOne(moduleByName(t, vs, "fixture-types"), goldenPkgPrefix)
	if err != nil {
		t.Fatal(err)
	}
	for _, w := range []string{"Identity_Tcp", "Identity_Udp", "Identity_Protocol"} {
		if !strings.Contains(typesSrc, w) {
			t.Errorf("fixture-types missing identity value %s", w)
		}
	}
}

// TestGoldenPackagesBuild compiles the committed golden packages, so
// the emitted code is known to type-check against the runtime — the
// go tool skips testdata in wildcard walks, so each package is built
// by explicit path.
func TestGoldenPackagesBuild(t *testing.T) {
	if testing.Short() {
		t.Skip("compilation exec test skipped in -short mode")
	}
	entries, err := os.ReadDir(filepath.Join("testdata", "golden", "fixture"))
	if err != nil {
		t.Skipf("no goldens yet: %v", err)
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		dir := "./" + filepath.Join("testdata", "golden", "fixture", e.Name())
		cmd := exec.Command("go", "build", dir)
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Errorf("go build %s: %v\n%s", dir, err, out)
		}
	}
}
