// Code generated by yanggen. DO NOT EDIT.
// generator: yanggen-5
// module: fixture-dev revision: 2026-01-04
// source sha256: 8f9a99521481617a62eb134e05c9b43b9e653003b0adf014be8c7be3e01679fa

// Package fixturedev binds the YANG module fixture-dev.
package fixturedev

import yang "go.aledante.io/FlowSeer/src/protocol/yang"

// moduleFixtureDev identifies the fixture-dev YANG module.
var moduleFixtureDev = &yang.Module{
	Name:      "fixture-dev",
	Namespace: "urn:flowseer:fixture-dev",
}
