// Code generated by yanggen. DO NOT EDIT.
// generator: yanggen-1
// module: fixture-aug revision: 2026-01-03
// source sha256: 4dd3ca0ad3fcb6269631c5e44871bd549e521f52520f22e22e78b228e3898063

// Package fixtureaug binds the YANG module fixture-aug.
package fixtureaug
