package catalog

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

// commentWidth is where a generated doc comment wraps, chosen to match
// what the rest of the tree's comments look like by eye.
const commentWidth = 68

// RenderCodes returns the Go source for the diagnostic code variables,
// one per row, formatted as gofmt would leave it.
//
// The generator writes the result to disk and a test compares the
// committed file against a fresh call, so a hand-edited constant and a
// forgotten regeneration fail the same way.
//
// The codes are declared in internal/diag rather than in package smi
// because the lexer, framer and parser raise them and package smi loads
// what those produce; a code declared at the top would put the package
// on both ends of its own import graph.
func RenderCodes(rows []Entry) ([]byte, error) {
	return render(rows, "diag", "go.aledante.io/FlowSeer/src/common/errs", func(r Entry, _ string) string {
		return fmt.Sprintf("errs.NewCode(%q)", r.Code)
	})
}

// RenderAliases returns the Go source for package smi's re-export of the
// diagnostic codes.
//
// Package smi is the face a caller matches diagnostics against, and the
// obligation that reporting one takes a single import applies just as
// much to reading one. The aliases carry no string literal, so the
// repo-wide uniqueness scan still sees each code declared exactly once.
func RenderAliases(rows []Entry) ([]byte, error) {
	return render(rows, "smi", "go.aledante.io/FlowSeer/src/protocol/smi/internal/diag", func(_ Entry, name string) string {
		return "diag." + name
	})
}

// render returns the Go source for one generated file of diagnostic code
// variables: the validated rows as a `var` block in package pkg, importing
// importPath, with value supplying the right-hand side of each declaration
// from the row and the variable's name.
func render(rows []Entry, pkg, importPath string, value func(r Entry, name string) string) ([]byte, error) {
	if err := Validate(rows); err != nil {
		return nil, fmt.Errorf("catalog is invalid: %w", err)
	}

	var b bytes.Buffer

	writeGeneratedHeader(&b)
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "import %q\n\n", importPath)
	b.WriteString("// The diagnostic codes, one per catalog row. A code is a wire\n")
	b.WriteString("// contract: append-only, never renamed, never reused for a different\n")
	b.WriteString("// condition. Severity is not part of a code's identity and may be\n")
	b.WriteString("// regraded; the code may not.\n")
	b.WriteString("var (\n")

	for i, r := range rows {
		if i > 0 {
			b.WriteString("\n")
		}

		name := "ErrCode" + r.Tag
		for _, line := range wrapComment(name+" marks "+r.Description+".", commentWidth) {
			fmt.Fprintf(&b, "\t// %s\n", line)
		}
		fmt.Fprintf(&b, "\t%s = %s\n", name, value(r, name))
	}

	b.WriteString(")\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated source: %w", err)
	}

	return src, nil
}

// writeGeneratedHeader writes the banner both rendered files carry.
func writeGeneratedHeader(b *bytes.Buffer) {
	b.WriteString("// Code generated by src/protocol/smi/internal/catalog/gen; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// The diagnostic table in internal/catalog is the source of truth.\n")
	b.WriteString("// Append a row there and run `go generate ./src/protocol/smi/...`.\n\n")
}

// wrapComment greedily breaks text into lines of at most width bytes. A
// word longer than width gets its own line rather than being split.
func wrapComment(text string, width int) []string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return nil
	}

	lines := []string{words[0]}
	for _, w := range words[1:] {
		last := len(lines) - 1
		if len(lines[last])+1+len(w) <= width {
			lines[last] += " " + w

			continue
		}

		lines = append(lines, w)
	}

	return lines
}
