// Code generated by mibgen; DO NOT EDIT.
//
// Source MIBs:   FAKE-VENDOR-A-MIB, FAKE-VENDOR-B-MIB
//
// Regenerate with `go generate .` at the repository root.

// Package sysobjectid resolves a sysObjectID to the deepest naming node the
// configured MIB modules declare under the enterprises subtree.
package sysobjectid

import snmp "go.aledante.io/FlowSeer/src/protocol/snmp"

// Entry is one naming node of the identity table.
type Entry struct {
	// OID is the node's object identifier.
	OID snmp.OID
	// Name is the descriptor the MIB declares the node under.
	Name string
	// Module is the MIB module that declares the node.
	Module string
	// Description is the first paragraph of the node's DESCRIPTION,
	// capped in length, or empty for a plain OID assignment.
	Description string
}

// entries is the table in OID order, one entry per OID.
var entries = []Entry{
	{OID: snmp.MustOID(1, 3, 6, 1, 4, 1, 99996, 1), Name: "fakeSharedByA", Module: "FAKE-VENDOR-A-MIB"},
	{OID: snmp.MustOID(1, 3, 6, 1, 4, 1, 99997), Name: "fakeVendorB", Module: "FAKE-VENDOR-B-MIB", Description: "Root of the Fake Vendor B registration subtree."},
	{OID: snmp.MustOID(1, 3, 6, 1, 4, 1, 99997, 1), Name: "fakeVendorBProducts", Module: "FAKE-VENDOR-B-MIB"},
	{OID: snmp.MustOID(1, 3, 6, 1, 4, 1, 99997, 1, 1), Name: "fakeVendorBAccessPoint", Module: "FAKE-VENDOR-B-MIB", Description: "The access point."},
	{OID: snmp.MustOID(1, 3, 6, 1, 4, 1, 99998), Name: "fakeVendorA", Module: "FAKE-VENDOR-A-MIB", Description: "Root of the Fake Vendor A registration subtree."},
	{OID: snmp.MustOID(1, 3, 6, 1, 4, 1, 99998, 1), Name: "fakeVendorAProducts", Module: "FAKE-VENDOR-A-MIB", Description: "Registration point for every Fake Vendor A product. A sysObjectID under this node names one product model, and a model that is not listed here still resolves to the family node above it, so a firmware release that registers a new model"},
	{OID: snmp.MustOID(1, 3, 6, 1, 4, 1, 99998, 1, 1), Name: "fakeVendorASwitchFamily", Module: "FAKE-VENDOR-A-MIB"},
	{OID: snmp.MustOID(1, 3, 6, 1, 4, 1, 99998, 1, 1, 1), Name: "fakeVendorASwitch24", Module: "FAKE-VENDOR-A-MIB", Description: "The 24-port switch."},
	{OID: snmp.MustOID(1, 3, 6, 1, 4, 1, 99998, 1, 1, 2), Name: "fakeVendorASwitch48", Module: "FAKE-VENDOR-A-MIB"},
	{OID: snmp.MustOID(1, 3, 6, 1, 4, 1, 99998, 1, 2), Name: "fakeVendorARouterFamily", Module: "FAKE-VENDOR-A-MIB"},
}

// oids is the set the longest-prefix lookup searches.
var oids = func() snmp.OIDSet {
	list := make([]snmp.OID, len(entries))
	for i, e := range entries {
		list[i] = e.OID
	}
	return snmp.NewOIDSet(list)
}()

// byKey indexes entries by [snmp.OID.WireKey] for exact lookup.
var byKey = func() map[string]Entry {
	m := make(map[string]Entry, len(entries))
	for _, e := range entries {
		m[e.OID.WireKey()] = e
	}
	return m
}()

// Lookup returns the deepest entry whose OID is a prefix of oid, which
// is the entry at oid itself when one is declared, and false when no
// configured module declares a node above oid.
func Lookup(oid snmp.OID) (Entry, bool) {
	member, ok := oids.Longest(oid)
	if !ok {
		return Entry{}, false
	}
	return byKey[member.WireKey()], true
}

// Exact returns the entry declared at oid itself, and false when none is.
func Exact(oid snmp.OID) (Entry, bool) {
	e, ok := byKey[oid.WireKey()]
	return e, ok
}

// Entries returns a copy of the table in OID order.
func Entries() []Entry {
	out := make([]Entry, len(entries))
	copy(out, entries)
	return out
}
