// Code generated by yanggen. DO NOT EDIT.
// generator: yanggen-6
// module: fixture-aug2 revision: 2026-01-05
// source sha256: 67a5589bc05c261008421581031b0bcc12233d2e6bfe30bb0ce5744e61317644

// Package fixtureaug2 binds the YANG module fixture-aug2.
package fixtureaug2

import yang "go.aledante.io/FlowSeer/src/protocol/yang"

// moduleFixtureAug2 identifies the fixture-aug2 YANG module.
var moduleFixtureAug2 = &yang.Module{
	Name:      "fixture-aug2",
	Namespace: "urn:flowseer:fixture-aug2",
}

// Mirror is the fixture-aug2 node /fixture-main:servers/fixture-aug2:mirror.
type Mirror struct {
	ID *string
}

// MirrorSchema describes Mirror for the generic codecs.
var MirrorSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "ID", Name: "id", Type: yang.TString},
	},
	Keys:   []string{"id"},
	Module: moduleFixtureAug2,
	Name:   "mirror",
}

// ServerAugment is the fixture-aug2 augment group at /fixture-main:servers/server.
type ServerAugment struct {
	Owner *uint8
	Port  *string
}

// ServerAugmentSchema describes ServerAugment group fields with no codec root.
var ServerAugmentSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Owner", Name: "owner", Type: yang.TUint8},
		{GoName: "Port", Name: "port", Type: yang.TString},
	},
	Module: moduleFixtureAug2,
}

// ServersAugment is the fixture-aug2 augment group at /fixture-main:servers.
type ServersAugment struct {
	Mirror []Mirror
}

// ServersAugmentSchema describes ServersAugment group fields with no codec root.
var ServersAugmentSchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: MirrorSchema, GoName: "Mirror", List: true, Name: "mirror"},
	},
	Module: moduleFixtureAug2,
}
