// Code generated by mibgen; DO NOT EDIT.
//
// Source MIB:    FAKE-MIB
// Source path:   testdata/mibs/FAKE-MIB.mib
// Source SHA-256: d28f3aef3e1f103f3ac02811fcd4bb9eca39bee8545caf46a736ac087a19aed6
//
// Regenerate with `go generate .` at the repository root.

// Package fakemib binds the SMI objects declared by FAKE-MIB.
package fakemib

import (
	"bytes"
	"context"
	"fmt"
	"iter"
	"net"

	errs "go.aledante.io/FlowSeer/src/common/errs"
	snmp "go.aledante.io/FlowSeer/src/protocol/snmp"
)

// FakeStatusValue is the SMI enum fakeStatus (inline).
// An enum-typed scalar.
//
// Values outside the named constants are preserved. Concurrent reads are safe;
// callers must synchronize writes to a shared value.
type FakeStatusValue int32

const (
	// FakeStatusValueUp represents the SMI value up.
	FakeStatusValueUp FakeStatusValue = 1
	// FakeStatusValueDown represents the SMI value down.
	FakeStatusValueDown FakeStatusValue = 2
	// FakeStatusValueTesting represents the SMI value testing.
	FakeStatusValueTesting FakeStatusValue = 3
)

// String returns the SMI label, or FakeStatusValue(n) for an unrecognized value n.
func (v FakeStatusValue) String() string {
	switch v {
	case FakeStatusValueUp:
		return "up"
	case FakeStatusValueDown:
		return "down"
	case FakeStatusValueTesting:
		return "testing"
	}

	return fmt.Sprintf("FakeStatusValue(%d)", v)
}

// FakeCapabilities names the bit positions of the SMI BITS type FakeCapabilities.
// Pass one to [snmp.BitSet.Has] on a value of this type.
// A named BITS convention. Bit positions follow declaration order; the
// emitter names each one as an snmp.BitPos constant and decodes values of
// this type to an snmp.BitSet.
const (
	// FakeCapabilitiesAlpha is the position of the alpha bit.
	FakeCapabilitiesAlpha snmp.BitPos = 0
	// FakeCapabilitiesBeta is the position of the beta bit.
	FakeCapabilitiesBeta snmp.BitPos = 1
	// FakeCapabilitiesGamma is the position of the gamma bit.
	FakeCapabilitiesGamma snmp.BitPos = 2
)

// FakeScalarGet reads the SMIv2 scalar fakeScalar.
// It returns the session or decode error, or an error if the response is empty.
//
// A simple scalar.
func FakeScalarGet(ctx context.Context, sess snmp.Session) (int32, error) {
	vbs, err := sess.Get(ctx, []snmp.OID{snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 1, 0)})
	if err != nil {
		return 0, err
	}

	if len(vbs) == 0 {
		return 0, errs.Msg("empty Get response for fakeScalar")
	}

	return func(vb snmp.VarBind) (int32, error) {
		return snmp.DecodeInt32(vb)
	}(vbs[0])
}

// FakeStatusGet reads the SMIv2 scalar fakeStatus.
// It returns the session or decode error, or an error if the response is empty.
//
// An enum-typed scalar.
func FakeStatusGet(ctx context.Context, sess snmp.Session) (FakeStatusValue, error) {
	vbs, err := sess.Get(ctx, []snmp.OID{snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 2, 0)})
	if err != nil {
		return FakeStatusValue(0), err
	}

	if len(vbs) == 0 {
		return FakeStatusValue(0), errs.Msg("empty Get response for fakeStatus")
	}

	return func(vb snmp.VarBind) (FakeStatusValue, error) {
		v, err := snmp.DecodeInt32(vb)
		if err != nil {
			return FakeStatusValue(0), err
		}
		return FakeStatusValue(v), nil
	}(vbs[0])
}

// FakeStackLastChangeGet reads the SMIv2 scalar fakeStackLastChange.
// It returns the session or decode error, or an error if the response is empty.
//
// Scalar change indicator covering fakeStackTable. Bound by the
// name-prefix structural rule, not by per-row discovery.
func FakeStackLastChangeGet(ctx context.Context, sess snmp.Session) (uint32, error) {
	vbs, err := sess.Get(ctx, []snmp.OID{snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 5, 0)})
	if err != nil {
		return 0, err
	}

	if len(vbs) == 0 {
		return 0, errs.Msg("empty Get response for fakeStackLastChange")
	}

	return func(vb snmp.VarBind) (uint32, error) {
		return snmp.DecodeUint32(vb)
	}(vbs[0])
}

// FakeCapsGet reads the SMIv2 scalar fakeCaps.
// It returns the session or decode error, or an error if the response is empty.
//
// A BITS-typed scalar.
func FakeCapsGet(ctx context.Context, sess snmp.Session) (snmp.BitSet, error) {
	vbs, err := sess.Get(ctx, []snmp.OID{snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 6, 0)})
	if err != nil {
		return snmp.BitSet{}, err
	}

	if len(vbs) == 0 {
		return snmp.BitSet{}, errs.Msg("empty Get response for fakeCaps")
	}

	return func(vb snmp.VarBind) (snmp.BitSet, error) {
		return snmp.DecodeBitSet(vb)
	}(vbs[0])
}

// FakeName is the column fakeName of table fakeTable.
// Name.
var FakeName = snmp.NewColumn[string](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 2), snmp.KindOctetString, func(vb snmp.VarBind) (string, error) {
	return snmp.DecodeDisplayString(vb)
})

// FakeMac is the column fakeMac of table fakeTable.
// MAC address.
var FakeMac = snmp.NewColumn[net.HardwareAddr](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 3), snmp.KindOctetString, func(vb snmp.VarBind) (net.HardwareAddr, error) {
	return snmp.DecodeMacAddress(vb)
})

// FakeOctets is the column fakeOctets of table fakeTable.
// Counter.
var FakeOctets = snmp.NewColumn[uint64](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 4), snmp.KindCounter64, func(vb snmp.VarBind) (uint64, error) {
	return snmp.DecodeUint64(vb)
})

// FakeLastChange is the column fakeLastChange of table fakeTable.
// Per-row change indicator. The name-suffix heuristic classifies this
// column as TierIndicator at codegen time and structural discovery binds
// it to fakeTable.
var FakeLastChange = snmp.NewColumn[uint32](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 5), snmp.KindTimeTicks, func(vb snmp.VarBind) (uint32, error) {
	return snmp.DecodeUint32(vb)
})

// FakeFlags is the column fakeFlags of table fakeTable.
// A BITS-typed column. Covers the row-struct, watch- equality, and
// observation paths for set-valued columns.
var FakeFlags = snmp.NewColumn[snmp.BitSet](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 6), snmp.KindOctetString, func(vb snmp.VarBind) (snmp.BitSet, error) {
	return snmp.DecodeBitSet(vb)
})

// FakeTableRow is one row of fakeTable. Index carries the OID
// suffix beyond the table-entry prefix; the remaining fields are
// populated only for columns the caller passed to Walk(). Use
// [FakeTableRow.Observed] to tell a reported zero from a column the
// agent never answered.
// The zero value has no observed columns. Concurrent reads are safe;
// callers must synchronize mutation of the row or its referenced data.
type FakeTableRow struct {
	Index          snmp.OID
	FakeName       string
	FakeMac        net.HardwareAddr
	FakeOctets     uint64
	FakeLastChange uint32
	FakeFlags      snmp.BitSet

	// observed carries one bit per column of this table, in
	// column-OID order, set when the walk decoded a value for
	// that column on this row.
	observed [1]uint64
}

// Observed reports whether col returned a value for this row. A column
// the agent answered reads true even when the answer was zero or empty;
// a column that was requested but never landed, one that was not passed
// to Walk, and any column of another table all read false.
func (r FakeTableRow) Observed(col snmp.AnyColumn) bool {
	switch col.Key() {
	case FakeName.Key():
		return r.observed[0]&(1<<0) != 0
	case FakeMac.Key():
		return r.observed[0]&(1<<1) != 0
	case FakeOctets.Key():
		return r.observed[0]&(1<<2) != 0
	case FakeLastChange.Key():
		return r.observed[0]&(1<<3) != 0
	case FakeFlags.Key():
		return r.observed[0]&(1<<4) != 0
	}

	return false
}

// FakeTableWalker streams selected columns of fakeTable.
// The zero value is not usable; construct via FakeTable.Walk(ctx, sess, cols...).
// Iteration is single-use and single-consumer; Close and Err are safe concurrently.
type FakeTableWalker struct {
	rw   *snmp.ColumnWalker
	cols []snmp.AnyColumn
}

// Iter yields complete selected-column rows in numeric OID suffix order
// (192.168.0.2 precedes 192.168.0.10). It retains one batch per selected
// column. Breaking iteration stops retrieval. A decode error omits the
// failing row and later rows; already delivered rows remain valid. Check Err.
func (tw *FakeTableWalker) Iter() iter.Seq2[snmp.OID, FakeTableRow] {
	return func(yield func(snmp.OID, FakeTableRow) bool) {
		for idx, cells := range tw.rw.Iter() {
			row := FakeTableRow{Index: idx}
			for _, cell := range cells {
				rv := cell.Value
				var derr error
				switch tw.cols[cell.Column].Key() {
				case FakeName.Key():
					vb, vbErr := rv.Decode()
					if vbErr != nil {
						derr = vbErr
					} else {
						dv, dErr := FakeName.Decode(vb)
						if dErr != nil {
							derr = dErr
						} else {
							row.FakeName = dv
							row.observed[0] |= 1 << 0
						}
					}
				case FakeMac.Key():
					vb, vbErr := rv.Decode()
					if vbErr != nil {
						derr = vbErr
					} else {
						dv, dErr := FakeMac.Decode(vb)
						if dErr != nil {
							derr = dErr
						} else {
							row.FakeMac = dv
							row.observed[0] |= 1 << 1
						}
					}
				case FakeOctets.Key():
					if v, okRaw := snmp.RawCounter64(rv); okRaw {
						row.FakeOctets = uint64(v)
						row.observed[0] |= 1 << 2
					} else {
						vb, vbErr := rv.Decode()
						if vbErr != nil {
							derr = vbErr
						} else {
							dv, dErr := FakeOctets.Decode(vb)
							if dErr != nil {
								derr = dErr
							} else {
								row.FakeOctets = dv
								row.observed[0] |= 1 << 2
							}
						}
					}
				case FakeLastChange.Key():
					if v, okRaw := snmp.RawTimeTicks(rv); okRaw {
						row.FakeLastChange = uint32(v)
						row.observed[0] |= 1 << 3
					} else {
						vb, vbErr := rv.Decode()
						if vbErr != nil {
							derr = vbErr
						} else {
							dv, dErr := FakeLastChange.Decode(vb)
							if dErr != nil {
								derr = dErr
							} else {
								row.FakeLastChange = dv
								row.observed[0] |= 1 << 3
							}
						}
					}
				case FakeFlags.Key():
					vb, vbErr := rv.Decode()
					if vbErr != nil {
						derr = vbErr
					} else {
						dv, dErr := FakeFlags.Decode(vb)
						if dErr != nil {
							derr = dErr
						} else {
							row.FakeFlags = dv
							row.observed[0] |= 1 << 4
						}
					}
				}
				if derr != nil {
					tw.rw.Fail(derr)
					return
				}
			}
			if !yield(idx, row) {
				return
			}
		}
	}
}

// Err returns the underlying walker's terminal error, or nil if
// the walk completed naturally.
func (tw *FakeTableWalker) Err() error {
	return tw.rw.Err()
}

// fakeTableT is the singleton type of FakeTable.
type fakeTableT struct{}

// FakeTable is the descriptor for the fakeTable table.
var FakeTable fakeTableT

// Close stops retrieval. It is idempotent and safe during iteration.
func (tw *FakeTableWalker) Close() {
	tw.rw.Close()
}

// Walk lazily retrieves only selected columns with bounded defaults.
// Rows are the union of selected values in numeric OID index order.
// No columns means no rows or requests. Duplicate selections are ignored.
// Unknown or foreign columns fail before I/O with [snmp.ErrForeignColumn].
func (t fakeTableT) Walk(ctx context.Context, sess snmp.Session, cols ...snmp.AnyColumn) *FakeTableWalker {
	return t.WalkWithOptions(ctx, sess, snmp.TableWalkOptions{}, cols...)
}

// WalkWithOptions is Walk with request sizing and per-call controls.
// SNMPv1 remains unsupported. Parent cancellation is an error; stopping iteration is successful.
func (fakeTableT) WalkWithOptions(ctx context.Context, sess snmp.Session, options snmp.TableWalkOptions, cols ...snmp.AnyColumn) *FakeTableWalker {
	seen := make(map[string]bool)
	var selected []snmp.AnyColumn
	var roots []snmp.OID
	for _, c := range cols {
		switch c.Key() {
		case FakeName.Key(), FakeMac.Key(), FakeOctets.Key(), FakeLastChange.Key(), FakeFlags.Key():
		default:
			w := snmp.WalkColumns(ctx, sess, nil, options)
			w.Fail(errs.Wrapf(snmp.ErrForeignColumn, "fakeTable.Walk: column %s", c.OID()))
			return &FakeTableWalker{rw: w}
		}
		if seen[c.Key()] {
			continue
		}
		seen[c.Key()] = true
		selected = append(selected, c)
		roots = append(roots, c.OID())
	}
	return &FakeTableWalker{
		cols: selected,
		rw:   snmp.WalkColumns(ctx, sess, roots, options),
	}
}

// decodeFakeTableRow decodes one row of FakeTable from the supplied
// VarBinds. Each VarBind's OID determines which row field it populates
// (via the column's last sub-id). VarBinds with unknown column-ids are
// ignored. Absent columns leave their field at its zero value.
func decodeFakeTableRow(idx snmp.OID, vbs []snmp.VarBind) (FakeTableRow, error) {
	var row FakeTableRow
	row.Index = idx

	for _, vb := range vbs {
		o := vb.GetHeader().OID
		if o.Len() == 0 {
			continue
		}
		entryLen := snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1).Len()
		if o.Len() <= entryLen {
			continue
		}
		colID := o.At(entryLen)
		switch colID {
		case 2:
			dv, derr := FakeName.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeName = dv
			row.observed[0] |= 1 << 0
		case 3:
			dv, derr := FakeMac.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeMac = dv
			row.observed[0] |= 1 << 1
		case 4:
			dv, derr := FakeOctets.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeOctets = dv
			row.observed[0] |= 1 << 2
		case 5:
			dv, derr := FakeLastChange.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeLastChange = dv
			row.observed[0] |= 1 << 3
		case 6:
			dv, derr := FakeFlags.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeFlags = dv
			row.observed[0] |= 1 << 4
		}
	}

	return row, nil
}

// equalFakeTableRow compares two FakeTableRow values for equality.
// Used by [snmp.Watcher] to compute ChangeKindModified emits. Field-by-
// field with the type-appropriate comparator (bytes.Equal for []byte,
// OID.Equal for OID, time.Time.Equal for time.Time, == for everything else).
func equalFakeTableRow(a FakeTableRow, b FakeTableRow) bool {
	return a.Index.Equal(b.Index) && a.observed == b.observed && a.FakeName == b.FakeName && bytes.Equal(a.FakeMac, b.FakeMac) && a.FakeOctets == b.FakeOctets && a.FakeLastChange == b.FakeLastChange && a.FakeFlags.Equal(b.FakeFlags)
}

// mergeFakeTableRow merges the values decoded from vbs into dst, leaving fields
// whose columns are not present in vbs unchanged. Used by [snmp.Watcher]
// to maintain per-row state under partial-column fetches (Counter-tier,
// Static-tier). Best-effort: individual VarBind decode failures are
// silently skipped rather than propagated, because partial-fetch ticks
// surface transient errors through [snmp.Watcher.LastTickErr] at the
// call-site granularity rather than per-VarBind.
func mergeFakeTableRow(dst *FakeTableRow, vbs []snmp.VarBind) {
	for _, vb := range vbs {
		o := vb.GetHeader().OID
		if o.Len() == 0 {
			continue
		}
		entryLen := snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1).Len()
		if o.Len() <= entryLen {
			continue
		}
		colID := o.At(entryLen)
		switch colID {
		case 2:
			dv, derr := FakeName.Decode(vb)
			if derr == nil {
				dst.FakeName = dv
				dst.observed[0] |= 1 << 0
			}
		case 3:
			dv, derr := FakeMac.Decode(vb)
			if derr == nil {
				dst.FakeMac = dv
				dst.observed[0] |= 1 << 1
			}
		case 4:
			dv, derr := FakeOctets.Decode(vb)
			if derr == nil {
				dst.FakeOctets = dv
				dst.observed[0] |= 1 << 2
			}
		case 5:
			dv, derr := FakeLastChange.Decode(vb)
			if derr == nil {
				dst.FakeLastChange = dv
				dst.observed[0] |= 1 << 3
			}
		case 6:
			dv, derr := FakeFlags.Decode(vb)
			if derr == nil {
				dst.FakeFlags = dv
				dst.observed[0] |= 1 << 4
			}
		}
	}
}

// FakeTableWatcher is a table-aware Watcher over FakeTable.
// The zero value is not usable; construct via FakeTable.Watch(ctx, sess, cols, opts...).
// Use a single iterator. The other methods may be called concurrently.
type FakeTableWatcher struct {
	w *snmp.Watcher[FakeTableRow]
}

// Iter returns the range-over-func view of the Watcher's event stream.
// See [snmp.Watcher.Iter] for the contract.
func (tw *FakeTableWatcher) Iter() iter.Seq2[snmp.OID, snmp.WatchEvent[FakeTableRow]] {
	return tw.w.Iter()
}

// Err returns the underlying Watcher's terminal error, or nil if it
// completed naturally. See [snmp.Watcher.Err].
func (tw *FakeTableWatcher) Err() error {
	return tw.w.Err()
}

// Close signals the Watcher's tick goroutine to terminate. Idempotent.
// See [snmp.Watcher.Close].
func (tw *FakeTableWatcher) Close() error {
	return tw.w.Close()
}

// Fallback reports whether the Watcher has transitioned to fallback
// mode. See [snmp.Watcher.Fallback].
func (tw *FakeTableWatcher) Fallback() bool {
	return tw.w.Fallback()
}

// LastTickErr returns the most-recent transient per-tick error.
// See [snmp.Watcher.LastTickErr].
func (tw *FakeTableWatcher) LastTickErr() error {
	return tw.w.LastTickErr()
}

// TableRoot returns the OID of the table this Watcher operates over.
func (tw *FakeTableWatcher) TableRoot() snmp.OID {
	return tw.w.TableRoot()
}

// Watch opens a long-lived watch on FakeTable.
//
// cols selects the columns whose values are reported on every emitted
// event. opts override cadence bounds, per-column tier classifications,
// fallback behavior, and other policy — see [snmp.WatchOption] for the
// full set.
//
// cols is a slice rather than variadic because opts is variadic and
// Go forbids two variadic parameters.
//
// Events emitted on this stream:
//   - ChangeKindAdded    — Row populated, Prev always nil.
//   - ChangeKindModified — Row is current state. Prev is nil unless
//     the caller passed [snmp.WithPrevRow]; when
//     set, Prev carries the previous Row.
//   - ChangeKindRemoved  — Row carries the last-known state at the
//     time the row disappeared. Prev is nil.
//
// The returned Watcher must be Closed when the caller is done; iteration
// exit alone does not free the underlying goroutine until Close.
//
// On validation failure (invalid cadence bounds, tier override of the
// indicator column, etc.) Watch returns a Watcher whose Err() returns
// the cause immediately; range loops exit without emitting events and
// Close is a no-op.
func (fakeTableT) Watch(ctx context.Context, sess snmp.Session, cols []snmp.AnyColumn, opts ...snmp.WatchOption) *FakeTableWatcher {
	allOpts := append([]snmp.WatchOption{snmp.WithTierLookup(ColumnTier)}, opts...)
	w, _ := snmp.NewWatcher[FakeTableRow](ctx, sess, FakeTableIndicator, cols, decodeFakeTableRow, equalFakeTableRow, mergeFakeTableRow, allOpts...)

	return &FakeTableWatcher{w: w}
}

// FakeStackName is the column fakeStackName of table fakeStackTable.
// Name.
var FakeStackName = snmp.NewColumn[string](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 4, 1, 2), snmp.KindOctetString, func(vb snmp.VarBind) (string, error) {
	return snmp.DecodeDisplayString(vb)
})

// FakeStackTableRow is one row of fakeStackTable. Index carries the OID
// suffix beyond the table-entry prefix; the remaining fields are
// populated only for columns the caller passed to Walk(). Use
// [FakeStackTableRow.Observed] to tell a reported zero from a column the
// agent never answered.
// The zero value has no observed columns. Concurrent reads are safe;
// callers must synchronize mutation of the row or its referenced data.
type FakeStackTableRow struct {
	Index         snmp.OID
	FakeStackName string

	// observed carries one bit per column of this table, in
	// column-OID order, set when the walk decoded a value for
	// that column on this row.
	observed [1]uint64
}

// Observed reports whether col returned a value for this row. A column
// the agent answered reads true even when the answer was zero or empty;
// a column that was requested but never landed, one that was not passed
// to Walk, and any column of another table all read false.
func (r FakeStackTableRow) Observed(col snmp.AnyColumn) bool {
	switch col.Key() {
	case FakeStackName.Key():
		return r.observed[0]&(1<<0) != 0
	}

	return false
}

// FakeStackTableWalker streams selected columns of fakeStackTable.
// The zero value is not usable; construct via FakeStackTable.Walk(ctx, sess, cols...).
// Iteration is single-use and single-consumer; Close and Err are safe concurrently.
type FakeStackTableWalker struct {
	rw   *snmp.ColumnWalker
	cols []snmp.AnyColumn
}

// Iter yields complete selected-column rows in numeric OID suffix order
// (192.168.0.2 precedes 192.168.0.10). It retains one batch per selected
// column. Breaking iteration stops retrieval. A decode error omits the
// failing row and later rows; already delivered rows remain valid. Check Err.
func (tw *FakeStackTableWalker) Iter() iter.Seq2[snmp.OID, FakeStackTableRow] {
	return func(yield func(snmp.OID, FakeStackTableRow) bool) {
		for idx, cells := range tw.rw.Iter() {
			row := FakeStackTableRow{Index: idx}
			for _, cell := range cells {
				rv := cell.Value
				var derr error
				switch tw.cols[cell.Column].Key() {
				case FakeStackName.Key():
					vb, vbErr := rv.Decode()
					if vbErr != nil {
						derr = vbErr
					} else {
						dv, dErr := FakeStackName.Decode(vb)
						if dErr != nil {
							derr = dErr
						} else {
							row.FakeStackName = dv
							row.observed[0] |= 1 << 0
						}
					}
				}
				if derr != nil {
					tw.rw.Fail(derr)
					return
				}
			}
			if !yield(idx, row) {
				return
			}
		}
	}
}

// Err returns the underlying walker's terminal error, or nil if
// the walk completed naturally.
func (tw *FakeStackTableWalker) Err() error {
	return tw.rw.Err()
}

// fakeStackTableT is the singleton type of FakeStackTable.
type fakeStackTableT struct{}

// FakeStackTable is the descriptor for the fakeStackTable table.
var FakeStackTable fakeStackTableT

// Close stops retrieval. It is idempotent and safe during iteration.
func (tw *FakeStackTableWalker) Close() {
	tw.rw.Close()
}

// Walk lazily retrieves only selected columns with bounded defaults.
// Rows are the union of selected values in numeric OID index order.
// No columns means no rows or requests. Duplicate selections are ignored.
// Unknown or foreign columns fail before I/O with [snmp.ErrForeignColumn].
func (t fakeStackTableT) Walk(ctx context.Context, sess snmp.Session, cols ...snmp.AnyColumn) *FakeStackTableWalker {
	return t.WalkWithOptions(ctx, sess, snmp.TableWalkOptions{}, cols...)
}

// WalkWithOptions is Walk with request sizing and per-call controls.
// SNMPv1 remains unsupported. Parent cancellation is an error; stopping iteration is successful.
func (fakeStackTableT) WalkWithOptions(ctx context.Context, sess snmp.Session, options snmp.TableWalkOptions, cols ...snmp.AnyColumn) *FakeStackTableWalker {
	seen := make(map[string]bool)
	var selected []snmp.AnyColumn
	var roots []snmp.OID
	for _, c := range cols {
		switch c.Key() {
		case FakeStackName.Key():
		default:
			w := snmp.WalkColumns(ctx, sess, nil, options)
			w.Fail(errs.Wrapf(snmp.ErrForeignColumn, "fakeStackTable.Walk: column %s", c.OID()))
			return &FakeStackTableWalker{rw: w}
		}
		if seen[c.Key()] {
			continue
		}
		seen[c.Key()] = true
		selected = append(selected, c)
		roots = append(roots, c.OID())
	}
	return &FakeStackTableWalker{
		cols: selected,
		rw:   snmp.WalkColumns(ctx, sess, roots, options),
	}
}

// decodeFakeStackTableRow decodes one row of FakeStackTable from the supplied
// VarBinds. Each VarBind's OID determines which row field it populates
// (via the column's last sub-id). VarBinds with unknown column-ids are
// ignored. Absent columns leave their field at its zero value.
func decodeFakeStackTableRow(idx snmp.OID, vbs []snmp.VarBind) (FakeStackTableRow, error) {
	var row FakeStackTableRow
	row.Index = idx

	for _, vb := range vbs {
		o := vb.GetHeader().OID
		if o.Len() == 0 {
			continue
		}
		entryLen := snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 4, 1).Len()
		if o.Len() <= entryLen {
			continue
		}
		colID := o.At(entryLen)
		switch colID {
		case 2:
			dv, derr := FakeStackName.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeStackName = dv
			row.observed[0] |= 1 << 0
		}
	}

	return row, nil
}

// equalFakeStackTableRow compares two FakeStackTableRow values for equality.
// Used by [snmp.Watcher] to compute ChangeKindModified emits. Field-by-
// field with the type-appropriate comparator (bytes.Equal for []byte,
// OID.Equal for OID, time.Time.Equal for time.Time, == for everything else).
func equalFakeStackTableRow(a FakeStackTableRow, b FakeStackTableRow) bool {
	return a.Index.Equal(b.Index) && a.observed == b.observed && a.FakeStackName == b.FakeStackName
}

// mergeFakeStackTableRow merges the values decoded from vbs into dst, leaving fields
// whose columns are not present in vbs unchanged. Used by [snmp.Watcher]
// to maintain per-row state under partial-column fetches (Counter-tier,
// Static-tier). Best-effort: individual VarBind decode failures are
// silently skipped rather than propagated, because partial-fetch ticks
// surface transient errors through [snmp.Watcher.LastTickErr] at the
// call-site granularity rather than per-VarBind.
func mergeFakeStackTableRow(dst *FakeStackTableRow, vbs []snmp.VarBind) {
	for _, vb := range vbs {
		o := vb.GetHeader().OID
		if o.Len() == 0 {
			continue
		}
		entryLen := snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 4, 1).Len()
		if o.Len() <= entryLen {
			continue
		}
		colID := o.At(entryLen)
		switch colID {
		case 2:
			dv, derr := FakeStackName.Decode(vb)
			if derr == nil {
				dst.FakeStackName = dv
				dst.observed[0] |= 1 << 0
			}
		}
	}
}

// FakeStackTableWatcher is a table-aware Watcher over FakeStackTable.
// The zero value is not usable; construct via FakeStackTable.Watch(ctx, sess, cols, opts...).
// Use a single iterator. The other methods may be called concurrently.
type FakeStackTableWatcher struct {
	w *snmp.Watcher[FakeStackTableRow]
}

// Iter returns the range-over-func view of the Watcher's event stream.
// See [snmp.Watcher.Iter] for the contract.
func (tw *FakeStackTableWatcher) Iter() iter.Seq2[snmp.OID, snmp.WatchEvent[FakeStackTableRow]] {
	return tw.w.Iter()
}

// Err returns the underlying Watcher's terminal error, or nil if it
// completed naturally. See [snmp.Watcher.Err].
func (tw *FakeStackTableWatcher) Err() error {
	return tw.w.Err()
}

// Close signals the Watcher's tick goroutine to terminate. Idempotent.
// See [snmp.Watcher.Close].
func (tw *FakeStackTableWatcher) Close() error {
	return tw.w.Close()
}

// Fallback reports whether the Watcher has transitioned to fallback
// mode. See [snmp.Watcher.Fallback].
func (tw *FakeStackTableWatcher) Fallback() bool {
	return tw.w.Fallback()
}

// LastTickErr returns the most-recent transient per-tick error.
// See [snmp.Watcher.LastTickErr].
func (tw *FakeStackTableWatcher) LastTickErr() error {
	return tw.w.LastTickErr()
}

// TableRoot returns the OID of the table this Watcher operates over.
func (tw *FakeStackTableWatcher) TableRoot() snmp.OID {
	return tw.w.TableRoot()
}

// Watch opens a long-lived watch on FakeStackTable.
//
// cols selects the columns whose values are reported on every emitted
// event. opts override cadence bounds, per-column tier classifications,
// fallback behavior, and other policy — see [snmp.WatchOption] for the
// full set.
//
// cols is a slice rather than variadic because opts is variadic and
// Go forbids two variadic parameters.
//
// Events emitted on this stream:
//   - ChangeKindAdded    — Row populated, Prev always nil.
//   - ChangeKindModified — Row is current state. Prev is nil unless
//     the caller passed [snmp.WithPrevRow]; when
//     set, Prev carries the previous Row.
//   - ChangeKindRemoved  — Row carries the last-known state at the
//     time the row disappeared. Prev is nil.
//
// The returned Watcher must be Closed when the caller is done; iteration
// exit alone does not free the underlying goroutine until Close.
//
// On validation failure (invalid cadence bounds, tier override of the
// indicator column, etc.) Watch returns a Watcher whose Err() returns
// the cause immediately; range loops exit without emitting events and
// Close is a no-op.
func (fakeStackTableT) Watch(ctx context.Context, sess snmp.Session, cols []snmp.AnyColumn, opts ...snmp.WatchOption) *FakeStackTableWatcher {
	allOpts := append([]snmp.WatchOption{snmp.WithTierLookup(ColumnTier)}, opts...)
	w, _ := snmp.NewWatcher[FakeStackTableRow](ctx, sess, FakeStackTableIndicator, cols, decodeFakeStackTableRow, equalFakeStackTableRow, mergeFakeStackTableRow, allOpts...)

	return &FakeStackTableWatcher{w: w}
}

// fAKEMIBOIDDispatch maps column wire keys ([snmp.OID.WireKey]) to their
// typed AnyColumn for fast
// lookup during table-walk decoding. Per-MIB-module — no global
// registry; cross-package callers should consult OIDDispatch().
var fAKEMIBOIDDispatch = map[string]snmp.AnyColumn{
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 2).WireKey(): FakeName,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 3).WireKey(): FakeMac,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 4).WireKey(): FakeOctets,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 5).WireKey(): FakeLastChange,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 6).WireKey(): FakeFlags,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 4, 1, 2).WireKey(): FakeStackName,
}

// OIDDispatch returns a shallow copy of the package's wire-key →
// AnyColumn map. The copy isolates callers from accidental mutation
// of the package-internal map.
func OIDDispatch() map[string]snmp.AnyColumn {
	out := make(map[string]snmp.AnyColumn, len(fAKEMIBOIDDispatch))
	for k, v := range fAKEMIBOIDDispatch {
		out[k] = v
	}
	return out
}

// fAKEMIBColumnTiers maps column wire keys ([snmp.OID.WireKey]) to their
// snmp.Tier classification.
// Tier classification drives the Watcher's scheduler — counters fire
// on their own cadence, state columns refresh on indicator advance,
// and indicator columns drive the change-detection probe itself.
// See snmp.Tier and snmp.Watcher for the consumption contract.
var fAKEMIBColumnTiers = map[string]snmp.Tier{
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 2).WireKey(): snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 3).WireKey(): snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 4).WireKey(): snmp.TierCounter,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 5).WireKey(): snmp.TierIndicator,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 6).WireKey(): snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 4, 1, 2).WireKey(): snmp.TierState,
}

// ColumnTier returns the codegen-classified [snmp.Tier] for col, or
// snmp.TierUnknown when col's OID is not known to this package. The
// generated Watch methods install this function via
// [snmp.WithTierLookup]; returning TierUnknown lets the runtime fall
// back to its wire-Kind heuristic for columns this package does not
// classify. Caller overrides via [snmp.WithColumnTier] still win.
func ColumnTier(col snmp.AnyColumn) snmp.Tier {
	if col == nil {
		return snmp.TierUnknown
	}
	t, ok := fAKEMIBColumnTiers[col.Key()]
	if !ok {
		return snmp.TierUnknown
	}
	return t
}

// FakeTableIndicator is the per-row change indicator for fakeTable.
// The Watcher probes the indicator column on each tick and only
// re-fetches a row's other state-tier columns when the row's
// indicator value advances. See [snmp.NewPerRowIndicator] and
// [snmp.Watcher] for the consumption contract.
// Discovered by mibgen structural rule: per-row column name matches indicator-suffix heuristic.
var FakeTableIndicator = snmp.MustChangeIndicator(snmp.NewPerRowIndicator(FakeLastChange, snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3)))

// FakeStackTableIndicator is the scalar change indicator for fakeStackTable.
// The Watcher Gets fakeStackLastChange on each tick; when the value
// advances the full table is walked and diffed against the snapshot.
// See [snmp.NewScalarIndicator] and [snmp.Watcher] for the contract.
// Discovered by mibgen structural rule: scalar named after the table plus an indicator suffix.
var FakeStackTableIndicator = snmp.MustChangeIndicator(snmp.NewScalarIndicator(snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 5), snmp.KindTimeTicks, []snmp.OID{snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 4)}))
