// Code generated by mibgen; DO NOT EDIT.
//
// Source MIB:    FAKE-MIB
// Source path:   testdata/mibs/FAKE-MIB.mib
// Source SHA-256: 9e9c53e06206fbb15d34337f2d3d29257ee048b53269d03456771297b23fb8e4
//
// Regenerate with `go generate .` at the repository root.

// Package fakemib binds the SMI objects declared by FAKE-MIB.
package fakemib

import (
	"bytes"
	"context"
	"iter"
	"net"
	"net/netip"

	errs "go.aledante.io/FlowSeer/src/common/errs"
	snmp "go.aledante.io/FlowSeer/src/protocol/snmp"
	fakekeysmib "go.aledante.io/FlowSeer/src/protocol/snmp/cmd/mibgen/testdata/golden/fakekeysmib"
)

// FakeModeValue is the SMI enum fakeMode (inline).
// A one-member enum column.
//
// Unknown values are valid; reads are safe concurrently.
type FakeModeValue int32

const (
	// FakeModeValueOnly is only.
	FakeModeValueOnly FakeModeValue = 1
)

var (
	fakeModeValueValues = []int32{1}
	fakeModeValueNames  = []string{"only"}
)

// String returns the SMI label, or FakeModeValue(n) for an unknown value.
func (v FakeModeValue) String() string {
	return snmp.EnumString(int32(v), "FakeModeValue", fakeModeValueValues, fakeModeValueNames)
}

// FakeStatusValue is the SMI enum fakeStatus (inline).
// An enum-typed scalar.
//
// Unknown values are valid; reads are safe concurrently.
type FakeStatusValue int32

const (
	// FakeStatusValueUp is up.
	FakeStatusValueUp FakeStatusValue = 1
	// FakeStatusValueDown is down.
	FakeStatusValueDown FakeStatusValue = 2
	// FakeStatusValueTesting is testing.
	FakeStatusValueTesting FakeStatusValue = 3
)

var (
	fakeStatusValueValues = []int32{1, 2, 3}
	fakeStatusValueNames  = []string{"up", "down", "testing"}
)

// String returns the SMI label, or FakeStatusValue(n) for an unknown value.
func (v FakeStatusValue) String() string {
	return snmp.EnumString(int32(v), "FakeStatusValue", fakeStatusValueValues, fakeStatusValueNames)
}

// FakeCapabilities names the bit positions of the SMI BITS type FakeCapabilities.
// Pass one to [snmp.BitSet.Has] on a value of this type.
// A named BITS convention. Bit positions follow declaration order; the
// emitter names each one as an snmp.BitPos constant and decodes values of
// this type to an snmp.BitSet.
const (
	// FakeCapabilitiesAlpha is the position of the alpha bit.
	FakeCapabilitiesAlpha snmp.BitPos = 0
	// FakeCapabilitiesBeta is the position of the beta bit.
	FakeCapabilitiesBeta snmp.BitPos = 1
	// FakeCapabilitiesGamma is the position of the gamma bit.
	FakeCapabilitiesGamma snmp.BitPos = 2
)

// FakeScalarGet reads the SMIv2 scalar fakeScalar.
// It returns the session or decode error, or an error if the response is empty.
//
// A simple scalar.
func FakeScalarGet(ctx context.Context, sess snmp.Session) (int32, error) {
	vbs, err := sess.Get(ctx, []snmp.OID{snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 1, 0)})
	if err != nil {
		return 0, err
	}

	if len(vbs) == 0 {
		return 0, errs.Msg("empty Get response for fakeScalar")
	}

	return snmp.DecodeInt32(vbs[0])
}

// FakeStatusGet reads the SMIv2 scalar fakeStatus.
// It returns the session or decode error, or an error if the response is empty.
//
// An enum-typed scalar.
func FakeStatusGet(ctx context.Context, sess snmp.Session) (FakeStatusValue, error) {
	vbs, err := sess.Get(ctx, []snmp.OID{snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 2, 0)})
	if err != nil {
		return FakeStatusValue(0), err
	}

	if len(vbs) == 0 {
		return FakeStatusValue(0), errs.Msg("empty Get response for fakeStatus")
	}

	return func(vb snmp.VarBind) (FakeStatusValue, error) {
		v, err := snmp.DecodeInt32(vb)
		if err != nil {
			return FakeStatusValue(0), err
		}
		return FakeStatusValue(v), nil
	}(vbs[0])
}

// FakeStackLastChangeGet reads the SMIv2 scalar fakeStackLastChange.
// It returns the session or decode error, or an error if the response is empty.
//
// Scalar change indicator covering fakeStackTable. Bound by the
// name-prefix structural rule, not by per-row discovery.
func FakeStackLastChangeGet(ctx context.Context, sess snmp.Session) (uint32, error) {
	vbs, err := sess.Get(ctx, []snmp.OID{snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 5, 0)})
	if err != nil {
		return 0, err
	}

	if len(vbs) == 0 {
		return 0, errs.Msg("empty Get response for fakeStackLastChange")
	}

	return snmp.DecodeUint32(vbs[0])
}

// FakeCapsGet reads the SMIv2 scalar fakeCaps.
// It returns the session or decode error, or an error if the response is empty.
//
// A BITS-typed scalar.
func FakeCapsGet(ctx context.Context, sess snmp.Session) (snmp.BitSet, error) {
	vbs, err := sess.Get(ctx, []snmp.OID{snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 6, 0)})
	if err != nil {
		return snmp.BitSet{}, err
	}

	if len(vbs) == 0 {
		return snmp.BitSet{}, errs.Msg("empty Get response for fakeCaps")
	}

	return snmp.DecodeBitSet(vbs[0])
}

// FakeLegacyMACGet reads the SMIv2 scalar fakeLegacyMac.
// It returns the session or decode error, or an error if the response is empty.
//
// An obsolete scalar with a natural textual-convention decoder.
//
// Deprecated: fakeLegacyMac is STATUS obsolete in FAKE-MIB.
func FakeLegacyMACGet(ctx context.Context, sess snmp.Session) (net.HardwareAddr, error) {
	vbs, err := sess.Get(ctx, []snmp.OID{snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 18, 0)})
	if err != nil {
		return nil, err
	}

	if len(vbs) == 0 {
		return nil, errs.Msg("empty Get response for fakeLegacyMac")
	}

	return snmp.DecodeMacAddress(vbs[0])
}

// FakeName is fakeName.
// Name.
var FakeName = snmp.NewTableColumn[string](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 2), snmp.KindOctetString, snmp.DecodeDisplayString, 0)

// FakeMAC is fakeMac.
// MAC address.
var FakeMAC = snmp.NewTableColumn[net.HardwareAddr](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 3), snmp.KindOctetString, snmp.DecodeMacAddress, 1)

// FakeOctets is fakeOctets.
// Counter.
var FakeOctets = snmp.NewFusedTableColumn[uint64](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 4), snmp.KindCounter64, snmp.DecodeUint64, snmp.RawCounter64, 2)

// FakeLastChange is fakeLastChange.
// Per-row change indicator. The name-suffix heuristic classifies this
// column as TierIndicator at codegen time and structural discovery binds
// it to fakeTable.
var FakeLastChange = snmp.NewFusedTableColumn[uint32](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 5), snmp.KindTimeTicks, snmp.DecodeUint32, snmp.RawTimeTicks, 3)

// FakeFlags is fakeFlags.
// A BITS-typed column. Covers the row-struct, watch- equality, and
// observation paths for set-valued columns.
var FakeFlags = snmp.NewTableColumn[snmp.BitSet](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 6), snmp.KindOctetString, snmp.DecodeBitSet, 4)

// FakeRef is fakeRef.
// A reference to a row of fakeKeyTable in FAKE-KEYS-MIB. Covers the
// cross-package keyed-convention path and its degraded form when that
// module is not configured.
var FakeRef = snmp.NewFusedTableColumn[fakekeysmib.FakeKeyIndex](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 7), snmp.KindInteger32, func(vb snmp.VarBind) (fakekeysmib.FakeKeyIndex, error) {
	v, err := snmp.DecodeInt32(vb)
	if err != nil {
		return fakekeysmib.FakeKeyIndex(0), err
	}
	return fakekeysmib.FakeKeyIndex(v), nil
}, snmp.RawInteger32As[fakekeysmib.FakeKeyIndex], 5)

// FakeMode is fakeMode.
// A one-member enum column.
var FakeMode = snmp.NewFusedTableColumn[FakeModeValue](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 8), snmp.KindInteger32, func(vb snmp.VarBind) (FakeModeValue, error) {
	v, err := snmp.DecodeInt32(vb)
	if err != nil {
		return FakeModeValue(0), err
	}
	return FakeModeValue(v), nil
}, snmp.RawInteger32As[FakeModeValue], 6)

// FakeDeprecated is fakeDeprecated.
// A deprecated counter column.
//
// Deprecated: fakeDeprecated is STATUS deprecated in FAKE-MIB.
var (
	FakeDeprecated   = snmp.NewFusedTableColumn[uint32](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 9), snmp.KindCounter32, snmp.DecodeUint32, snmp.RawCounter32, 7)
	fakeTableColumns = []snmp.AnyColumn{FakeName, FakeMAC, FakeOctets, FakeLastChange, FakeFlags, FakeRef, FakeMode, FakeDeprecated}
)

// FakeTableKey is the decoded INDEX of one fakeTable row, one field per
// part in INDEX order. It is comparable and usable as a map key.
type FakeTableKey struct {
	FakeIndex int32
}

var fakeTableIndexShapes = []snmp.IndexShape{{Kind: snmp.IndexInteger}}

// decodeFakeTableKey decodes the instance suffix of one fakeTable row. ok is false
// when the suffix does not match the declared INDEX; the key is then zero.
func decodeFakeTableKey(idx snmp.OID) (FakeTableKey, bool) {
	var parts [1]snmp.IndexValue
	if !snmp.DecodeIndexInto(parts[:], idx, fakeTableIndexShapes) {
		return FakeTableKey{}, false
	}
	return FakeTableKey{FakeIndex: int32(parts[0].Integer)}, true
}

// FakeTableRow is one table row; KeyValid reports index validity, use Observed for field presence, and concurrent reads are safe.
type FakeTableRow struct {
	Key            FakeTableKey
	keyValid       bool
	FakeName       string
	FakeMAC        net.HardwareAddr
	FakeOctets     uint64
	FakeLastChange uint32
	FakeFlags      snmp.BitSet
	FakeRef        fakekeysmib.FakeKeyIndex
	FakeMode       FakeModeValue
	FakeDeprecated uint32
	observed       [1]uint64
}

// KeyValid reports whether Key decoded from the row index.
func (r FakeTableRow) KeyValid() bool {
	return r.keyValid
}

// Observed reports whether col supplied this row field, including a zero value.
func (r FakeTableRow) Observed(col snmp.AnyColumn) bool {
	return snmp.ColumnObserved(r.observed[:], fakeTableColumns, col)
}

// FakeTableWalker streams one table walk; its zero value is unusable, and Err/Close are safe concurrently.
type FakeTableWalker struct {
	snmp.TableWalker[FakeTableRow]
}
type fakeTableT struct {
	snmp.Table[FakeTableRow, *FakeTableWalker]
}

// FakeTable is the descriptor for the fakeTable table.
var FakeTable = fakeTableT{Table: snmp.NewTable("fakeTable", fakeTableColumns, func(idx snmp.OID, row *FakeTableRow) {
	row.Key, row.keyValid = decodeFakeTableKey(idx)
}, func(row *FakeTableRow, ordinal int, rv snmp.RawVarBind) error {
	switch ordinal {
	case 0:
		return snmp.DecodeColumn(rv, FakeName, &row.FakeName, row.observed[:])
	case 1:
		return snmp.DecodeColumn(rv, FakeMAC, &row.FakeMAC, row.observed[:])
	case 2:
		return snmp.DecodeColumn(rv, FakeOctets, &row.FakeOctets, row.observed[:])
	case 3:
		return snmp.DecodeColumn(rv, FakeLastChange, &row.FakeLastChange, row.observed[:])
	case 4:
		return snmp.DecodeColumn(rv, FakeFlags, &row.FakeFlags, row.observed[:])
	case 5:
		return snmp.DecodeColumn(rv, FakeRef, &row.FakeRef, row.observed[:])
	case 6:
		return snmp.DecodeColumn(rv, FakeMode, &row.FakeMode, row.observed[:])
	case 7:
		return snmp.DecodeColumn(rv, FakeDeprecated, &row.FakeDeprecated, row.observed[:])
	}
	return nil
}, func(tw snmp.TableWalker[FakeTableRow]) *FakeTableWalker {
	return &FakeTableWalker{TableWalker: tw}
})}

// Descriptor returns the table identity, change indicator, and row-key type.
func (fakeTableT) Descriptor() snmp.TableDescriptor {
	return snmp.TableDescriptor{
		Indicator: FakeTableIndicator,
		KeyType:   "FakeTableKey",
		Root:      snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3),
	}
}

// decodeFakeTableRow decodes one row of FakeTable from the supplied
// VarBinds. Each VarBind's OID determines which row field it populates
// (via the column's last sub-id). VarBinds with unknown column-ids are
// ignored. Absent columns leave their field at its zero value.
func decodeFakeTableRow(idx snmp.OID, vbs []snmp.VarBind) (FakeTableRow, error) {
	var row FakeTableRow
	row.Key, row.keyValid = decodeFakeTableKey(idx)

	for _, vb := range vbs {
		o := vb.GetHeader().OID
		if o.Len() == 0 {
			continue
		}
		entryLen := snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1).Len()
		if o.Len() <= entryLen {
			continue
		}
		colID := o.At(entryLen)
		switch colID {
		case 2:
			dv, derr := FakeName.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeName = dv
			row.observed[0] |= 1 << 0
		case 3:
			dv, derr := FakeMAC.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeMAC = dv
			row.observed[0] |= 1 << 1
		case 4:
			dv, derr := FakeOctets.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeOctets = dv
			row.observed[0] |= 1 << 2
		case 5:
			dv, derr := FakeLastChange.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeLastChange = dv
			row.observed[0] |= 1 << 3
		case 6:
			dv, derr := FakeFlags.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeFlags = dv
			row.observed[0] |= 1 << 4
		case 7:
			dv, derr := FakeRef.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeRef = dv
			row.observed[0] |= 1 << 5
		case 8:
			dv, derr := FakeMode.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeMode = dv
			row.observed[0] |= 1 << 6
		case 9:
			dv, derr := FakeDeprecated.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeDeprecated = dv
			row.observed[0] |= 1 << 7
		}
	}

	return row, nil
}

// equalFakeTableRow compares two FakeTableRow values for equality.
// Used by [snmp.Watcher] to compute ChangeKindModified emits. Field-by-
// field with the type-appropriate comparator (bytes.Equal for []byte,
// OID.Equal for OID, time.Time.Equal for time.Time, == for everything else).
func equalFakeTableRow(a FakeTableRow, b FakeTableRow) bool {
	return a.Key == b.Key && a.keyValid == b.keyValid && a.observed == b.observed && a.FakeName == b.FakeName && bytes.Equal(a.FakeMAC, b.FakeMAC) && a.FakeOctets == b.FakeOctets && a.FakeLastChange == b.FakeLastChange && a.FakeFlags.Equal(b.FakeFlags) && a.FakeRef == b.FakeRef && a.FakeMode == b.FakeMode && a.FakeDeprecated == b.FakeDeprecated
}

// mergeFakeTableRow merges the values decoded from vbs into dst, leaving fields
// whose columns are not present in vbs unchanged. Used by [snmp.Watcher]
// to maintain per-row state under partial-column fetches (Counter-tier,
// Static-tier). Best-effort: individual VarBind decode failures are
// silently skipped rather than propagated, because partial-fetch ticks
// surface transient errors through [snmp.Watcher.LastTickErr] at the
// call-site granularity rather than per-VarBind.
func mergeFakeTableRow(dst *FakeTableRow, vbs []snmp.VarBind) {
	for _, vb := range vbs {
		o := vb.GetHeader().OID
		if o.Len() == 0 {
			continue
		}
		entryLen := snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1).Len()
		if o.Len() <= entryLen {
			continue
		}
		colID := o.At(entryLen)
		switch colID {
		case 2:
			dv, derr := FakeName.Decode(vb)
			if derr == nil {
				dst.FakeName = dv
				dst.observed[0] |= 1 << 0
			}
		case 3:
			dv, derr := FakeMAC.Decode(vb)
			if derr == nil {
				dst.FakeMAC = dv
				dst.observed[0] |= 1 << 1
			}
		case 4:
			dv, derr := FakeOctets.Decode(vb)
			if derr == nil {
				dst.FakeOctets = dv
				dst.observed[0] |= 1 << 2
			}
		case 5:
			dv, derr := FakeLastChange.Decode(vb)
			if derr == nil {
				dst.FakeLastChange = dv
				dst.observed[0] |= 1 << 3
			}
		case 6:
			dv, derr := FakeFlags.Decode(vb)
			if derr == nil {
				dst.FakeFlags = dv
				dst.observed[0] |= 1 << 4
			}
		case 7:
			dv, derr := FakeRef.Decode(vb)
			if derr == nil {
				dst.FakeRef = dv
				dst.observed[0] |= 1 << 5
			}
		case 8:
			dv, derr := FakeMode.Decode(vb)
			if derr == nil {
				dst.FakeMode = dv
				dst.observed[0] |= 1 << 6
			}
		case 9:
			dv, derr := FakeDeprecated.Decode(vb)
			if derr == nil {
				dst.FakeDeprecated = dv
				dst.observed[0] |= 1 << 7
			}
		}
	}
}

// FakeTableWatcher is a table-aware Watcher over FakeTable.
// The zero value is not usable; construct via FakeTable.Watch(ctx, sess, cols, opts...).
// Use a single iterator. The other methods may be called concurrently.
type FakeTableWatcher struct {
	w *snmp.Watcher[FakeTableRow]
}

// Iter returns the range-over-func view of the Watcher's event stream.
// See [snmp.Watcher.Iter] for the contract.
func (tw *FakeTableWatcher) Iter() iter.Seq2[snmp.OID, snmp.WatchEvent[FakeTableRow]] {
	return tw.w.Iter()
}

// Err returns the underlying Watcher's terminal error, or nil if it
// completed naturally. See [snmp.Watcher.Err].
func (tw *FakeTableWatcher) Err() error {
	return tw.w.Err()
}

// Close signals the Watcher's tick goroutine to terminate. Idempotent.
// See [snmp.Watcher.Close].
func (tw *FakeTableWatcher) Close() error {
	return tw.w.Close()
}

// Fallback reports whether the Watcher has transitioned to fallback
// mode. See [snmp.Watcher.Fallback].
func (tw *FakeTableWatcher) Fallback() bool {
	return tw.w.Fallback()
}

// LastTickErr returns the most-recent transient per-tick error.
// See [snmp.Watcher.LastTickErr].
func (tw *FakeTableWatcher) LastTickErr() error {
	return tw.w.LastTickErr()
}

// TableRoot returns the OID of the table this Watcher operates over.
func (tw *FakeTableWatcher) TableRoot() snmp.OID {
	return tw.w.TableRoot()
}

// Watch opens a long-lived watch on FakeTable.
//
// cols selects the columns whose values are reported on every emitted
// event. opts override cadence bounds, per-column tier classifications,
// fallback behavior, and other policy — see [snmp.WatchOption] for the
// full set.
//
// cols is a slice rather than variadic because opts is variadic and
// Go forbids two variadic parameters.
//
// Events emitted on this stream:
//   - ChangeKindAdded    — Row populated, Prev always nil.
//   - ChangeKindModified — Row is current state. Prev is nil unless
//     the caller passed [snmp.WithPrevRow]; when
//     set, Prev carries the previous Row.
//   - ChangeKindRemoved  — Row carries the last-known state at the
//     time the row disappeared. Prev is nil.
//
// The returned Watcher must be Closed when the caller is done; iteration
// exit alone does not free the underlying goroutine until Close.
//
// On validation failure (invalid cadence bounds, tier override of the
// indicator column, etc.) Watch returns a Watcher whose Err() returns
// the cause immediately; range loops exit without emitting events and
// Close is a no-op.
func (fakeTableT) Watch(ctx context.Context, sess snmp.Session, cols []snmp.AnyColumn, opts ...snmp.WatchOption) *FakeTableWatcher {
	allOpts := append([]snmp.WatchOption{snmp.WithTierLookup(ColumnTier)}, opts...)
	w, _ := snmp.NewWatcher[FakeTableRow](ctx, sess, FakeTableIndicator, cols, decodeFakeTableRow, equalFakeTableRow, mergeFakeTableRow, allOpts...)

	return &FakeTableWatcher{w: w}
}

// FakeStackName is fakeStackName.
// Name.
var (
	FakeStackName         = snmp.NewTableColumn[string](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 4, 1, 2), snmp.KindOctetString, snmp.DecodeDisplayString, 0)
	fakeStackTableColumns = []snmp.AnyColumn{FakeStackName}
)

// FakeStackTableKey is the decoded INDEX of one fakeStackTable row, one field per
// part in INDEX order. It is comparable and usable as a map key.
type FakeStackTableKey struct {
	FakeStackIndex int32
}

var fakeStackTableIndexShapes = []snmp.IndexShape{{Kind: snmp.IndexInteger}}

// decodeFakeStackTableKey decodes the instance suffix of one fakeStackTable row. ok is false
// when the suffix does not match the declared INDEX; the key is then zero.
func decodeFakeStackTableKey(idx snmp.OID) (FakeStackTableKey, bool) {
	var parts [1]snmp.IndexValue
	if !snmp.DecodeIndexInto(parts[:], idx, fakeStackTableIndexShapes) {
		return FakeStackTableKey{}, false
	}
	return FakeStackTableKey{FakeStackIndex: int32(parts[0].Integer)}, true
}

// FakeStackTableRow is one table row; KeyValid reports index validity, use Observed for field presence, and concurrent reads are safe.
type FakeStackTableRow struct {
	Key           FakeStackTableKey
	keyValid      bool
	FakeStackName string
	observed      [1]uint64
}

// KeyValid reports whether Key decoded from the row index.
func (r FakeStackTableRow) KeyValid() bool {
	return r.keyValid
}

// Observed reports whether col supplied this row field, including a zero value.
func (r FakeStackTableRow) Observed(col snmp.AnyColumn) bool {
	return snmp.ColumnObserved(r.observed[:], fakeStackTableColumns, col)
}

// FakeStackTableWalker streams one table walk; its zero value is unusable, and Err/Close are safe concurrently.
type FakeStackTableWalker struct {
	snmp.TableWalker[FakeStackTableRow]
}
type fakeStackTableT struct {
	snmp.Table[FakeStackTableRow, *FakeStackTableWalker]
}

// FakeStackTable is the descriptor for the fakeStackTable table.
var FakeStackTable = fakeStackTableT{Table: snmp.NewTable("fakeStackTable", fakeStackTableColumns, func(idx snmp.OID, row *FakeStackTableRow) {
	row.Key, row.keyValid = decodeFakeStackTableKey(idx)
}, func(row *FakeStackTableRow, ordinal int, rv snmp.RawVarBind) error {
	switch ordinal {
	case 0:
		return snmp.DecodeColumn(rv, FakeStackName, &row.FakeStackName, row.observed[:])
	}
	return nil
}, func(tw snmp.TableWalker[FakeStackTableRow]) *FakeStackTableWalker {
	return &FakeStackTableWalker{TableWalker: tw}
})}

// Descriptor returns the table identity, change indicator, and row-key type.
func (fakeStackTableT) Descriptor() snmp.TableDescriptor {
	return snmp.TableDescriptor{
		Indicator: FakeStackTableIndicator,
		KeyType:   "FakeStackTableKey",
		Root:      snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 4),
	}
}

// decodeFakeStackTableRow decodes one row of FakeStackTable from the supplied
// VarBinds. Each VarBind's OID determines which row field it populates
// (via the column's last sub-id). VarBinds with unknown column-ids are
// ignored. Absent columns leave their field at its zero value.
func decodeFakeStackTableRow(idx snmp.OID, vbs []snmp.VarBind) (FakeStackTableRow, error) {
	var row FakeStackTableRow
	row.Key, row.keyValid = decodeFakeStackTableKey(idx)

	for _, vb := range vbs {
		o := vb.GetHeader().OID
		if o.Len() == 0 {
			continue
		}
		entryLen := snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 4, 1).Len()
		if o.Len() <= entryLen {
			continue
		}
		colID := o.At(entryLen)
		if colID == 2 {
			dv, derr := FakeStackName.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeStackName = dv
			row.observed[0] |= 1 << 0
		}
	}

	return row, nil
}

// equalFakeStackTableRow compares two FakeStackTableRow values for equality.
// Used by [snmp.Watcher] to compute ChangeKindModified emits. Field-by-
// field with the type-appropriate comparator (bytes.Equal for []byte,
// OID.Equal for OID, time.Time.Equal for time.Time, == for everything else).
func equalFakeStackTableRow(a FakeStackTableRow, b FakeStackTableRow) bool {
	return a.Key == b.Key && a.keyValid == b.keyValid && a.observed == b.observed && a.FakeStackName == b.FakeStackName
}

// mergeFakeStackTableRow merges the values decoded from vbs into dst, leaving fields
// whose columns are not present in vbs unchanged. Used by [snmp.Watcher]
// to maintain per-row state under partial-column fetches (Counter-tier,
// Static-tier). Best-effort: individual VarBind decode failures are
// silently skipped rather than propagated, because partial-fetch ticks
// surface transient errors through [snmp.Watcher.LastTickErr] at the
// call-site granularity rather than per-VarBind.
func mergeFakeStackTableRow(dst *FakeStackTableRow, vbs []snmp.VarBind) {
	for _, vb := range vbs {
		o := vb.GetHeader().OID
		if o.Len() == 0 {
			continue
		}
		entryLen := snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 4, 1).Len()
		if o.Len() <= entryLen {
			continue
		}
		colID := o.At(entryLen)
		if colID == 2 {
			dv, derr := FakeStackName.Decode(vb)
			if derr == nil {
				dst.FakeStackName = dv
				dst.observed[0] |= 1 << 0
			}
		}
	}
}

// FakeStackTableWatcher is a table-aware Watcher over FakeStackTable.
// The zero value is not usable; construct via FakeStackTable.Watch(ctx, sess, cols, opts...).
// Use a single iterator. The other methods may be called concurrently.
type FakeStackTableWatcher struct {
	w *snmp.Watcher[FakeStackTableRow]
}

// Iter returns the range-over-func view of the Watcher's event stream.
// See [snmp.Watcher.Iter] for the contract.
func (tw *FakeStackTableWatcher) Iter() iter.Seq2[snmp.OID, snmp.WatchEvent[FakeStackTableRow]] {
	return tw.w.Iter()
}

// Err returns the underlying Watcher's terminal error, or nil if it
// completed naturally. See [snmp.Watcher.Err].
func (tw *FakeStackTableWatcher) Err() error {
	return tw.w.Err()
}

// Close signals the Watcher's tick goroutine to terminate. Idempotent.
// See [snmp.Watcher.Close].
func (tw *FakeStackTableWatcher) Close() error {
	return tw.w.Close()
}

// Fallback reports whether the Watcher has transitioned to fallback
// mode. See [snmp.Watcher.Fallback].
func (tw *FakeStackTableWatcher) Fallback() bool {
	return tw.w.Fallback()
}

// LastTickErr returns the most-recent transient per-tick error.
// See [snmp.Watcher.LastTickErr].
func (tw *FakeStackTableWatcher) LastTickErr() error {
	return tw.w.LastTickErr()
}

// TableRoot returns the OID of the table this Watcher operates over.
func (tw *FakeStackTableWatcher) TableRoot() snmp.OID {
	return tw.w.TableRoot()
}

// Watch opens a long-lived watch on FakeStackTable.
//
// cols selects the columns whose values are reported on every emitted
// event. opts override cadence bounds, per-column tier classifications,
// fallback behavior, and other policy — see [snmp.WatchOption] for the
// full set.
//
// cols is a slice rather than variadic because opts is variadic and
// Go forbids two variadic parameters.
//
// Events emitted on this stream:
//   - ChangeKindAdded    — Row populated, Prev always nil.
//   - ChangeKindModified — Row is current state. Prev is nil unless
//     the caller passed [snmp.WithPrevRow]; when
//     set, Prev carries the previous Row.
//   - ChangeKindRemoved  — Row carries the last-known state at the
//     time the row disappeared. Prev is nil.
//
// The returned Watcher must be Closed when the caller is done; iteration
// exit alone does not free the underlying goroutine until Close.
//
// On validation failure (invalid cadence bounds, tier override of the
// indicator column, etc.) Watch returns a Watcher whose Err() returns
// the cause immediately; range loops exit without emitting events and
// Close is a no-op.
func (fakeStackTableT) Watch(ctx context.Context, sess snmp.Session, cols []snmp.AnyColumn, opts ...snmp.WatchOption) *FakeStackTableWatcher {
	allOpts := append([]snmp.WatchOption{snmp.WithTierLookup(ColumnTier)}, opts...)
	w, _ := snmp.NewWatcher[FakeStackTableRow](ctx, sess, FakeStackTableIndicator, cols, decodeFakeStackTableRow, equalFakeStackTableRow, mergeFakeStackTableRow, allOpts...)

	return &FakeStackTableWatcher{w: w}
}

// FakePairValue is fakePairValue.
// Value.
var (
	FakePairValue        = snmp.NewFusedTableColumn[int32](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 7, 1, 3), snmp.KindInteger32, snmp.DecodeInt32, snmp.RawInteger32, 0)
	fakePairTableColumns = []snmp.AnyColumn{FakePairValue}
)

// FakePairTableKey is the decoded INDEX of one fakePairTable row, one field per
// part in INDEX order. It is comparable and usable as a map key.
type FakePairTableKey struct {
	FakePairSlot int32
	FakePairName string
}

var fakePairTableIndexShapes = []snmp.IndexShape{{Kind: snmp.IndexInteger}, {Kind: snmp.IndexLengthPrefixedOctets}}

// decodeFakePairTableKey decodes the instance suffix of one fakePairTable row. ok is false
// when the suffix does not match the declared INDEX; the key is then zero.
func decodeFakePairTableKey(idx snmp.OID) (FakePairTableKey, bool) {
	var parts [2]snmp.IndexValue
	if !snmp.DecodeIndexInto(parts[:], idx, fakePairTableIndexShapes) {
		return FakePairTableKey{}, false
	}
	return FakePairTableKey{FakePairSlot: int32(parts[0].Integer), FakePairName: string(parts[1].Octets)}, true
}

// FakePairTableRow is one table row; KeyValid reports index validity, use Observed for field presence, and concurrent reads are safe.
type FakePairTableRow struct {
	Key           FakePairTableKey
	keyValid      bool
	FakePairValue int32
	observed      [1]uint64
}

// KeyValid reports whether Key decoded from the row index.
func (r FakePairTableRow) KeyValid() bool {
	return r.keyValid
}

// Observed reports whether col supplied this row field, including a zero value.
func (r FakePairTableRow) Observed(col snmp.AnyColumn) bool {
	return snmp.ColumnObserved(r.observed[:], fakePairTableColumns, col)
}

// FakePairTableWalker streams one table walk; its zero value is unusable, and Err/Close are safe concurrently.
type FakePairTableWalker struct {
	snmp.TableWalker[FakePairTableRow]
}
type fakePairTableT struct {
	snmp.Table[FakePairTableRow, *FakePairTableWalker]
}

// FakePairTable is the descriptor for the fakePairTable table.
var FakePairTable = fakePairTableT{Table: snmp.NewTable("fakePairTable", fakePairTableColumns, func(idx snmp.OID, row *FakePairTableRow) {
	row.Key, row.keyValid = decodeFakePairTableKey(idx)
}, func(row *FakePairTableRow, ordinal int, rv snmp.RawVarBind) error {
	switch ordinal {
	case 0:
		return snmp.DecodeColumn(rv, FakePairValue, &row.FakePairValue, row.observed[:])
	}
	return nil
}, func(tw snmp.TableWalker[FakePairTableRow]) *FakePairTableWalker {
	return &FakePairTableWalker{TableWalker: tw}
})}

// Descriptor returns the table identity, change indicator, and row-key type.
func (fakePairTableT) Descriptor() snmp.TableDescriptor {
	return snmp.TableDescriptor{
		KeyType: "FakePairTableKey",
		Root:    snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 7),
	}
}

// FakeImpliedValue is fakeImpliedValue.
// Value.
var (
	FakeImpliedValue        = snmp.NewFusedTableColumn[int32](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 8, 1, 2), snmp.KindInteger32, snmp.DecodeInt32, snmp.RawInteger32, 0)
	fakeImpliedTableColumns = []snmp.AnyColumn{FakeImpliedValue}
)

// FakeImpliedTableKey is the decoded INDEX of one fakeImpliedTable row, one field per
// part in INDEX order. It is comparable and usable as a map key.
type FakeImpliedTableKey struct {
	FakeImpliedName string
}

var fakeImpliedTableIndexShapes = []snmp.IndexShape{{Kind: snmp.IndexImpliedOctets}}

// decodeFakeImpliedTableKey decodes the instance suffix of one fakeImpliedTable row. ok is false
// when the suffix does not match the declared INDEX; the key is then zero.
func decodeFakeImpliedTableKey(idx snmp.OID) (FakeImpliedTableKey, bool) {
	var parts [1]snmp.IndexValue
	if !snmp.DecodeIndexInto(parts[:], idx, fakeImpliedTableIndexShapes) {
		return FakeImpliedTableKey{}, false
	}
	return FakeImpliedTableKey{FakeImpliedName: string(parts[0].Octets)}, true
}

// FakeImpliedTableRow is one table row; KeyValid reports index validity, use Observed for field presence, and concurrent reads are safe.
type FakeImpliedTableRow struct {
	Key              FakeImpliedTableKey
	keyValid         bool
	FakeImpliedValue int32
	observed         [1]uint64
}

// KeyValid reports whether Key decoded from the row index.
func (r FakeImpliedTableRow) KeyValid() bool {
	return r.keyValid
}

// Observed reports whether col supplied this row field, including a zero value.
func (r FakeImpliedTableRow) Observed(col snmp.AnyColumn) bool {
	return snmp.ColumnObserved(r.observed[:], fakeImpliedTableColumns, col)
}

// FakeImpliedTableWalker streams one table walk; its zero value is unusable, and Err/Close are safe concurrently.
type FakeImpliedTableWalker struct {
	snmp.TableWalker[FakeImpliedTableRow]
}
type fakeImpliedTableT struct {
	snmp.Table[FakeImpliedTableRow, *FakeImpliedTableWalker]
}

// FakeImpliedTable is the descriptor for the fakeImpliedTable table.
var FakeImpliedTable = fakeImpliedTableT{Table: snmp.NewTable("fakeImpliedTable", fakeImpliedTableColumns, func(idx snmp.OID, row *FakeImpliedTableRow) {
	row.Key, row.keyValid = decodeFakeImpliedTableKey(idx)
}, func(row *FakeImpliedTableRow, ordinal int, rv snmp.RawVarBind) error {
	switch ordinal {
	case 0:
		return snmp.DecodeColumn(rv, FakeImpliedValue, &row.FakeImpliedValue, row.observed[:])
	}
	return nil
}, func(tw snmp.TableWalker[FakeImpliedTableRow]) *FakeImpliedTableWalker {
	return &FakeImpliedTableWalker{TableWalker: tw}
})}

// Descriptor returns the table identity, change indicator, and row-key type.
func (fakeImpliedTableT) Descriptor() snmp.TableDescriptor {
	return snmp.TableDescriptor{
		KeyType: "FakeImpliedTableKey",
		Root:    snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 8),
	}
}

// FakeAddrLabel is fakeAddrLabel.
// Label.
var (
	FakeAddrLabel        = snmp.NewTableColumn[string](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 9, 1, 2), snmp.KindOctetString, snmp.DecodeDisplayString, 0)
	fakeAddrTableColumns = []snmp.AnyColumn{FakeAddrLabel}
)

// FakeAddrTableKey is the decoded INDEX of one fakeAddrTable row, one field per
// part in INDEX order. It is comparable and usable as a map key.
type FakeAddrTableKey struct {
	FakeAddrIP netip.Addr
}

var fakeAddrTableIndexShapes = []snmp.IndexShape{{Kind: snmp.IndexIPv4}}

// decodeFakeAddrTableKey decodes the instance suffix of one fakeAddrTable row. ok is false
// when the suffix does not match the declared INDEX; the key is then zero.
func decodeFakeAddrTableKey(idx snmp.OID) (FakeAddrTableKey, bool) {
	var parts [1]snmp.IndexValue
	if !snmp.DecodeIndexInto(parts[:], idx, fakeAddrTableIndexShapes) {
		return FakeAddrTableKey{}, false
	}
	return FakeAddrTableKey{FakeAddrIP: parts[0].Addr}, true
}

// FakeAddrTableRow is one table row; KeyValid reports index validity, use Observed for field presence, and concurrent reads are safe.
type FakeAddrTableRow struct {
	Key           FakeAddrTableKey
	keyValid      bool
	FakeAddrLabel string
	observed      [1]uint64
}

// KeyValid reports whether Key decoded from the row index.
func (r FakeAddrTableRow) KeyValid() bool {
	return r.keyValid
}

// Observed reports whether col supplied this row field, including a zero value.
func (r FakeAddrTableRow) Observed(col snmp.AnyColumn) bool {
	return snmp.ColumnObserved(r.observed[:], fakeAddrTableColumns, col)
}

// FakeAddrTableWalker streams one table walk; its zero value is unusable, and Err/Close are safe concurrently.
type FakeAddrTableWalker struct {
	snmp.TableWalker[FakeAddrTableRow]
}
type fakeAddrTableT struct {
	snmp.Table[FakeAddrTableRow, *FakeAddrTableWalker]
}

// FakeAddrTable is the descriptor for the fakeAddrTable table.
var FakeAddrTable = fakeAddrTableT{Table: snmp.NewTable("fakeAddrTable", fakeAddrTableColumns, func(idx snmp.OID, row *FakeAddrTableRow) {
	row.Key, row.keyValid = decodeFakeAddrTableKey(idx)
}, func(row *FakeAddrTableRow, ordinal int, rv snmp.RawVarBind) error {
	switch ordinal {
	case 0:
		return snmp.DecodeColumn(rv, FakeAddrLabel, &row.FakeAddrLabel, row.observed[:])
	}
	return nil
}, func(tw snmp.TableWalker[FakeAddrTableRow]) *FakeAddrTableWalker {
	return &FakeAddrTableWalker{TableWalker: tw}
})}

// Descriptor returns the table identity, change indicator, and row-key type.
func (fakeAddrTableT) Descriptor() snmp.TableDescriptor {
	return snmp.TableDescriptor{
		KeyType: "FakeAddrTableKey",
		Root:    snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 9),
	}
}

// FakeOIDLabel is fakeOidLabel.
// Label.
var (
	FakeOIDLabel        = snmp.NewTableColumn[string](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 10, 1, 2), snmp.KindOctetString, snmp.DecodeDisplayString, 0)
	fakeOIDTableColumns = []snmp.AnyColumn{FakeOIDLabel}
)

// FakeOIDTableKey is the decoded INDEX of one fakeOidTable row, one field per
// part in INDEX order. It is comparable and usable as a map key.
type FakeOIDTableKey struct {
	FakeOIDPath string
}

var fakeOIDTableIndexShapes = []snmp.IndexShape{{Kind: snmp.IndexLengthPrefixedOID}}

// decodeFakeOIDTableKey decodes the instance suffix of one fakeOidTable row. ok is false
// when the suffix does not match the declared INDEX; the key is then zero.
func decodeFakeOIDTableKey(idx snmp.OID) (FakeOIDTableKey, bool) {
	var parts [1]snmp.IndexValue
	if !snmp.DecodeIndexInto(parts[:], idx, fakeOIDTableIndexShapes) {
		return FakeOIDTableKey{}, false
	}
	return FakeOIDTableKey{FakeOIDPath: parts[0].OID.String()}, true
}

// FakeOIDTableRow is one table row; KeyValid reports index validity, use Observed for field presence, and concurrent reads are safe.
type FakeOIDTableRow struct {
	Key          FakeOIDTableKey
	keyValid     bool
	FakeOIDLabel string
	observed     [1]uint64
}

// KeyValid reports whether Key decoded from the row index.
func (r FakeOIDTableRow) KeyValid() bool {
	return r.keyValid
}

// Observed reports whether col supplied this row field, including a zero value.
func (r FakeOIDTableRow) Observed(col snmp.AnyColumn) bool {
	return snmp.ColumnObserved(r.observed[:], fakeOIDTableColumns, col)
}

// FakeOIDTableWalker streams one table walk; its zero value is unusable, and Err/Close are safe concurrently.
type FakeOIDTableWalker struct {
	snmp.TableWalker[FakeOIDTableRow]
}
type fakeOIDTableT struct {
	snmp.Table[FakeOIDTableRow, *FakeOIDTableWalker]
}

// FakeOIDTable is the descriptor for the fakeOidTable table.
var FakeOIDTable = fakeOIDTableT{Table: snmp.NewTable("fakeOidTable", fakeOIDTableColumns, func(idx snmp.OID, row *FakeOIDTableRow) {
	row.Key, row.keyValid = decodeFakeOIDTableKey(idx)
}, func(row *FakeOIDTableRow, ordinal int, rv snmp.RawVarBind) error {
	switch ordinal {
	case 0:
		return snmp.DecodeColumn(rv, FakeOIDLabel, &row.FakeOIDLabel, row.observed[:])
	}
	return nil
}, func(tw snmp.TableWalker[FakeOIDTableRow]) *FakeOIDTableWalker {
	return &FakeOIDTableWalker{TableWalker: tw}
})}

// Descriptor returns the table identity, change indicator, and row-key type.
func (fakeOIDTableT) Descriptor() snmp.TableDescriptor {
	return snmp.TableDescriptor{
		KeyType: "FakeOIDTableKey",
		Root:    snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 10),
	}
}

// FakeAugExtra is fakeAugExtra.
// Extra value.
var (
	FakeAugExtra            = snmp.NewFusedTableColumn[int32](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 11, 1, 1), snmp.KindInteger32, snmp.DecodeInt32, snmp.RawInteger32, 0)
	fakeAugTableColumns     = []snmp.AnyColumn{FakeAugExtra}
	fakeAugTableIndexShapes = []snmp.IndexShape{{Kind: snmp.IndexInteger}}
)

// decodeFakeAugTableKey decodes the instance suffix of one fakeAugTable row. ok is false
// when the suffix does not match the declared INDEX; the key is then zero.
func decodeFakeAugTableKey(idx snmp.OID) (FakeTableKey, bool) {
	var parts [1]snmp.IndexValue
	if !snmp.DecodeIndexInto(parts[:], idx, fakeAugTableIndexShapes) {
		return FakeTableKey{}, false
	}
	return FakeTableKey{FakeIndex: int32(parts[0].Integer)}, true
}

// FakeAugTableRow is one table row; KeyValid reports index validity, use Observed for field presence, and concurrent reads are safe.
type FakeAugTableRow struct {
	Key          FakeTableKey
	keyValid     bool
	FakeAugExtra int32
	observed     [1]uint64
}

// KeyValid reports whether Key decoded from the row index.
func (r FakeAugTableRow) KeyValid() bool {
	return r.keyValid
}

// Observed reports whether col supplied this row field, including a zero value.
func (r FakeAugTableRow) Observed(col snmp.AnyColumn) bool {
	return snmp.ColumnObserved(r.observed[:], fakeAugTableColumns, col)
}

// FakeAugTableWalker streams one table walk; its zero value is unusable, and Err/Close are safe concurrently.
type FakeAugTableWalker struct {
	snmp.TableWalker[FakeAugTableRow]
}
type fakeAugTableT struct {
	snmp.Table[FakeAugTableRow, *FakeAugTableWalker]
}

// FakeAugTable is the descriptor for the fakeAugTable table.
var FakeAugTable = fakeAugTableT{Table: snmp.NewTable("fakeAugTable", fakeAugTableColumns, func(idx snmp.OID, row *FakeAugTableRow) {
	row.Key, row.keyValid = decodeFakeAugTableKey(idx)
}, func(row *FakeAugTableRow, ordinal int, rv snmp.RawVarBind) error {
	switch ordinal {
	case 0:
		return snmp.DecodeColumn(rv, FakeAugExtra, &row.FakeAugExtra, row.observed[:])
	}
	return nil
}, func(tw snmp.TableWalker[FakeAugTableRow]) *FakeAugTableWalker {
	return &FakeAugTableWalker{TableWalker: tw}
})}

// Descriptor returns the table identity, change indicator, and row-key type.
func (fakeAugTableT) Descriptor() snmp.TableDescriptor {
	return snmp.TableDescriptor{
		KeyType: "FakeTableKey",
		Root:    snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 11),
	}
}

// FakeUnresolvedValue is fakeUnresolvedValue.
// Value.
var (
	FakeUnresolvedValue        = snmp.NewFusedTableColumn[int32](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 12, 1, 1), snmp.KindInteger32, snmp.DecodeInt32, snmp.RawInteger32, 0)
	fakeUnresolvedTableColumns = []snmp.AnyColumn{FakeUnresolvedValue}
)

// FakeUnresolvedTableRow is one table row; Index is the raw OID suffix, use Observed for field presence, and concurrent reads are safe.
type FakeUnresolvedTableRow struct {
	Index               snmp.OID
	FakeUnresolvedValue int32
	observed            [1]uint64
}

// Observed reports whether col supplied this row field, including a zero value.
func (r FakeUnresolvedTableRow) Observed(col snmp.AnyColumn) bool {
	return snmp.ColumnObserved(r.observed[:], fakeUnresolvedTableColumns, col)
}

// FakeUnresolvedTableWalker streams one table walk; its zero value is unusable, and Err/Close are safe concurrently.
type FakeUnresolvedTableWalker struct {
	snmp.TableWalker[FakeUnresolvedTableRow]
}
type fakeUnresolvedTableT struct {
	snmp.Table[FakeUnresolvedTableRow, *FakeUnresolvedTableWalker]
}

// FakeUnresolvedTable is the descriptor for the fakeUnresolvedTable table.
var FakeUnresolvedTable = fakeUnresolvedTableT{Table: snmp.NewTable("fakeUnresolvedTable", fakeUnresolvedTableColumns, func(idx snmp.OID, row *FakeUnresolvedTableRow) {
	row.Index = idx
}, func(row *FakeUnresolvedTableRow, ordinal int, rv snmp.RawVarBind) error {
	switch ordinal {
	case 0:
		return snmp.DecodeColumn(rv, FakeUnresolvedValue, &row.FakeUnresolvedValue, row.observed[:])
	}
	return nil
}, func(tw snmp.TableWalker[FakeUnresolvedTableRow]) *FakeUnresolvedTableWalker {
	return &FakeUnresolvedTableWalker{TableWalker: tw}
})}

// Descriptor returns the table identity, change indicator, and row-key type.
func (fakeUnresolvedTableT) Descriptor() snmp.TableDescriptor {
	return snmp.TableDescriptor{
		KeyType: "snmp.OID",
		Root:    snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 12),
	}
}

// FakeKeyAugExtra is fakeKeyAugExtra.
// Extra value.
var (
	FakeKeyAugExtra            = snmp.NewFusedTableColumn[int32](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 13, 1, 1), snmp.KindInteger32, snmp.DecodeInt32, snmp.RawInteger32, 0)
	fakeKeyAugTableColumns     = []snmp.AnyColumn{FakeKeyAugExtra}
	fakeKeyAugTableIndexShapes = []snmp.IndexShape{{Kind: snmp.IndexInteger}}
)

// decodeFakeKeyAugTableKey decodes the instance suffix of one fakeKeyAugTable row. ok is false
// when the suffix does not match the declared INDEX; the key is then zero.
func decodeFakeKeyAugTableKey(idx snmp.OID) (fakekeysmib.FakeKeyTableKey, bool) {
	var parts [1]snmp.IndexValue
	if !snmp.DecodeIndexInto(parts[:], idx, fakeKeyAugTableIndexShapes) {
		return fakekeysmib.FakeKeyTableKey{}, false
	}
	return fakekeysmib.FakeKeyTableKey{FakeKeyIndex: fakekeysmib.FakeKeyIndex(parts[0].Integer)}, true
}

// FakeKeyAugTableRow is one table row; KeyValid reports index validity, use Observed for field presence, and concurrent reads are safe.
type FakeKeyAugTableRow struct {
	Key             fakekeysmib.FakeKeyTableKey
	keyValid        bool
	FakeKeyAugExtra int32
	observed        [1]uint64
}

// KeyValid reports whether Key decoded from the row index.
func (r FakeKeyAugTableRow) KeyValid() bool {
	return r.keyValid
}

// Observed reports whether col supplied this row field, including a zero value.
func (r FakeKeyAugTableRow) Observed(col snmp.AnyColumn) bool {
	return snmp.ColumnObserved(r.observed[:], fakeKeyAugTableColumns, col)
}

// FakeKeyAugTableWalker streams one table walk; its zero value is unusable, and Err/Close are safe concurrently.
type FakeKeyAugTableWalker struct {
	snmp.TableWalker[FakeKeyAugTableRow]
}
type fakeKeyAugTableT struct {
	snmp.Table[FakeKeyAugTableRow, *FakeKeyAugTableWalker]
}

// FakeKeyAugTable is the descriptor for the fakeKeyAugTable table.
var FakeKeyAugTable = fakeKeyAugTableT{Table: snmp.NewTable("fakeKeyAugTable", fakeKeyAugTableColumns, func(idx snmp.OID, row *FakeKeyAugTableRow) {
	row.Key, row.keyValid = decodeFakeKeyAugTableKey(idx)
}, func(row *FakeKeyAugTableRow, ordinal int, rv snmp.RawVarBind) error {
	switch ordinal {
	case 0:
		return snmp.DecodeColumn(rv, FakeKeyAugExtra, &row.FakeKeyAugExtra, row.observed[:])
	}
	return nil
}, func(tw snmp.TableWalker[FakeKeyAugTableRow]) *FakeKeyAugTableWalker {
	return &FakeKeyAugTableWalker{TableWalker: tw}
})}

// Descriptor returns the table identity, change indicator, and row-key type.
func (fakeKeyAugTableT) Descriptor() snmp.TableDescriptor {
	return snmp.TableDescriptor{
		KeyType: "fakekeysmib.FakeKeyTableKey",
		Root:    snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 13),
	}
}

// FakeChainExtra is fakeChainExtra.
// Extra value.
var (
	FakeChainExtra            = snmp.NewFusedTableColumn[int32](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 14, 1, 1), snmp.KindInteger32, snmp.DecodeInt32, snmp.RawInteger32, 0)
	fakeChainTableColumns     = []snmp.AnyColumn{FakeChainExtra}
	fakeChainTableIndexShapes = []snmp.IndexShape{{Kind: snmp.IndexInteger}}
)

// decodeFakeChainTableKey decodes the instance suffix of one fakeChainTable row. ok is false
// when the suffix does not match the declared INDEX; the key is then zero.
func decodeFakeChainTableKey(idx snmp.OID) (FakeTableKey, bool) {
	var parts [1]snmp.IndexValue
	if !snmp.DecodeIndexInto(parts[:], idx, fakeChainTableIndexShapes) {
		return FakeTableKey{}, false
	}
	return FakeTableKey{FakeIndex: int32(parts[0].Integer)}, true
}

// FakeChainTableRow is one table row; KeyValid reports index validity, use Observed for field presence, and concurrent reads are safe.
type FakeChainTableRow struct {
	Key            FakeTableKey
	keyValid       bool
	FakeChainExtra int32
	observed       [1]uint64
}

// KeyValid reports whether Key decoded from the row index.
func (r FakeChainTableRow) KeyValid() bool {
	return r.keyValid
}

// Observed reports whether col supplied this row field, including a zero value.
func (r FakeChainTableRow) Observed(col snmp.AnyColumn) bool {
	return snmp.ColumnObserved(r.observed[:], fakeChainTableColumns, col)
}

// FakeChainTableWalker streams one table walk; its zero value is unusable, and Err/Close are safe concurrently.
type FakeChainTableWalker struct {
	snmp.TableWalker[FakeChainTableRow]
}
type fakeChainTableT struct {
	snmp.Table[FakeChainTableRow, *FakeChainTableWalker]
}

// FakeChainTable is the descriptor for the fakeChainTable table.
var FakeChainTable = fakeChainTableT{Table: snmp.NewTable("fakeChainTable", fakeChainTableColumns, func(idx snmp.OID, row *FakeChainTableRow) {
	row.Key, row.keyValid = decodeFakeChainTableKey(idx)
}, func(row *FakeChainTableRow, ordinal int, rv snmp.RawVarBind) error {
	switch ordinal {
	case 0:
		return snmp.DecodeColumn(rv, FakeChainExtra, &row.FakeChainExtra, row.observed[:])
	}
	return nil
}, func(tw snmp.TableWalker[FakeChainTableRow]) *FakeChainTableWalker {
	return &FakeChainTableWalker{TableWalker: tw}
})}

// Descriptor returns the table identity, change indicator, and row-key type.
func (fakeChainTableT) Descriptor() snmp.TableDescriptor {
	return snmp.TableDescriptor{
		KeyType: "FakeTableKey",
		Root:    snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 14),
	}
}

// FakeBareTableKey is the decoded INDEX of one fakeBareTable row, one field per
// part in INDEX order. It is comparable and usable as a map key.
type FakeBareTableKey struct {
	FakeBareIndex int32
}

// FakeBareAugExtra is fakeBareAugExtra.
// Extra value.
var (
	FakeBareAugExtra            = snmp.NewFusedTableColumn[int32](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 16, 1, 1), snmp.KindInteger32, snmp.DecodeInt32, snmp.RawInteger32, 0)
	fakeBareAugTableColumns     = []snmp.AnyColumn{FakeBareAugExtra}
	fakeBareAugTableIndexShapes = []snmp.IndexShape{{Kind: snmp.IndexInteger}}
)

// decodeFakeBareAugTableKey decodes the instance suffix of one fakeBareAugTable row. ok is false
// when the suffix does not match the declared INDEX; the key is then zero.
func decodeFakeBareAugTableKey(idx snmp.OID) (FakeBareTableKey, bool) {
	var parts [1]snmp.IndexValue
	if !snmp.DecodeIndexInto(parts[:], idx, fakeBareAugTableIndexShapes) {
		return FakeBareTableKey{}, false
	}
	return FakeBareTableKey{FakeBareIndex: int32(parts[0].Integer)}, true
}

// FakeBareAugTableRow is one table row; KeyValid reports index validity, use Observed for field presence, and concurrent reads are safe.
type FakeBareAugTableRow struct {
	Key              FakeBareTableKey
	keyValid         bool
	FakeBareAugExtra int32
	observed         [1]uint64
}

// KeyValid reports whether Key decoded from the row index.
func (r FakeBareAugTableRow) KeyValid() bool {
	return r.keyValid
}

// Observed reports whether col supplied this row field, including a zero value.
func (r FakeBareAugTableRow) Observed(col snmp.AnyColumn) bool {
	return snmp.ColumnObserved(r.observed[:], fakeBareAugTableColumns, col)
}

// FakeBareAugTableWalker streams one table walk; its zero value is unusable, and Err/Close are safe concurrently.
type FakeBareAugTableWalker struct {
	snmp.TableWalker[FakeBareAugTableRow]
}
type fakeBareAugTableT struct {
	snmp.Table[FakeBareAugTableRow, *FakeBareAugTableWalker]
}

// FakeBareAugTable is the descriptor for the fakeBareAugTable table.
var FakeBareAugTable = fakeBareAugTableT{Table: snmp.NewTable("fakeBareAugTable", fakeBareAugTableColumns, func(idx snmp.OID, row *FakeBareAugTableRow) {
	row.Key, row.keyValid = decodeFakeBareAugTableKey(idx)
}, func(row *FakeBareAugTableRow, ordinal int, rv snmp.RawVarBind) error {
	switch ordinal {
	case 0:
		return snmp.DecodeColumn(rv, FakeBareAugExtra, &row.FakeBareAugExtra, row.observed[:])
	}
	return nil
}, func(tw snmp.TableWalker[FakeBareAugTableRow]) *FakeBareAugTableWalker {
	return &FakeBareAugTableWalker{TableWalker: tw}
})}

// Descriptor returns the table identity, change indicator, and row-key type.
func (fakeBareAugTableT) Descriptor() snmp.TableDescriptor {
	return snmp.TableDescriptor{
		KeyType: "FakeBareTableKey",
		Root:    snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 16),
	}
}

// FakeRefinedValue is fakeRefinedValue.
// Value.
var (
	FakeRefinedValue        = snmp.NewFusedTableColumn[int32](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 17, 1, 2), snmp.KindInteger32, snmp.DecodeInt32, snmp.RawInteger32, 0)
	fakeRefinedTableColumns = []snmp.AnyColumn{FakeRefinedValue}
)

// FakeRefinedTableKey is the decoded INDEX of one fakeRefinedTable row, one field per
// part in INDEX order. It is comparable and usable as a map key.
type FakeRefinedTableKey struct {
	FakeRefinedIndex fakekeysmib.FakeKeyIndex
}

var fakeRefinedTableIndexShapes = []snmp.IndexShape{{Kind: snmp.IndexInteger}}

// decodeFakeRefinedTableKey decodes the instance suffix of one fakeRefinedTable row. ok is false
// when the suffix does not match the declared INDEX; the key is then zero.
func decodeFakeRefinedTableKey(idx snmp.OID) (FakeRefinedTableKey, bool) {
	var parts [1]snmp.IndexValue
	if !snmp.DecodeIndexInto(parts[:], idx, fakeRefinedTableIndexShapes) {
		return FakeRefinedTableKey{}, false
	}
	return FakeRefinedTableKey{FakeRefinedIndex: fakekeysmib.FakeKeyIndex(parts[0].Integer)}, true
}

// FakeRefinedTableRow is one table row; KeyValid reports index validity, use Observed for field presence, and concurrent reads are safe.
type FakeRefinedTableRow struct {
	Key              FakeRefinedTableKey
	keyValid         bool
	FakeRefinedValue int32
	observed         [1]uint64
}

// KeyValid reports whether Key decoded from the row index.
func (r FakeRefinedTableRow) KeyValid() bool {
	return r.keyValid
}

// Observed reports whether col supplied this row field, including a zero value.
func (r FakeRefinedTableRow) Observed(col snmp.AnyColumn) bool {
	return snmp.ColumnObserved(r.observed[:], fakeRefinedTableColumns, col)
}

// FakeRefinedTableWalker streams one table walk; its zero value is unusable, and Err/Close are safe concurrently.
type FakeRefinedTableWalker struct {
	snmp.TableWalker[FakeRefinedTableRow]
}
type fakeRefinedTableT struct {
	snmp.Table[FakeRefinedTableRow, *FakeRefinedTableWalker]
}

// FakeRefinedTable is the descriptor for the fakeRefinedTable table.
var FakeRefinedTable = fakeRefinedTableT{Table: snmp.NewTable("fakeRefinedTable", fakeRefinedTableColumns, func(idx snmp.OID, row *FakeRefinedTableRow) {
	row.Key, row.keyValid = decodeFakeRefinedTableKey(idx)
}, func(row *FakeRefinedTableRow, ordinal int, rv snmp.RawVarBind) error {
	switch ordinal {
	case 0:
		return snmp.DecodeColumn(rv, FakeRefinedValue, &row.FakeRefinedValue, row.observed[:])
	}
	return nil
}, func(tw snmp.TableWalker[FakeRefinedTableRow]) *FakeRefinedTableWalker {
	return &FakeRefinedTableWalker{TableWalker: tw}
})}

// Descriptor returns the table identity, change indicator, and row-key type.
func (fakeRefinedTableT) Descriptor() snmp.TableDescriptor {
	return snmp.TableDescriptor{
		KeyType: "FakeRefinedTableKey",
		Root:    snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 17),
	}
}

// FakeSoloLastChange is fakeSoloLastChange.
// The table's single readable column and change indicator.
var (
	FakeSoloLastChange   = snmp.NewFusedTableColumn[uint32](snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 19, 1, 2), snmp.KindCounter32, snmp.DecodeUint32, snmp.RawCounter32, 0)
	fakeSoloTableColumns = []snmp.AnyColumn{FakeSoloLastChange}
)

// FakeSoloTableKey is the decoded INDEX of one fakeSoloTable row, one field per
// part in INDEX order. It is comparable and usable as a map key.
type FakeSoloTableKey struct {
	FakeSoloIndex int32
}

var fakeSoloTableIndexShapes = []snmp.IndexShape{{Kind: snmp.IndexInteger}}

// decodeFakeSoloTableKey decodes the instance suffix of one fakeSoloTable row. ok is false
// when the suffix does not match the declared INDEX; the key is then zero.
func decodeFakeSoloTableKey(idx snmp.OID) (FakeSoloTableKey, bool) {
	var parts [1]snmp.IndexValue
	if !snmp.DecodeIndexInto(parts[:], idx, fakeSoloTableIndexShapes) {
		return FakeSoloTableKey{}, false
	}
	return FakeSoloTableKey{FakeSoloIndex: int32(parts[0].Integer)}, true
}

// FakeSoloTableRow is one table row; KeyValid reports index validity, use Observed for field presence, and concurrent reads are safe.
type FakeSoloTableRow struct {
	Key                FakeSoloTableKey
	keyValid           bool
	FakeSoloLastChange uint32
	observed           [1]uint64
}

// KeyValid reports whether Key decoded from the row index.
func (r FakeSoloTableRow) KeyValid() bool {
	return r.keyValid
}

// Observed reports whether col supplied this row field, including a zero value.
func (r FakeSoloTableRow) Observed(col snmp.AnyColumn) bool {
	return snmp.ColumnObserved(r.observed[:], fakeSoloTableColumns, col)
}

// FakeSoloTableWalker streams one table walk; its zero value is unusable, and Err/Close are safe concurrently.
type FakeSoloTableWalker struct {
	snmp.TableWalker[FakeSoloTableRow]
}
type fakeSoloTableT struct {
	snmp.Table[FakeSoloTableRow, *FakeSoloTableWalker]
}

// FakeSoloTable is the descriptor for the fakeSoloTable table.
//
// Deprecated: fakeSoloTable is STATUS deprecated in FAKE-MIB.
var FakeSoloTable = fakeSoloTableT{Table: snmp.NewTable("fakeSoloTable", fakeSoloTableColumns, func(idx snmp.OID, row *FakeSoloTableRow) {
	row.Key, row.keyValid = decodeFakeSoloTableKey(idx)
}, func(row *FakeSoloTableRow, ordinal int, rv snmp.RawVarBind) error {
	switch ordinal {
	case 0:
		return snmp.DecodeColumn(rv, FakeSoloLastChange, &row.FakeSoloLastChange, row.observed[:])
	}
	return nil
}, func(tw snmp.TableWalker[FakeSoloTableRow]) *FakeSoloTableWalker {
	return &FakeSoloTableWalker{TableWalker: tw}
})}

// Descriptor returns the table identity, change indicator, and row-key type.
func (fakeSoloTableT) Descriptor() snmp.TableDescriptor {
	return snmp.TableDescriptor{
		Indicator: FakeSoloTableIndicator,
		KeyType:   "FakeSoloTableKey",
		Root:      snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 19),
	}
}

// decodeFakeSoloTableRow decodes one row of FakeSoloTable from the supplied
// VarBinds. Each VarBind's OID determines which row field it populates
// (via the column's last sub-id). VarBinds with unknown column-ids are
// ignored. Absent columns leave their field at its zero value.
func decodeFakeSoloTableRow(idx snmp.OID, vbs []snmp.VarBind) (FakeSoloTableRow, error) {
	var row FakeSoloTableRow
	row.Key, row.keyValid = decodeFakeSoloTableKey(idx)

	for _, vb := range vbs {
		o := vb.GetHeader().OID
		if o.Len() == 0 {
			continue
		}
		entryLen := snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 19, 1).Len()
		if o.Len() <= entryLen {
			continue
		}
		colID := o.At(entryLen)
		if colID == 2 {
			dv, derr := FakeSoloLastChange.Decode(vb)
			if derr != nil {
				return row, derr
			}
			row.FakeSoloLastChange = dv
			row.observed[0] |= 1 << 0
		}
	}

	return row, nil
}

// equalFakeSoloTableRow compares two FakeSoloTableRow values for equality.
// Used by [snmp.Watcher] to compute ChangeKindModified emits. Field-by-
// field with the type-appropriate comparator (bytes.Equal for []byte,
// OID.Equal for OID, time.Time.Equal for time.Time, == for everything else).
func equalFakeSoloTableRow(a FakeSoloTableRow, b FakeSoloTableRow) bool {
	return a.Key == b.Key && a.keyValid == b.keyValid && a.observed == b.observed && a.FakeSoloLastChange == b.FakeSoloLastChange
}

// mergeFakeSoloTableRow merges the values decoded from vbs into dst, leaving fields
// whose columns are not present in vbs unchanged. Used by [snmp.Watcher]
// to maintain per-row state under partial-column fetches (Counter-tier,
// Static-tier). Best-effort: individual VarBind decode failures are
// silently skipped rather than propagated, because partial-fetch ticks
// surface transient errors through [snmp.Watcher.LastTickErr] at the
// call-site granularity rather than per-VarBind.
func mergeFakeSoloTableRow(dst *FakeSoloTableRow, vbs []snmp.VarBind) {
	for _, vb := range vbs {
		o := vb.GetHeader().OID
		if o.Len() == 0 {
			continue
		}
		entryLen := snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 19, 1).Len()
		if o.Len() <= entryLen {
			continue
		}
		colID := o.At(entryLen)
		if colID == 2 {
			dv, derr := FakeSoloLastChange.Decode(vb)
			if derr == nil {
				dst.FakeSoloLastChange = dv
				dst.observed[0] |= 1 << 0
			}
		}
	}
}

// FakeSoloTableWatcher is a table-aware Watcher over FakeSoloTable.
// The zero value is not usable; construct via FakeSoloTable.Watch(ctx, sess, cols, opts...).
// Use a single iterator. The other methods may be called concurrently.
type FakeSoloTableWatcher struct {
	w *snmp.Watcher[FakeSoloTableRow]
}

// Iter returns the range-over-func view of the Watcher's event stream.
// See [snmp.Watcher.Iter] for the contract.
func (tw *FakeSoloTableWatcher) Iter() iter.Seq2[snmp.OID, snmp.WatchEvent[FakeSoloTableRow]] {
	return tw.w.Iter()
}

// Err returns the underlying Watcher's terminal error, or nil if it
// completed naturally. See [snmp.Watcher.Err].
func (tw *FakeSoloTableWatcher) Err() error {
	return tw.w.Err()
}

// Close signals the Watcher's tick goroutine to terminate. Idempotent.
// See [snmp.Watcher.Close].
func (tw *FakeSoloTableWatcher) Close() error {
	return tw.w.Close()
}

// Fallback reports whether the Watcher has transitioned to fallback
// mode. See [snmp.Watcher.Fallback].
func (tw *FakeSoloTableWatcher) Fallback() bool {
	return tw.w.Fallback()
}

// LastTickErr returns the most-recent transient per-tick error.
// See [snmp.Watcher.LastTickErr].
func (tw *FakeSoloTableWatcher) LastTickErr() error {
	return tw.w.LastTickErr()
}

// TableRoot returns the OID of the table this Watcher operates over.
func (tw *FakeSoloTableWatcher) TableRoot() snmp.OID {
	return tw.w.TableRoot()
}

// Watch opens a long-lived watch on FakeSoloTable.
//
// cols selects the columns whose values are reported on every emitted
// event. opts override cadence bounds, per-column tier classifications,
// fallback behavior, and other policy — see [snmp.WatchOption] for the
// full set.
//
// cols is a slice rather than variadic because opts is variadic and
// Go forbids two variadic parameters.
//
// Events emitted on this stream:
//   - ChangeKindAdded    — Row populated, Prev always nil.
//   - ChangeKindModified — Row is current state. Prev is nil unless
//     the caller passed [snmp.WithPrevRow]; when
//     set, Prev carries the previous Row.
//   - ChangeKindRemoved  — Row carries the last-known state at the
//     time the row disappeared. Prev is nil.
//
// The returned Watcher must be Closed when the caller is done; iteration
// exit alone does not free the underlying goroutine until Close.
//
// On validation failure (invalid cadence bounds, tier override of the
// indicator column, etc.) Watch returns a Watcher whose Err() returns
// the cause immediately; range loops exit without emitting events and
// Close is a no-op.
func (fakeSoloTableT) Watch(ctx context.Context, sess snmp.Session, cols []snmp.AnyColumn, opts ...snmp.WatchOption) *FakeSoloTableWatcher {
	allOpts := append([]snmp.WatchOption{snmp.WithTierLookup(ColumnTier)}, opts...)
	w, _ := snmp.NewWatcher[FakeSoloTableRow](ctx, sess, FakeSoloTableIndicator, cols, decodeFakeSoloTableRow, equalFakeSoloTableRow, mergeFakeSoloTableRow, allOpts...)

	return &FakeSoloTableWatcher{w: w}
}

// fAKEMIBOIDDispatch maps column wire keys ([snmp.OID.WireKey]) to their
// typed AnyColumn for fast
// lookup during table-walk decoding. Per-MIB-module — no global
// registry; cross-package callers should consult OIDDispatch().
var fAKEMIBOIDDispatch = map[string]snmp.AnyColumn{
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 10, 1, 2).WireKey(): FakeOIDLabel,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 11, 1, 1).WireKey(): FakeAugExtra,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 12, 1, 1).WireKey(): FakeUnresolvedValue,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 13, 1, 1).WireKey(): FakeKeyAugExtra,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 14, 1, 1).WireKey(): FakeChainExtra,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 16, 1, 1).WireKey(): FakeBareAugExtra,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 17, 1, 2).WireKey(): FakeRefinedValue,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 19, 1, 2).WireKey(): FakeSoloLastChange,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 2).WireKey():  FakeName,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 3).WireKey():  FakeMAC,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 4).WireKey():  FakeOctets,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 5).WireKey():  FakeLastChange,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 6).WireKey():  FakeFlags,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 7).WireKey():  FakeRef,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 8).WireKey():  FakeMode,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 9).WireKey():  FakeDeprecated,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 4, 1, 2).WireKey():  FakeStackName,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 7, 1, 3).WireKey():  FakePairValue,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 8, 1, 2).WireKey():  FakeImpliedValue,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 9, 1, 2).WireKey():  FakeAddrLabel,
}

// OIDDispatch returns a shallow copy of the package's wire-key →
// AnyColumn map. The copy isolates callers from accidental mutation
// of the package-internal map.
func OIDDispatch() map[string]snmp.AnyColumn {
	out := make(map[string]snmp.AnyColumn, len(fAKEMIBOIDDispatch))
	for k, v := range fAKEMIBOIDDispatch {
		out[k] = v
	}
	return out
}

// fAKEMIBColumnTiers maps column wire keys ([snmp.OID.WireKey]) to their
// snmp.Tier classification.
// Tier classification drives the Watcher's scheduler — counters fire
// on their own cadence, state columns refresh on indicator advance,
// and indicator columns drive the change-detection probe itself.
// See snmp.Tier and snmp.Watcher for the consumption contract.
var fAKEMIBColumnTiers = map[string]snmp.Tier{
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 10, 1, 2).WireKey(): snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 11, 1, 1).WireKey(): snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 12, 1, 1).WireKey(): snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 13, 1, 1).WireKey(): snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 14, 1, 1).WireKey(): snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 16, 1, 1).WireKey(): snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 17, 1, 2).WireKey(): snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 19, 1, 2).WireKey(): snmp.TierCounter,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 2).WireKey():  snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 3).WireKey():  snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 4).WireKey():  snmp.TierCounter,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 5).WireKey():  snmp.TierIndicator,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 6).WireKey():  snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 7).WireKey():  snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 8).WireKey():  snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3, 1, 9).WireKey():  snmp.TierCounter,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 4, 1, 2).WireKey():  snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 7, 1, 3).WireKey():  snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 8, 1, 2).WireKey():  snmp.TierState,
	snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 9, 1, 2).WireKey():  snmp.TierState,
}

// ColumnTier returns the codegen-classified [snmp.Tier] for col, or
// snmp.TierUnknown when col's OID is not known to this package. The
// generated Watch methods install this function via
// [snmp.WithTierLookup]; returning TierUnknown lets the runtime fall
// back to its wire-Kind heuristic for columns this package does not
// classify. Caller overrides via [snmp.WithColumnTier] still win.
func ColumnTier(col snmp.AnyColumn) snmp.Tier {
	if col == nil {
		return snmp.TierUnknown
	}
	t, ok := fAKEMIBColumnTiers[col.Key()]
	if !ok {
		return snmp.TierUnknown
	}
	return t
}

// FakeSoloTableIndicator is the per-row change indicator for fakeSoloTable.
// The Watcher probes the indicator column on each tick and only
// re-fetches a row's other state-tier columns when the row's
// indicator value advances. See [snmp.NewPerRowIndicator] and
// [snmp.Watcher] for the consumption contract.
// Discovered by mibgen structural rule: per-row column name matches indicator-suffix heuristic.
var FakeSoloTableIndicator = snmp.MustChangeIndicator(snmp.NewPerRowIndicator(FakeSoloLastChange, snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 19)))

// FakeTableIndicator is the per-row change indicator for fakeTable.
// The Watcher probes the indicator column on each tick and only
// re-fetches a row's other state-tier columns when the row's
// indicator value advances. See [snmp.NewPerRowIndicator] and
// [snmp.Watcher] for the consumption contract.
// Discovered by mibgen structural rule: per-row column name matches indicator-suffix heuristic.
var FakeTableIndicator = snmp.MustChangeIndicator(snmp.NewPerRowIndicator(FakeLastChange, snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 3)))

// FakeStackTableIndicator is the scalar change indicator for fakeStackTable.
// The Watcher Gets fakeStackLastChange on each tick; when the value
// advances the full table is walked and diffed against the snapshot.
// See [snmp.NewScalarIndicator] and [snmp.Watcher] for the contract.
// Discovered by mibgen structural rule: scalar named after the table plus an indicator suffix.
var FakeStackTableIndicator = snmp.MustChangeIndicator(snmp.NewScalarIndicator(snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 5), snmp.KindTimeTicks, []snmp.OID{snmp.MustOID(1, 3, 6, 1, 4, 1, 99999, 1, 4)}))
