// Code generated by src/common/smi/internal/catalog/gen; DO NOT EDIT.
//
// The diagnostic table in internal/catalog is the source of truth.
// Append a row there and run `go generate ./src/common/smi/...`.

package smi

import "go.aledante.io/FlowSeer/src/common/errs"

// The diagnostic codes, one per catalog row. A code is a wire
// contract: append-only, never renamed, never reused for a different
// condition. Severity is not part of a code's identity and may be
// regraded; the code may not.
var (
	// ErrCodeHyphenSeparator marks a hyphen run whose length is 1 mod 4,
	// which pairs off into comments and leaves one stray minus token
	// behind.
	ErrCodeHyphenSeparator = errs.NewCode("smi/hyphen-separator")

	// ErrCodeLimitExceeded marks a declared resource limit being reached,
	// which costs the whole file so that pathological input costs bounded
	// work.
	ErrCodeLimitExceeded = errs.NewCode("smi/limit-exceeded")

	// ErrCodeMissingModuleHeader marks a file with no module header, which
	// costs the whole file because there is no module to attribute a
	// declaration to.
	ErrCodeMissingModuleHeader = errs.NewCode("smi/missing-module-header")

	// ErrCodeOddHexString marks a hexadecimal string literal with an odd
	// digit count, whose trailing nibble has no byte to land in.
	ErrCodeOddHexString = errs.NewCode("smi/odd-hex-string")

	// ErrCodeTrailingHyphenIdentifier marks an identifier ending in a
	// hyphen, which RFC 2578 forbids and which a stricter lexer reads as
	// the start of a comment.
	ErrCodeTrailingHyphenIdentifier = errs.NewCode("smi/trailing-hyphen-identifier")

	// ErrCodeUnrecognizedDeclaration marks a declaration the framer could
	// not classify, which costs that declaration and nothing around it.
	ErrCodeUnrecognizedDeclaration = errs.NewCode("smi/unrecognized-declaration")

	// ErrCodeUnterminatedComment marks a comment running to end of file,
	// which costs the whole file because no declaration boundary after it
	// can be trusted.
	ErrCodeUnterminatedComment = errs.NewCode("smi/unterminated-comment")

	// ErrCodeUnterminatedString marks a quoted string running to end of
	// file, one of the few conditions that costs the whole file because
	// nothing after the opening quote can be framed.
	ErrCodeUnterminatedString = errs.NewCode("smi/unterminated-string")
)
