#!/usr/bin/env python3
"""Entity taxonomy: regex patterns matched against MIB table names, MIB module names, YANG node paths."""

# entity id -> (domain, display name, [regex patterns matched case-insensitively])
TAXONOMY = [
 # ---- 0. Identity & platform ----
 ("system-identity",      "L0 Platform", "System identity",            [r'\bsysdescr|sysobjectid|sysname|syscontact|syslocation|sysuptime|system-?info|deviceinfo|swinfo|hwinfo']),
 ("hw-component",         "L0 Platform", "Hardware component tree",    [r'entphysical|physicalentity|component|entity-?ext|chassis|linecard|module-?info|slot|card(table|entry)|inventory']),
 ("transceiver",          "L0 Platform", "Transceiver / optics DOM",   [r'transceiver|sfp|xcvr|ddm|opticalmodule|dom(threshold|value)|gbic']),
 ("stacking",             "L0 Platform", "Stacking / virtual chassis", [r'stack|vsf|vsx|irf|vss|memberunit|clusterswitch|hgmp|single-?ip|drni|m-?lag|mclag|vpc\b|superlag']),
 ("power-supply",         "L0 Platform", "Power supply & budget",      [r'powersupply|psu|redundantpower|power-?stat|powerunit|powerentry']),
 ("environment",          "L0 Platform", "Environment sensors",        [r'sensor|temperature|tempsensor|fan(table|entry|tray)?|thermal|environment|hwenviro']),
 ("firmware-image",       "L0 Platform", "Firmware / image / boot",    [r'firmware|image|bootrom|softwareversion|upgrade|download|switch-?image|flash-?man']),
 ("config-file",          "L0 Platform", "Config file & backup",       [r'config-?man|configfile|copy-?mib|running-?config|startup|savecfg|tftp|backup|ztp|pnp\b']),
 ("license",              "L0 Platform", "Licensing",                  [r'license|licensing|smart-?license|gtl-?mib']),
 ("cpu-memory",           "L0 Platform", "CPU / memory / storage",     [r'cpu(-?util|-?counters|table)|memory|memproc|disk|cfcard|storage|procmon|res-?mon']),

 # ---- 1. Interfaces / PHY ----
 ("interface",            "L1 Interface","Interface (generic)",        [r'\bif(table|xtable|entry|index|name|descr|alias|type|mtu)|interfaces?/interface|ifmib|if-?ext|rlinterfaces']),
 ("if-counters",          "L1 Interface","Interface counters",         [r'ifhc(in|out)|ifin(octets|errors|discards|ucastpkts)|ifout(octets|errors)|port-?statistics|if-?counter|etherstats|dot3stats']),
 ("ethernet-phy",         "L1 Interface","Ethernet PHY / MAU",         [r'\bmau\b|dot3mau|autoneg|duplex|speed|ethernet(-?ext)?|etherlike|phy-?mib|linkspeed|medium']),
 ("eee",                  "L1 Interface","Energy Efficient Ethernet",  [r'\beee\b|energy-?efficient|dot3aeee|green-?mib|power-?saving|energymngt']),
 ("fec",                  "L1 Interface","FEC / link tuning",          [r'\bfec\b|forward-?error|pre-?fec']),
 ("poe",                  "L1 Interface","Power over Ethernet",        [r'pethmain|pethpse|poe|power-?eth|pse-?port|powerethernet']),
 ("subinterface",         "L1 Interface","Subinterface",               [r'subinterface|sub-?if|vlanterm|ifsub']),
 ("lag",                  "L1 Interface","Link aggregation group",     [r'\blag\b|dot3ad|aggregat|trunk-?mib|port-?channel|etherchannel|if-?aggregate|smartlink-?group']),
 ("lacp",                 "L1 Interface","LACP protocol state",        [r'lacp|dot3adagg(port|actor|partner)']),
 ("tunnel-if",            "L1 Interface","Tunnel interfaces",          [r'tunnel|\bgre\b|ipip|l2tp|vxlan|nvgre|dvpn|ipv6-?tunnel']),
 ("loopback-if",          "L1 Interface","Loopback interface",         [r'loopback(?!-?detect|-?test)']),
 ("mgmt-if",              "L1 Interface","Management interface",       [r'mnginf|management-?interface|oobm|mgmt-?if']),
 ("cable-diag",           "L1 Interface","Cable diagnostics / TDR",    [r'cable-?diag|tdr|vct|virtualcable|loopback-?test|linktest']),
 ("link-oam",             "L1 Interface","Ethernet link OAM (802.3ah)",[r'dot3oam|efm|ethoam|link-?oam']),
 ("udld",                 "L1 Interface","UDLD / DLDP",                [r'udld|dldp|dul[dp]']),

 # ---- 2. Switching ----
 ("vlan",                 "L2 Switching","VLAN database",              [r'vlanstatic|dot1qvlan|vlan(table|entry|current|id)|vlan-?mib|lswvlan|l2vlan|vlangroup']),
 ("vlan-membership",      "L2 Switching","Port VLAN membership / PVID",[r'egressports|untaggedports|dot1qpvid|dot1qport|portvlan|switchport|pvid|vlanport']),
 ("qinq",                 "L2 Switching","QinQ / provider bridge",     [r'qinq|provider-?bridge|dot1ad|pb-?mib|vlan-?tunnel|vlan-?translat|\bpbb\b']),
 ("fdb",                  "L2 Switching","MAC forwarding database",    [r'dot1dtpfdb|dot1qtpfdb|fdb|l2fdb|macaddress(table)?|mactable|\bcam-?mib|l2mam|mam-?mib|mac-?notif|macnotify']),
 ("stp",                  "L2 Switching","Spanning tree",              [r'dot1dstp|\bstp\b|rstp|mstp|pvst|rpvst|spanning-?tree|vbst|specialbpdu']),
 ("loop-protect",         "L2 Switching","Loop / BPDU protection",     [r'loop-?protect|loopback-?detect|\blbd\b|loopdetect|bpdu-?protect|ldt-?mib|mflp|\bldt\b']),
 ("lldp",                 "L2 Switching","LLDP",                       [r'lldp']),
 ("cdp-like",             "L2 Switching","CDP & other discovery",      [r'\bcdp\b|isdp|\bfdp\b|\bedp\b|ptopo|nbf-?mib|ddp-?client|bonjour|mdns|discovery']),
 ("igmp-snooping",        "L2 Switching","IGMP/MLD snooping",          [r'igmpsnoop|igsp|mgmd-?snooping|multicast-?snooping|mld-?snoop|snooping']),
 ("mvr",                  "L2 Switching","Multicast VLAN registration",[r'\bmvr\b|mcast-?vlan|multicast-?vlan|mvlan']),
 ("storm-control",        "L2 Switching","Storm control / rate limit", [r'storm|broadcast-?(limit|suppress)|rate-?limit|\bcar-?mib|connection-?rate']),
 ("mirroring",            "L2 Switching","Port mirroring / SPAN",      [r'mirror|\bspan-?mib|rspan|erspan|packet-?monitor|\bmir-?mib']),
 ("port-isolation",       "L2 Switching","Port isolation / PVLAN",     [r'private-?vlan|protectedports|l2isolate|traffic-?segment|port-?isolat|\bpvlan']),
 ("garp",                 "L2 Switching","GVRP / MVRP / MRP",          [r'gvrp|mvrp|garp|\bmirp|\bmrp-?mib|dot1qgarp']),
 ("voice-vlan",           "L2 Switching","Voice / auto VLAN",          [r'voice-?vlan|vlanvoice|surveillance-?vlan|auto-?vlan|autovoip|smartport|protocol-?vlan|subnet-?vlan|super-?vlan|mac-?vlan']),
 ("ring-protection",      "L2 Switching","Ring protection (ERPS/RRPP)",[r'erps|rrpp|smart-?link|smlk|flexlinks|\brpr-?mib']),
 ("macsec",               "L2 Switching","MACsec (802.1AE)",           [r'macsec|secy|dot1ae']),
 ("fabric-overlay",       "L2 Switching","Fabric / overlay (VXLAN,SPB)",[r'trill|\bspb-?|vxlan|evpn|nvo3|\bevi-?mib|\bevc-?mib|vsi-?mib|\bvpls|\bvpws|pwe3|l2vpn']),
 ("l2pt",                 "L2 Switching","L2 protocol tunneling",      [r'l2pt|l2-?protocol-?tunnel']),
 ("jumbo-mtu",            "L2 Switching","Jumbo frames / MTU",         [r'jumbo|max-?frame|\bmtu\b']),

 # ---- 3. L3 ----
 ("ip-address",           "L3 IP",      "IP interface addressing",     [r'ipaddrtable|ipaddresstable|ipv6addr|ip-?address-?mib|ipconfig|inetcidr|if-?ip|ipv4-?address']),
 ("arp-nd",               "L3 IP",      "ARP / IPv6 ND cache",         [r'ipnettomedia|ipnettophysical|\barp\b|etharp|neighbor-?cache|\bnd-?mib|ipv6nettomedia']),
 ("rib-fib",              "L3 IP",      "Routing table / FIB / AFT",   [r'iproutetable|ipcidrroute|inetcidrroute|ipforward|routing-?table|\baft\b|\brib\b|fibtable|unicast-?mib']),
 ("static-route",         "L3 IP",      "Static routes / local routing",[r'static-?route|local-?routing|ippreflist']),
 ("vrf",                  "L3 IP",      "VRF / network instance",      [r'\bvrf|network-?instance|l3vpn|mpls-?vpn|context-?mib|\bmdc-?mib|virtual-?system|\bvs-?mib']),
 ("rip",                  "L3 Routing", "RIP",                         [r'\brip\b|ripv2|ripng']),
 ("ospf",                 "L3 Routing", "OSPF v2/v3",                  [r'ospf']),
 ("isis",                 "L3 Routing", "IS-IS",                       [r'isis']),
 ("bgp",                  "L3 Routing", "BGP",                         [r'\bbgp']),
 ("eigrp",                "L3 Routing", "EIGRP",                       [r'eigrp']),
 ("multicast-routing",    "L3 Routing", "PIM / DVMRP / MSDP / mroute", [r'\bpim\b|dvmrp|msdp|ipmroute|mgmd|multicast-?routing|ipmcast']),
 ("bfd",                  "L3 Routing", "BFD",                         [r'\bbfd\b']),
 ("mpls",                 "L3 Routing", "MPLS / LDP / RSVP-TE / SR",   [r'mpls|\bldp\b|rsvp|segment-?routing|\bsrv6|srpolicy|srte']),
 ("vrrp",                 "L3 IP",      "VRRP / gateway redundancy",   [r'vrrp|hsrp|glbp|vsrp|xrrp|vgmp|e-?trunk|failover|\bha-?mib']),
 ("nat",                  "L3 IP",      "NAT",                         [r'\bnat-?|napt|\bnat\b']),
 ("routing-policy",       "L3 IP",      "Route maps / policy routing", [r'route-?map|routemap|\bpbr\b|routing-?policy|policy-?forwarding|route-?policy|redistribute|prefix-?list|defined-?sets']),
 ("dhcp",                 "L3 IP",      "DHCP client/server/relay",    [r'dhcp']),
 ("dns",                  "L3 IP",      "DNS resolver / server",       [r'\bdns']),
 ("ip-diagnostics",       "L3 IP",      "Ping / traceroute / SLA",     [r'disman-?(ping|traceroute)|ip-?sla|\bnqa\b|twamp|ce-?ping|ipfpm|\bifit\b|probes']),
 ("l2-security-guard",    "L3 IP",      "DAI / IP source guard / RA guard",[r'source-?guard|\bdai-?mib|arp-?(protect|inspect|ratelimit|source)|impb|ra-?guard|nd-?inspect|ipv6-?snooping|urpf|savi|\bsava|dhcp-?filter|mff-?mib']),
 ("icmp-tcp-udp",         "L3 IP",      "ICMP / TCP / UDP stack",      [r'icmp|tcp-?mib|udp-?mib|tcpsessions|\bsocket']),

 # ---- 4. QoS ----
 ("qos-policy",           "QoS",        "QoS classification & policy", [r'\bqos|cbqos|ifqos|hqos|xqos|policy-?mib|diffserv|dscp|class-?map|policy-?map|qos-?profile']),
 ("qos-queue",            "QoS",        "Queues / schedulers / WRED",  [r'queue|wred|wrtd|weightedrandom|scheduler|shaper|\bcos-?mib|priority-?queue|fqtss|\bpfc-?mib']),
 ("acl",                  "QoS",        "ACLs",                        [r'\bacl|access-?list|ipstdacl|cpu-?acl|acfp|packet-?match|defined-?sets|time-?range|timerange']),

 # ---- 5. Security & AAA ----
 ("dot1x",                "Security",   "802.1X / port access",        [r'dot1x|\bpae-?mib|port-?access|\bmab\b|mac-?auth|web-?auth|jwac|network-?access|authentication-?manager|portal-?mib|wba-?mib|captive-?portal']),
 ("aaa",                  "Security",   "AAA / RADIUS / TACACS",       [r'\baaa|radius|tacacs|hwtacacs|ldap-?client|local-?aaa|\brbac|user-?mib|autz|user-?auth|domain-?mib|\buser6?-?mib']),
 ("port-security",        "Security",   "Port security / DoS guard",   [r'port-?security|portsecurity|denialofservice|dos-?prevent|safeguard|cpu-?protect|sechigh|security-?suite|secstat|bridge-?security|macbind|llpf|network-?protocol-?port-?protect|atk-?mib']),
 ("firewall",             "Security",   "Firewall / sessions / VPN",   [r'firewall|\bipsec|\bike-?|sslvpn|\baspf|session-?mib|ipsession|zone-?defense|szone|\bids-?mib|\bli-?mib']),
 ("pki-crypto",           "Security",   "PKI / certificates / crypto", [r'\bpki|certificate|\bssl-?mib|\bssh-?mib|crypto|digitalkey|keying|keychain|masterkey|\brsa-?mib|\btrng']),

 # ---- 6. Wireless ----
 ("wlan-controller",      "Wireless",   "Wireless controller / mgmt",  [r'wlsx-?switch|ap-?manager|capwap|unimng|wlan-?global|zd-?system|sz-?system|ctrl-?mib|wlan-?configuration']),
 ("access-point",         "Wireless",   "Access point",                [r'access-?points?|\bap-?mib|apmt|ap-?service|wlsr-?ap|ai-?ap|zd-?ap|ap-?update|dot11-?apmt']),
 ("radio",                "Wireless",   "Radio (802.11 PHY)",          [r'radio|wifi-?phy|dot11phy|dot11-?rrm|\brrm\b|\brf-?']),
 ("bss-vap",              "Wireless",   "BSS / VAP / SSID profile",    [r'\bvap\b|\bbss\b|\bssid|wlan-?config|wlan-?mib|dot11-?cfg|essid']),
 ("wireless-client",      "Wireless",   "Wireless client / station",   [r'station|\bsta-?|wlan-?station|dot11-?acmt|user-?table|wlsx-?user|client(table|entry)|ap-?client|assoc']),
 ("wireless-rf",          "Wireless",   "RF management / neighbors",   [r'\barm\b|channel|\brf-?mgmt|\bsnr-?mib|noise|interference|dot11-?probe|peerlist']),
 ("rogue-wids",           "Wireless",   "Rogue AP / WIDS / WIPS",      [r'rogue|wids|wips|\bmon-?mib|\brs-?mib|air-?monitor']),
 ("mesh",                 "Wireless",   "Wireless mesh",               [r'mesh']),
 ("roaming",              "Wireless",   "Roaming / mobility",          [r'roam|mobility|\bha-?mib|tunnelednode']),
 ("wireless-guest",       "Wireless",   "Guest access / hotspot",      [r'guest|hotspot|captive|\bwba|walled']),
 ("app-visibility",       "Wireless",   "Application visibility",      [r'\bavc\b|\bdpi\b|\bdar-?mib|app(lication)?-?visib|nbar']),

 # ---- 7. Telemetry & ops ----
 ("snmp-agent",           "Ops",        "SNMP agent / v3 / traps",     [r'snmp(v2|v3)?-?(mib|framework|target|notification|usm|vacm|community|proxy|mpd)|snmp-?ext|snmp-?agent']),
 ("syslog-events",        "Ops",        "Syslog / event log / alarms", [r'syslog|infocenter|notification-?log|event(s)?-?mib|alarm|trap-?mib|userlog|\bslog|itu-?alarm']),
 ("rmon",                 "Ops",        "RMON / SMON / history",       [r'rmon|smon|history|etherhistory|alarm-?table']),
 ("flow-export",          "Ops",        "sFlow / NetFlow / IPFIX",     [r'sflow|netflow|netstream|ipfix|flowtemplate|bulkstat']),
 ("time-sync",            "Ops",        "NTP / SNTP / PTP",            [r'\bntp|sntp|\bptp|timesynchron|clock-?mib|sys-?clock']),
 ("netconf-telemetry",    "Ops",        "NETCONF / gNMI / telemetry",  [r'netconf|restconf|\bgnmi|telemetry|yang-?push|subscription']),
 ("scheduling-automation","Ops",        "Task scheduling / EEM",       [r'schedule|\beem\b|task-?mib|autorun|timebased|time-?range']),
 ("openflow-sdn",         "Ops",        "OpenFlow / SDN",              [r'openflow|\bofp-?mib|\bsdn']),
 ("host-resources",       "Ops",        "Host resources / apps",       [r'host-?resources|sysappl|network-?services|hrsw|hrstorage']),

 # ---- 8. WAN / access ----
 ("wan-serial",           "WAN",        "Serial / TDM / ATM / FR",     [r'\bds1|\bds3|\be1-?mib|\bt1-?mib|sonet|\batm-?|frame-?relay|\bfr-?qos|isdn|\bppp|sdlc|\bpos-?|\bima-?mib|tdm-?psn']),
 ("dsl",                  "WAN",        "DSL (ADSL/VDSL/SHDSL)",       [r'adsl|vdsl|shdsl|gbond']),
 ("pon",                  "WAN",        "PON (EPON/GPON)",             [r'\bepon|xpon|gpon|\bolt-?|\bonu-?|ufiber']),
 ("docsis",               "WAN",        "Cable / DOCSIS",              [r'docs-?|docsis|catv|\beoc-?']),
 ("cellular",             "WAN",        "Cellular / 3G/LTE",           [r'3gmodem|\blte-?|cellular|\bgsm|\bwwan']),
 ("bras",                 "WAN",        "BRAS / subscriber mgmt",      [r'bras|pppoe|\bipa-?mib|ippool|user-?vlan|cupm']),
 ("fibre-channel",        "WAN",        "Fibre Channel / FCoE",        [r'\bfc-?|fcoe|fcmgmt|\bfdmi|vsan|\bnpv-?mib|san-?agg']),
]
