// Code generated by yanggen. DO NOT EDIT.
// generator: yanggen-6
// module: fixture-main revision: 2026-01-02
// source sha256: 0d1ec5bd7e28eea85599e728721578f2a79cf4cb3e26eb7ff6e6128fefa6d96d

// Package fixturemain binds the YANG module fixture-main.
package fixturemain

import (
	yang "go.aledante.io/FlowSeer/src/protocol/yang"
	fixtureaug "go.aledante.io/FlowSeer/src/protocol/yang/cmd/yanggen/testdata/golden/fixture/fixtureaug"
	fixtureaug2 "go.aledante.io/FlowSeer/src/protocol/yang/cmd/yanggen/testdata/golden/fixture/fixtureaug2"
)

// moduleFixtureAug identifies the fixture-aug YANG module.
var moduleFixtureAug = &yang.Module{
	Name:      "fixture-aug",
	Namespace: "urn:flowseer:fixture-aug",
}

// moduleFixtureAug2 identifies the fixture-aug2 YANG module.
var moduleFixtureAug2 = &yang.Module{
	Name:      "fixture-aug2",
	Namespace: "urn:flowseer:fixture-aug2",
}

// moduleFixtureMain identifies the fixture-main YANG module.
var moduleFixtureMain = &yang.Module{
	Name:      "fixture-main",
	Namespace: "urn:flowseer:fixture-main",
}

// AlarmState is the fixture-main node /fixture-main:alarm-state.
type AlarmState struct {
	Count *uint32
}

// AlarmStateSchema describes AlarmState for the generic codecs.
var AlarmStateSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Count", Name: "count", Type: yang.TUint32},
	},
	Module: moduleFixtureMain,
	Name:   "alarm-state",
}

// AlarmStateXa0728a is the fixture-main node /fixture-main:alarmState.
type AlarmStateXa0728a struct {
	Count *uint32
}

// AlarmStateSchemaXa270cf describes AlarmStateXa0728a for the generic codecs.
var AlarmStateSchemaXa270cf = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Count", Name: "count", Type: yang.TUint32},
	},
	Module: moduleFixtureMain,
	Name:   "alarmState",
}

// Binding is the fixture-main node /fixture-main:bindings/binding.
type Binding struct {
	ServerRef *string
	Weight    *uint8
}

// BindingSchema describes Binding for the generic codecs.
var BindingSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "ServerRef", Name: "server-ref", Type: yang.TString},
		{GoName: "Weight", Name: "weight", Type: yang.TUint8},
	},
	Keys:   []string{"server-ref"},
	Module: moduleFixtureMain,
	Name:   "binding",
}

// Bindings is the fixture-main node /fixture-main:bindings.
type Bindings struct {
	Binding []Binding
}

// BindingsSchema describes Bindings for the generic codecs.
var BindingsSchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: BindingSchema, GoName: "Binding", List: true, Name: "binding"},
	},
	Module: moduleFixtureMain,
	Name:   "bindings",
}

// ByModuleA is the fixture-main node /fixture-main:shape-probe/by-module-a.
type ByModuleA struct {
	Slot *ByModuleASlot
}

// ByModuleASchema describes ByModuleA for the generic codecs.
var ByModuleASchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: ByModuleASlotSchema, GoName: "Slot", Name: "slot"},
	},
	Module: moduleFixtureMain,
	Name:   "by-module-a",
}

// ByModuleASlot is the fixture-main node /fixture-main:shape-probe/by-module-a/slot.
type ByModuleASlot struct {
	Value *uint32
}

// ByModuleASlotSchema describes ByModuleASlot for the generic codecs.
var ByModuleASlotSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Value", Name: "value", Type: yang.TUint32},
	},
	Module: moduleFixtureMain,
	Name:   "slot",
}

// ByModuleB is the fixture-main node /fixture-main:shape-probe/by-module-b.
type ByModuleB struct {
	Slot *ByModuleBSlot
}

// ByModuleBSchema describes ByModuleB for the generic codecs.
var ByModuleBSchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: ByModuleBSlotSchema, GoName: "Slot", Name: "slot"},
	},
	Module: moduleFixtureMain,
	Name:   "by-module-b",
}

// ByModuleBSlot is the fixture-main node /fixture-main:shape-probe/by-module-b/slot.
type ByModuleBSlot struct {
	FixtureAug *fixtureaug.SlotAugment
}

// ByModuleBSlotSchema describes ByModuleBSlot for the generic codecs.
var ByModuleBSlotSchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: fixtureaug.SlotAugmentSchema, GoName: "FixtureAug", Group: true},
	},
	Module: moduleFixtureMain,
	Name:   "slot",
}

// ByOwnerA is the fixture-main node /fixture-main:shape-probe/by-owner-a.
type ByOwnerA struct {
	Flag *Flag
}

// ByOwnerASchema describes ByOwnerA for the generic codecs.
var ByOwnerASchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: FlagSchema, GoName: "Flag", Name: "flag"},
	},
	Module: moduleFixtureMain,
	Name:   "by-owner-a",
}

// ByOwnerB is the fixture-main node /fixture-main:shape-probe/by-owner-b.
type ByOwnerB struct {
	FixtureAug *fixtureaug.ByOwnerBAugment
}

// ByOwnerBSchema describes ByOwnerB for the generic codecs.
var ByOwnerBSchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: fixtureaug.ByOwnerBAugmentSchema, GoName: "FixtureAug", Group: true},
	},
	Module: moduleFixtureMain,
	Name:   "by-owner-b",
}

// ByPresenceA is the fixture-main node /fixture-main:shape-probe/by-presence-a.
type ByPresenceA struct {
	Marker *ByPresenceAMarker
}

// ByPresenceASchema describes ByPresenceA for the generic codecs.
var ByPresenceASchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: ByPresenceAMarkerSchema, GoName: "Marker", Name: "marker"},
	},
	Module: moduleFixtureMain,
	Name:   "by-presence-a",
}

// ByPresenceAMarker is the fixture-main node /fixture-main:shape-probe/by-presence-a/marker.
type ByPresenceAMarker struct {
	Value *uint32
}

// ByPresenceAMarkerSchema describes ByPresenceAMarker for the generic codecs.
var ByPresenceAMarkerSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Value", Name: "value", Type: yang.TUint32},
	},
	Module: moduleFixtureMain,
	Name:   "marker",
}

// ByPresenceB is the fixture-main node /fixture-main:shape-probe/by-presence-b.
type ByPresenceB struct {
	Marker *ByPresenceBMarker
}

// ByPresenceBSchema describes ByPresenceB for the generic codecs.
var ByPresenceBSchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: ByPresenceBMarkerSchema, GoName: "Marker", Name: "marker"},
	},
	Module: moduleFixtureMain,
	Name:   "by-presence-b",
}

// ByPresenceBMarker is the fixture-main node /fixture-main:shape-probe/by-presence-b/marker.
type ByPresenceBMarker struct {
	Value *uint32
}

// ByPresenceBMarkerSchema describes ByPresenceBMarker for the generic codecs.
var ByPresenceBMarkerSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Value", Name: "value", Type: yang.TUint32},
	},
	Module:   moduleFixtureMain,
	Name:     "marker",
	Presence: true,
}

// ByTypeA is the fixture-main node /fixture-main:shape-probe/by-type-a.
type ByTypeA struct {
	Setting *ByTypeASetting
}

// ByTypeASchema describes ByTypeA for the generic codecs.
var ByTypeASchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: ByTypeASettingSchema, GoName: "Setting", Name: "setting"},
	},
	Module: moduleFixtureMain,
	Name:   "by-type-a",
}

// ByTypeASetting is the fixture-main node /fixture-main:shape-probe/by-type-a/setting.
type ByTypeASetting struct {
	Value *uint32
}

// ByTypeASettingSchema describes ByTypeASetting for the generic codecs.
var ByTypeASettingSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Value", Name: "value", Type: yang.TUint32},
	},
	Module: moduleFixtureMain,
	Name:   "setting",
}

// ByTypeB is the fixture-main node /fixture-main:shape-probe/by-type-b.
type ByTypeB struct {
	Setting *ByTypeBSetting
}

// ByTypeBSchema describes ByTypeB for the generic codecs.
var ByTypeBSchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: ByTypeBSettingSchema, GoName: "Setting", Name: "setting"},
	},
	Module: moduleFixtureMain,
	Name:   "by-type-b",
}

// ByTypeBSetting is the fixture-main node /fixture-main:shape-probe/by-type-b/setting.
type ByTypeBSetting struct {
	Value *string
}

// ByTypeBSettingSchema describes ByTypeBSetting for the generic codecs.
var ByTypeBSettingSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Value", Name: "value", Type: yang.TString},
	},
	Module: moduleFixtureMain,
	Name:   "setting",
}

// Endpoint is the fixture-main node /fixture-main:servers/server/endpoint.
type Endpoint struct {
	Address *string
	Enabled *bool
	Port    *uint16
}

// EndpointSchema describes Endpoint for the generic codecs.
var EndpointSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Address", Name: "address", Type: yang.TString},
		{GoName: "Enabled", Name: "enabled", Type: yang.TBool},
		{GoName: "Port", Name: "port", Type: yang.TUint16},
	},
	Keys:   []string{"address", "port"},
	Module: moduleFixtureMain,
	Name:   "endpoint",
}

// Flag is the fixture-main node /fixture-main:shape-probe/by-owner-a/flag.
type Flag struct{}

// FlagSchema describes Flag for the generic codecs.
var FlagSchema = &yang.Schema{
	Fields: []yang.Field{},
	Module: moduleFixtureMain,
	Name:   "flag",
}

// FromSubmodule is the fixture-main node /fixture-main:from-submodule.
type FromSubmodule struct {
	Label *string
}

// FromSubmoduleSchema describes FromSubmodule for the generic codecs.
var FromSubmoduleSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Label", Name: "label", Type: yang.TString},
	},
	Module: moduleFixtureMain,
	Name:   "from-submodule",
}

// Item is the fixture-main node shape instantiated at 2 schema paths, such as /fixture-main:primary-group/item.
type Item struct {
	BufferSize *uint32
}

// ItemSchema describes Item for the generic codecs.
var ItemSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "BufferSize", Name: "buffer-size", Type: yang.TUint32},
	},
	Module: moduleFixtureMain,
	Name:   "item",
}

// Key is the fixture-main node /fixture-main:servers/server/key.
type Key struct {
	ID *string
}

// KeySchema describes Key for the generic codecs.
var KeySchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "ID", Name: "id", Type: yang.TString},
	},
	Module: moduleFixtureMain,
	Name:   "key",
}

// Peer is the fixture-main node shape instantiated at 2 schema paths, such as /fixture-main:primary-group/peer.
type Peer struct {
	Name   *string
	Weight *uint8
}

// PeerSchema describes Peer for the generic codecs.
var PeerSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Name", Name: "name", Type: yang.TString},
		{GoName: "Weight", Name: "weight", Type: yang.TUint8},
	},
	Keys:   []string{"name"},
	Module: moduleFixtureMain,
	Name:   "peer",
}

// PrimaryGroup is the fixture-main node /fixture-main:primary-group.
type PrimaryGroup struct {
	Item *Item
	Peer []Peer
}

// PrimaryGroupSchema describes PrimaryGroup for the generic codecs.
var PrimaryGroupSchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: ItemSchema, GoName: "Item", Name: "item"},
		{Child: PeerSchema, GoName: "Peer", List: true, Name: "peer"},
	},
	Module: moduleFixtureMain,
	Name:   "primary-group",
}

// Schema is the fixture-main node /fixture-main:servers/schema.
type Schema struct {
	Version *string
}

// SchemaSchema describes Schema for the generic codecs.
var SchemaSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Version", Name: "version", Type: yang.TString},
	},
	Module: moduleFixtureMain,
	Name:   "schema",
}

// SecondaryGroup is the fixture-main node /fixture-main:secondary-group.
type SecondaryGroup struct {
	Item *Item
	Peer []Peer
}

// SecondaryGroupSchema describes SecondaryGroup for the generic codecs.
var SecondaryGroupSchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: ItemSchema, GoName: "Item", Name: "item"},
		{Child: PeerSchema, GoName: "Peer", List: true, Name: "peer"},
	},
	Module: moduleFixtureMain,
	Name:   "secondary-group",
}

// Servers is the fixture-main node /fixture-main:servers.
type Servers struct {
	Schema       *Schema
	Server       []ServersServer
	ServerSchema *ServersServerSchema
	FixtureAug2  *fixtureaug2.ServersAugment
}

// ServersSchema describes Servers for the generic codecs.
var ServersSchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: SchemaSchema, GoName: "Schema", Name: "schema"},
		{Child: ServersServerSchemaX24fddd, GoName: "Server", List: true, Name: "server"},
		{Child: ServersServerSchemaSchema, GoName: "ServerSchema", Name: "server-schema"},
		{Child: fixtureaug2.ServersAugmentSchema, GoName: "FixtureAug2", Group: true},
	},
	Module: moduleFixtureMain,
	Name:   "servers",
}

// ServersServer is the fixture-main node /fixture-main:servers/server.
type ServersServer struct {
	Endpoint    []Endpoint
	Key         *Key
	Listen      *yang.Value
	Name        *string
	Port        *uint16
	Proto       *yang.Identity
	Ratio       *yang.Value
	TLS         *TLS
	FixtureAug  *fixtureaug.ServerAugment
	FixtureAug2 *fixtureaug2.ServerAugment
}

// ServersServerSchemaX24fddd describes ServersServer for the generic codecs.
var ServersServerSchemaX24fddd = &yang.Schema{
	Fields: []yang.Field{
		{Child: EndpointSchema, GoName: "Endpoint", List: true, Name: "endpoint"},
		{Child: KeySchema, GoName: "Key", Name: "key"},
		{GoName: "Listen", Name: "listen", Type: &yang.Type{
			Kind:    yang.TypeUnion,
			Members: []yang.Type{{Kind: yang.TypeUint16}, {Kind: yang.TypeString}},
		}},
		{GoName: "Name", Name: "name", Type: yang.TString},
		{GoName: "Port", Name: "port", Type: yang.TUint16},
		{GoName: "Proto", Name: "proto", Type: yang.TIdentity},
		{GoName: "Ratio", Name: "ratio", Type: &yang.Type{
			FractionDigits: 3,
			Kind:           yang.TypeDecimal64,
		}},
		{Child: TLSSchema, GoName: "TLS", Name: "tls"},
		{Child: fixtureaug.ServerAugmentSchema, GoName: "FixtureAug", Group: true},
		{Child: fixtureaug2.ServerAugmentSchema, GoName: "FixtureAug2", Group: true},
	},
	Keys:   []string{"name"},
	Module: moduleFixtureMain,
	Name:   "server",
}

// ServersServerSchema is the fixture-main node /fixture-main:servers/server-schema.
type ServersServerSchema struct {
	Note *string
}

// ServersServerSchemaSchema describes ServersServerSchema for the generic codecs.
var ServersServerSchemaSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Note", Name: "note", Type: yang.TString},
	},
	Module: moduleFixtureMain,
	Name:   "server-schema",
}

// ShapeProbe is the fixture-main node /fixture-main:shape-probe.
type ShapeProbe struct {
	ByModuleA   *ByModuleA
	ByModuleB   *ByModuleB
	ByOwnerA    *ByOwnerA
	ByOwnerB    *ByOwnerB
	ByPresenceA *ByPresenceA
	ByPresenceB *ByPresenceB
	ByTypeA     *ByTypeA
	ByTypeB     *ByTypeB
}

// ShapeProbeSchema describes ShapeProbe for the generic codecs.
var ShapeProbeSchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: ByModuleASchema, GoName: "ByModuleA", Name: "by-module-a"},
		{Child: ByModuleBSchema, GoName: "ByModuleB", Name: "by-module-b"},
		{Child: ByOwnerASchema, GoName: "ByOwnerA", Name: "by-owner-a"},
		{Child: ByOwnerBSchema, GoName: "ByOwnerB", Name: "by-owner-b"},
		{Child: ByPresenceASchema, GoName: "ByPresenceA", Name: "by-presence-a"},
		{Child: ByPresenceBSchema, GoName: "ByPresenceB", Name: "by-presence-b"},
		{Child: ByTypeASchema, GoName: "ByTypeA", Name: "by-type-a"},
		{Child: ByTypeBSchema, GoName: "ByTypeB", Name: "by-type-b"},
	},
	Module: moduleFixtureMain,
	Name:   "shape-probe",
}

// TLS is the fixture-main node /fixture-main:servers/server/tls.
type TLS struct {
	MinVersion *string
}

// TLSSchema describes TLS for the generic codecs.
var TLSSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "MinVersion", Name: "min-version", Type: yang.TEnum},
	},
	Module:   moduleFixtureMain,
	Name:     "tls",
	Presence: true,
}

// BindingKey is Binding's row identity (ancestor keys in canonical form).
type BindingKey struct {
	ServerRef string
}

// BindingDescriptor is the list descriptor callers hand to a protocol library.
func BindingDescriptor() yang.ListDescriptor[Binding, BindingKey] {
	return yang.ListDescriptor[Binding, BindingKey]{
		Codec: yang.StructRowCodec(BindingSchema, func(r *Binding) BindingKey {
			var k BindingKey
			if r.ServerRef != nil {
				k.ServerRef = *r.ServerRef
			}
			return k
		}),
		Path: yang.JoinPath(yang.In(moduleFixtureMain, "bindings", "binding")),
	}
}

// PrimaryGroupPeerKey is Peer's row identity (ancestor keys in canonical form).
type PrimaryGroupPeerKey struct {
	Name string
}

// PrimaryGroupPeerDescriptor is the list descriptor callers hand to a protocol library.
func PrimaryGroupPeerDescriptor() yang.ListDescriptor[Peer, PrimaryGroupPeerKey] {
	return yang.ListDescriptor[Peer, PrimaryGroupPeerKey]{
		Codec: yang.StructRowCodec(PeerSchema, func(r *Peer) PrimaryGroupPeerKey {
			var k PrimaryGroupPeerKey
			if r.Name != nil {
				k.Name = *r.Name
			}
			return k
		}),
		Path: yang.JoinPath(yang.In(moduleFixtureMain, "primary-group", "peer")),
	}
}

// SecondaryGroupPeerKey is Peer's row identity (ancestor keys in canonical form).
type SecondaryGroupPeerKey struct {
	Name string
}

// SecondaryGroupPeerDescriptor is the list descriptor callers hand to a protocol library.
func SecondaryGroupPeerDescriptor() yang.ListDescriptor[Peer, SecondaryGroupPeerKey] {
	return yang.ListDescriptor[Peer, SecondaryGroupPeerKey]{
		Codec: yang.StructRowCodec(PeerSchema, func(r *Peer) SecondaryGroupPeerKey {
			var k SecondaryGroupPeerKey
			if r.Name != nil {
				k.Name = *r.Name
			}
			return k
		}),
		Path: yang.JoinPath(yang.In(moduleFixtureMain, "secondary-group", "peer")),
	}
}

// MirrorKey is Mirror's row identity (ancestor keys in canonical form).
type MirrorKey struct {
	ID string
}

// MirrorDescriptor is the list descriptor callers hand to a protocol library.
func MirrorDescriptor() yang.ListDescriptor[fixtureaug2.Mirror, MirrorKey] {
	return yang.ListDescriptor[fixtureaug2.Mirror, MirrorKey]{
		Codec: yang.StructRowCodec(fixtureaug2.MirrorSchema, func(r *fixtureaug2.Mirror) MirrorKey {
			var k MirrorKey
			if r.ID != nil {
				k.ID = *r.ID
			}
			return k
		}),
		Path: yang.JoinPath(yang.In(moduleFixtureMain, "servers"), yang.In(moduleFixtureAug2, "mirror")),
	}
}

// ServerKey is ServersServer's row identity (ancestor keys in canonical form).
type ServerKey struct {
	Name string
}

// ServerDescriptor is the list descriptor callers hand to a protocol library.
func ServerDescriptor() yang.ListDescriptor[ServersServer, ServerKey] {
	return yang.ListDescriptor[ServersServer, ServerKey]{
		Codec: yang.StructRowCodec(ServersServerSchemaX24fddd, func(r *ServersServer) ServerKey {
			var k ServerKey
			if r.Name != nil {
				k.Name = *r.Name
			}
			return k
		}),
		Path: yang.JoinPath(yang.In(moduleFixtureMain, "servers", "server")),
	}
}

// EndpointKey is Endpoint's row identity (ancestor keys in canonical form).
type EndpointKey struct {
	ServerName string
	Address    string
	Port       uint16
}

// EndpointFlatRow flattens one Endpoint entry with its ancestor list keys.
type EndpointFlatRow struct {
	ServerName string
	Entry      Endpoint
}

// EndpointDescriptor is the flattened-row descriptor for the nested list Endpoint.
func EndpointDescriptor() yang.ListDescriptor[EndpointFlatRow, EndpointKey] {
	return yang.ListDescriptor[EndpointFlatRow, EndpointKey]{
		Codec: yang.NestedRowCodec([]*yang.Schema{ServersServerSchemaX24fddd, EndpointSchema}, func(anc [][]yang.KeyValue, e Endpoint) EndpointFlatRow {
			return EndpointFlatRow{
				Entry:      e,
				ServerName: yang.AncestorKey(anc, 0, "name"),
			}
		}, func(r *EndpointFlatRow) *Endpoint {
			return &r.Entry
		}, func(r *EndpointFlatRow) EndpointKey {
			var k EndpointKey
			k.ServerName = r.ServerName
			if r.Entry.Address != nil {
				k.Address = *r.Entry.Address
			}
			if r.Entry.Port != nil {
				k.Port = *r.Entry.Port
			}
			return k
		}),
		Path: yang.JoinPath(yang.In(moduleFixtureMain, "servers", "server", "endpoint")),
	}
}

// AlarmStateDescriptor watches the AlarmState subtree as one synthetic row.
func AlarmStateDescriptor() yang.ListDescriptor[AlarmState, struct{}] {
	return yang.SubtreeDescriptor[AlarmState](AlarmStateSchema, yang.JoinPath(yang.In(moduleFixtureMain, "alarm-state")))
}

// AlarmStateDescriptorX1964ec watches the AlarmStateXa0728a subtree as one synthetic row.
func AlarmStateDescriptorX1964ec() yang.ListDescriptor[AlarmStateXa0728a, struct{}] {
	return yang.SubtreeDescriptor[AlarmStateXa0728a](AlarmStateSchemaXa270cf, yang.JoinPath(yang.In(moduleFixtureMain, "alarmState")))
}

// BindingsDescriptor watches the Bindings subtree as one synthetic row.
func BindingsDescriptor() yang.ListDescriptor[Bindings, struct{}] {
	return yang.SubtreeDescriptor[Bindings](BindingsSchema, yang.JoinPath(yang.In(moduleFixtureMain, "bindings")))
}

// FromSubmoduleDescriptor watches the FromSubmodule subtree as one synthetic row.
func FromSubmoduleDescriptor() yang.ListDescriptor[FromSubmodule, struct{}] {
	return yang.SubtreeDescriptor[FromSubmodule](FromSubmoduleSchema, yang.JoinPath(yang.In(moduleFixtureMain, "from-submodule")))
}

// PrimaryGroupDescriptor watches the PrimaryGroup subtree as one synthetic row.
func PrimaryGroupDescriptor() yang.ListDescriptor[PrimaryGroup, struct{}] {
	return yang.SubtreeDescriptor[PrimaryGroup](PrimaryGroupSchema, yang.JoinPath(yang.In(moduleFixtureMain, "primary-group")))
}

// SecondaryGroupDescriptor watches the SecondaryGroup subtree as one synthetic row.
func SecondaryGroupDescriptor() yang.ListDescriptor[SecondaryGroup, struct{}] {
	return yang.SubtreeDescriptor[SecondaryGroup](SecondaryGroupSchema, yang.JoinPath(yang.In(moduleFixtureMain, "secondary-group")))
}

// ServersDescriptor watches the Servers subtree as one synthetic row.
func ServersDescriptor() yang.ListDescriptor[Servers, struct{}] {
	return yang.SubtreeDescriptor[Servers](ServersSchema, yang.JoinPath(yang.In(moduleFixtureMain, "servers")))
}

// ShapeProbeDescriptor watches the ShapeProbe subtree as one synthetic row.
func ShapeProbeDescriptor() yang.ListDescriptor[ShapeProbe, struct{}] {
	return yang.SubtreeDescriptor[ShapeProbe](ShapeProbeSchema, yang.JoinPath(yang.In(moduleFixtureMain, "shape-probe")))
}
