// Code generated by yanggen. DO NOT EDIT.
// generator: yanggen-5
// module: fixture-main revision: 2026-01-02
// source sha256: 5da6674e7987c518e75dabb3f90b36eba9b1813061bea52f105a4bef50e1481e

// Package fixturemain binds the YANG module fixture-main.
package fixturemain

import yang "go.aledante.io/FlowSeer/src/protocol/yang"

// moduleFixtureAug identifies the fixture-aug YANG module.
var moduleFixtureAug = &yang.Module{
	Name:      "fixture-aug",
	Namespace: "urn:flowseer:fixture-aug",
}

// moduleFixtureMain identifies the fixture-main YANG module.
var moduleFixtureMain = &yang.Module{
	Name:      "fixture-main",
	Namespace: "urn:flowseer:fixture-main",
}

// AlarmState is the fixture-main node /fixture-main/alarm-state.
type AlarmState struct {
	Count *uint32
}

// AlarmStateSchema describes AlarmState for the generic codecs.
var AlarmStateSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Count", Name: "count", Type: yang.TUint32},
	},
	Module: moduleFixtureMain,
	Name:   "alarm-state",
}

// AlarmStateXa0728a is the fixture-main node /fixture-main/alarmState.
type AlarmStateXa0728a struct {
	Count *uint32
}

// AlarmStateSchemaXa270cf describes AlarmStateXa0728a for the generic codecs.
var AlarmStateSchemaXa270cf = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Count", Name: "count", Type: yang.TUint32},
	},
	Module: moduleFixtureMain,
	Name:   "alarmState",
}

// Binding is the fixture-main node /fixture-main/bindings/binding.
type Binding struct {
	ServerRef *string
	Weight    *uint8
}

// BindingSchema describes Binding for the generic codecs.
var BindingSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "ServerRef", Name: "server-ref", Type: yang.TString},
		{GoName: "Weight", Name: "weight", Type: yang.TUint8},
	},
	Keys:   []string{"server-ref"},
	Module: moduleFixtureMain,
	Name:   "binding",
}

// Bindings is the fixture-main node /fixture-main/bindings.
type Bindings struct {
	Binding []Binding
}

// BindingsSchema describes Bindings for the generic codecs.
var BindingsSchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: BindingSchema, GoName: "Binding", List: true, Name: "binding"},
	},
	Module: moduleFixtureMain,
	Name:   "bindings",
}

// Endpoint is the fixture-main node /fixture-main/servers/server/endpoint.
type Endpoint struct {
	Address *string
	Enabled *bool
	Port    *uint16
}

// EndpointSchema describes Endpoint for the generic codecs.
var EndpointSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Address", Name: "address", Type: yang.TString},
		{GoName: "Enabled", Name: "enabled", Type: yang.TBool},
		{GoName: "Port", Name: "port", Type: yang.TUint16},
	},
	Keys:   []string{"address", "port"},
	Module: moduleFixtureMain,
	Name:   "endpoint",
}

// FromSubmodule is the fixture-main node /fixture-main/from-submodule.
type FromSubmodule struct {
	Label *string
}

// FromSubmoduleSchema describes FromSubmodule for the generic codecs.
var FromSubmoduleSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Label", Name: "label", Type: yang.TString},
	},
	Module: moduleFixtureMain,
	Name:   "from-submodule",
}

// Item is the fixture-main node shape instantiated at 2 schema paths, such as /fixture-main/primary-group/item.
type Item struct {
	BufferSize *uint32
}

// ItemSchema describes Item for the generic codecs.
var ItemSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "BufferSize", Name: "buffer-size", Type: yang.TUint32},
	},
	Module: moduleFixtureMain,
	Name:   "item",
}

// Key is the fixture-main node /fixture-main/servers/server/key.
type Key struct {
	ID *string
}

// KeySchema describes Key for the generic codecs.
var KeySchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "ID", Name: "id", Type: yang.TString},
	},
	Module: moduleFixtureMain,
	Name:   "key",
}

// PrimaryGroup is the fixture-main node /fixture-main/primary-group.
type PrimaryGroup struct {
	Item *Item
}

// PrimaryGroupSchema describes PrimaryGroup for the generic codecs.
var PrimaryGroupSchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: ItemSchema, GoName: "Item", Name: "item"},
	},
	Module: moduleFixtureMain,
	Name:   "primary-group",
}

// Schema is the fixture-main node /fixture-main/servers/schema.
type Schema struct {
	Version *string
}

// SchemaSchema describes Schema for the generic codecs.
var SchemaSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Version", Name: "version", Type: yang.TString},
	},
	Module: moduleFixtureMain,
	Name:   "schema",
}

// SecondaryGroup is the fixture-main node /fixture-main/secondary-group.
type SecondaryGroup struct {
	Item *Item
}

// SecondaryGroupSchema describes SecondaryGroup for the generic codecs.
var SecondaryGroupSchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: ItemSchema, GoName: "Item", Name: "item"},
	},
	Module: moduleFixtureMain,
	Name:   "secondary-group",
}

// Servers is the fixture-main node /fixture-main/servers.
type Servers struct {
	Schema       *Schema
	Server       []ServersServer
	ServerSchema *ServersServerSchema
}

// ServersSchema describes Servers for the generic codecs.
var ServersSchema = &yang.Schema{
	Fields: []yang.Field{
		{Child: SchemaSchema, GoName: "Schema", Name: "schema"},
		{Child: ServersServerSchemaX9bc561, GoName: "Server", List: true, Name: "server"},
		{Child: ServersServerSchemaSchema, GoName: "ServerSchema", Name: "server-schema"},
	},
	Module: moduleFixtureMain,
	Name:   "servers",
}

// ServersServer is the fixture-main node /fixture-main/servers/server.
type ServersServer struct {
	Endpoint []Endpoint
	Key      *Key
	Listen   *yang.Value
	Name     *string
	Owner    *string
	Port     *uint16
	Proto    *yang.Identity
	Ratio    *yang.Value
	TLS      *TLS
}

// ServersServerSchemaX9bc561 describes ServersServer for the generic codecs.
var ServersServerSchemaX9bc561 = &yang.Schema{
	Fields: []yang.Field{
		{Child: EndpointSchema, GoName: "Endpoint", List: true, Name: "endpoint"},
		{Child: KeySchema, GoName: "Key", Name: "key"},
		{GoName: "Listen", Name: "listen", Type: &yang.Type{
			Kind:    yang.TypeUnion,
			Members: []yang.Type{{Kind: yang.TypeUint16}, {Kind: yang.TypeString}},
		}},
		{GoName: "Name", Name: "name", Type: yang.TString},
		{GoName: "Owner", Module: moduleFixtureAug, Name: "owner", Type: yang.TString},
		{GoName: "Port", Name: "port", Type: yang.TUint16},
		{GoName: "Proto", Name: "proto", Type: yang.TIdentity},
		{GoName: "Ratio", Name: "ratio", Type: &yang.Type{
			FractionDigits: 3,
			Kind:           yang.TypeDecimal64,
		}},
		{Child: TLSSchema, GoName: "TLS", Name: "tls"},
	},
	Keys:   []string{"name"},
	Module: moduleFixtureMain,
	Name:   "server",
}

// ServersServerSchema is the fixture-main node /fixture-main/servers/server-schema.
type ServersServerSchema struct {
	Note *string
}

// ServersServerSchemaSchema describes ServersServerSchema for the generic codecs.
var ServersServerSchemaSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "Note", Name: "note", Type: yang.TString},
	},
	Module: moduleFixtureMain,
	Name:   "server-schema",
}

// TLS is the fixture-main node /fixture-main/servers/server/tls.
type TLS struct {
	MinVersion *string
}

// TLSSchema describes TLS for the generic codecs.
var TLSSchema = &yang.Schema{
	Fields: []yang.Field{
		{GoName: "MinVersion", Name: "min-version", Type: yang.TEnum},
	},
	Module:   moduleFixtureMain,
	Name:     "tls",
	Presence: true,
}

// BindingKey is Binding's row identity (ancestor keys in canonical form).
type BindingKey struct {
	ServerRef string
}

// BindingDescriptor is the list descriptor callers hand to a protocol library.
func BindingDescriptor() yang.ListDescriptor[Binding, BindingKey] {
	return yang.ListDescriptor[Binding, BindingKey]{
		Codec: yang.StructRowCodec(BindingSchema, func(r *Binding) BindingKey {
			var k BindingKey
			if r.ServerRef != nil {
				k.ServerRef = *r.ServerRef
			}
			return k
		}),
		Path: yang.JoinPath(yang.In(moduleFixtureMain, "bindings", "binding")),
	}
}

// ServerKey is ServersServer's row identity (ancestor keys in canonical form).
type ServerKey struct {
	Name string
}

// ServerDescriptor is the list descriptor callers hand to a protocol library.
func ServerDescriptor() yang.ListDescriptor[ServersServer, ServerKey] {
	return yang.ListDescriptor[ServersServer, ServerKey]{
		Codec: yang.StructRowCodec(ServersServerSchemaX9bc561, func(r *ServersServer) ServerKey {
			var k ServerKey
			if r.Name != nil {
				k.Name = *r.Name
			}
			return k
		}),
		Path: yang.JoinPath(yang.In(moduleFixtureMain, "servers", "server")),
	}
}

// EndpointKey is Endpoint's row identity (ancestor keys in canonical form).
type EndpointKey struct {
	ServerName string
	Address    string
	Port       uint16
}

// EndpointFlatRow flattens one Endpoint entry with its ancestor list keys.
type EndpointFlatRow struct {
	ServerName string
	Entry      Endpoint
}

// EndpointDescriptor is the flattened-row descriptor for the nested list Endpoint.
func EndpointDescriptor() yang.ListDescriptor[EndpointFlatRow, EndpointKey] {
	return yang.ListDescriptor[EndpointFlatRow, EndpointKey]{
		Codec: yang.NestedRowCodec([]*yang.Schema{ServersServerSchemaX9bc561, EndpointSchema}, func(anc [][]yang.KeyValue, e Endpoint) EndpointFlatRow {
			return EndpointFlatRow{
				Entry:      e,
				ServerName: yang.AncestorKey(anc, 0, "name"),
			}
		}, func(r *EndpointFlatRow) *Endpoint {
			return &r.Entry
		}, func(r *EndpointFlatRow) EndpointKey {
			var k EndpointKey
			k.ServerName = r.ServerName
			if r.Entry.Address != nil {
				k.Address = *r.Entry.Address
			}
			if r.Entry.Port != nil {
				k.Port = *r.Entry.Port
			}
			return k
		}),
		Path: yang.JoinPath(yang.In(moduleFixtureMain, "servers", "server", "endpoint")),
	}
}

// AlarmStateDescriptor watches the AlarmState subtree as one synthetic row.
func AlarmStateDescriptor() yang.ListDescriptor[AlarmState, struct{}] {
	return yang.SubtreeDescriptor[AlarmState](AlarmStateSchema, yang.JoinPath(yang.In(moduleFixtureMain, "alarm-state")))
}

// AlarmStateDescriptorX665c35 watches the AlarmStateXa0728a subtree as one synthetic row.
func AlarmStateDescriptorX665c35() yang.ListDescriptor[AlarmStateXa0728a, struct{}] {
	return yang.SubtreeDescriptor[AlarmStateXa0728a](AlarmStateSchemaXa270cf, yang.JoinPath(yang.In(moduleFixtureMain, "alarmState")))
}

// BindingsDescriptor watches the Bindings subtree as one synthetic row.
func BindingsDescriptor() yang.ListDescriptor[Bindings, struct{}] {
	return yang.SubtreeDescriptor[Bindings](BindingsSchema, yang.JoinPath(yang.In(moduleFixtureMain, "bindings")))
}

// FromSubmoduleDescriptor watches the FromSubmodule subtree as one synthetic row.
func FromSubmoduleDescriptor() yang.ListDescriptor[FromSubmodule, struct{}] {
	return yang.SubtreeDescriptor[FromSubmodule](FromSubmoduleSchema, yang.JoinPath(yang.In(moduleFixtureMain, "from-submodule")))
}

// PrimaryGroupDescriptor watches the PrimaryGroup subtree as one synthetic row.
func PrimaryGroupDescriptor() yang.ListDescriptor[PrimaryGroup, struct{}] {
	return yang.SubtreeDescriptor[PrimaryGroup](PrimaryGroupSchema, yang.JoinPath(yang.In(moduleFixtureMain, "primary-group")))
}

// SecondaryGroupDescriptor watches the SecondaryGroup subtree as one synthetic row.
func SecondaryGroupDescriptor() yang.ListDescriptor[SecondaryGroup, struct{}] {
	return yang.SubtreeDescriptor[SecondaryGroup](SecondaryGroupSchema, yang.JoinPath(yang.In(moduleFixtureMain, "secondary-group")))
}

// ServersDescriptor watches the Servers subtree as one synthetic row.
func ServersDescriptor() yang.ListDescriptor[Servers, struct{}] {
	return yang.SubtreeDescriptor[Servers](ServersSchema, yang.JoinPath(yang.In(moduleFixtureMain, "servers")))
}
