package main

import (
	"flag"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/sleepinggenius2/gosmi"
)

// updateGolden refreshes the committed golden file under
// testdata/golden/fakemib/mib.go. Run with
//
//	go test ./common/snmp/cmd/mibgen -run TestEmit_FakeMIB_Golden -update-golden
//
// after intentional emitter changes. The flag is unbound by default so
// the test asserts equality against the committed file.
var updateGolden = flag.Bool("update-golden", false, "rewrite testdata/golden/* with the current emitter output")

// loadFakeMIB initializes gosmi against the testdata mibs directory and
// loads FAKE-MIB. The returned cleanup deferred-call resets gosmi so
// the next test starts from a clean slate; libsmi keeps module state
// in a global so leaking it would corrupt unrelated test runs.
func loadFakeMIB(t *testing.T) (*gosmi.SmiModule, func()) {
	t.Helper()
	mibDir, err := filepath.Abs("testdata/mibs")
	if err != nil {
		t.Fatalf("abs: %v", err)
	}
	// SNMPv2-TC / SNMPv2-SMI live under spec/mib/ietf in the repo;
	// add that search path too so libsmi can resolve the IMPORTS.
	ietfDir, err := filepath.Abs(filepath.Join("..", "..", "..", "..", "..", "spec", "mib", "ietf"))
	if err != nil {
		t.Fatalf("abs ietf: %v", err)
	}
	if _, err := os.Stat(ietfDir); err != nil {
		t.Skipf("spec/mib/ietf not available: %v", err)
	}

	gosmi.Init()
	gosmi.AppendPath(mibDir)
	gosmi.AppendPath(ietfDir)
	cleanup := func() { gosmi.Exit() }

	if _, err := gosmi.LoadModule("FAKE-MIB"); err != nil {
		cleanup()
		t.Fatalf("load FAKE-MIB: %v", err)
	}
	mod, err := gosmi.GetModule("FAKE-MIB")
	if err != nil {
		cleanup()
		t.Fatalf("get FAKE-MIB: %v", err)
	}
	return &mod, cleanup
}

// TestEmit_FakeMIB_Golden renders FAKE-MIB through the emitter and
// compares against the committed golden under testdata/golden/fakemib/.
// Use -update-golden after any intentional emitter change.
func TestEmit_FakeMIB_Golden(t *testing.T) {
	mod, cleanup := loadFakeMIB(t)
	defer cleanup()

	cm := Module{Name: "FAKE-MIB", Package: "fakemib"}
	cfgByName := map[string]Module{cm.Name: cm}

	got, err := renderModule(mod, cm, cfgByName, "go.aledante.io/FlowSeer/src/common/snmp/cmd/mibgen/testdata/golden")
	if err != nil {
		t.Fatalf("renderModule: %v", err)
	}

	goldenPath := filepath.Join("testdata", "golden", "fakemib", "mib.go")
	if *updateGolden {
		if err := os.MkdirAll(filepath.Dir(goldenPath), 0o755); err != nil {
			t.Fatalf("mkdir: %v", err)
		}
		if err := os.WriteFile(goldenPath, got, 0o644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		t.Logf("updated %s (%d bytes)", goldenPath, len(got))
		return
	}

	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden (rerun with -update-golden if first time): %v", err)
	}
	if string(want) != string(got) {
		t.Errorf("golden mismatch: %s; rerun with -update-golden after auditing the diff", goldenPath)
		// Write the candidate next to the golden so devs can diff
		// without re-running with the update flag.
		candidatePath := goldenPath + ".got"
		_ = os.WriteFile(candidatePath, got, 0o644)
		t.Logf("wrote candidate to %s", candidatePath)
	}
}

// TestEmit_GeneratedParses ensures the emitted source is a syntactically
// valid Go file. It does not run the type checker against the host
// package (that would require building common/snmp from a tmp module
// — too heavy for the unit suite).
func TestEmit_GeneratedParses(t *testing.T) {
	mod, cleanup := loadFakeMIB(t)
	defer cleanup()

	cm := Module{Name: "FAKE-MIB", Package: "fakemib"}
	out, err := renderModule(mod, cm, nil, "go.aledante.io/FlowSeer/src/common/snmp/cmd/mibgen/testdata/golden")
	if err != nil {
		t.Fatalf("renderModule: %v", err)
	}
	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, "fakemib_mib.go", out, parser.AllErrors|parser.ParseComments); err != nil {
		t.Fatalf("parse: %v\n--- emitted ---\n%s", err, string(out))
	}
}

// TestEmit_FakeMIB_HasExpectedSymbols asserts the most important
// surface of the generated package without locking it to byte-exact
// shape. The golden test handles byte-exactness; this test protects
// against accidental removal of a public identifier.
func TestEmit_FakeMIB_HasExpectedSymbols(t *testing.T) {
	mod, cleanup := loadFakeMIB(t)
	defer cleanup()

	cm := Module{Name: "FAKE-MIB", Package: "fakemib"}
	out, err := renderModule(mod, cm, nil, "go.aledante.io/FlowSeer/src/common/snmp/cmd/mibgen/testdata/golden")
	if err != nil {
		t.Fatalf("renderModule: %v", err)
	}
	src := string(out)

	wantFragments := []string{
		"package fakemib",
		"Code generated by mibgen",
		"func FakeScalarGet",
		"func FakeStatusGet",
		"type FakeStatusValue int32",
		"FakeStatusValueUp",
		"FakeStatusValueDown",
		"FakeStatusValueTesting",
		"var FakeName =",
		"var FakeMac =",
		"var FakeOctets =",
		"var FakeLastChange =",
		"type FakeTableRow struct",
		"type FakeTableWalker struct",
		"func (tw *FakeTableWalker) Iter()",
		"func (tw *FakeTableWalker) Err()",
		"func (fakeTableT) Walk",
		"var FakeTable fakeTableT",
		// Module-prefixed dispatch map: FAKE-MIB → fAKEMIBOIDDispatch
		// (camelCase upper-cases letters following hyphens, then the
		// first rune is lower-cased to keep the symbol package-private).
		// Renamed in the D5 refactor so two generated files dropped into
		// the same Go package directory don't collide on a shared name.
		"fAKEMIBOIDDispatch = map[string]snmp.AnyColumn",
		"func OIDDispatch()",
		// snmp.MustOID call expressions replaced the old per-package
		// mustParseOID helper. MustOID (not NewOID) is the codegen-facing
		// companion: a malformed generated OID panics at package init.
		"snmp.MustOID(",
		// Per-package ColumnTiers map + accessor, gated on the
		// module containing at least one Watch-eligible table. FAKE-MIB
		// has fakeLastChange as a structural per-row indicator → gate
		// open, map present.
		"fAKEMIBColumnTiers = map[string]snmp.Tier",
		"snmp.TierCounter",
		"snmp.TierIndicator",
		"snmp.TierState",
		"func ColumnTier(col snmp.AnyColumn) snmp.Tier",
		// Per-table ChangeIndicator var (per-row form for
		// fakeTable's fakeLastChange).
		"var FakeTableIndicator =",
		"snmp.MustChangeIndicator",
		"snmp.NewPerRowIndicator",
		// Per-table Watch machinery — decode/equal helpers,
		// typed wrapper, Watch method.
		"func decodeFakeTableRow(",
		"func equalFakeTableRow(",
		"func mergeFakeTableRow(",
		"type FakeTableWatcher struct",
		"func (tw *FakeTableWatcher) Iter()",
		"func (tw *FakeTableWatcher) Err()",
		"func (tw *FakeTableWatcher) Close()",
		"func (tw *FakeTableWatcher) Fallback()",
		"func (tw *FakeTableWatcher) LastTickErr()",
		"func (tw *FakeTableWatcher) TableRoot()",
		"func (fakeTableT) Watch(",
		"snmp.NewWatcher[FakeTableRow]",
		// equal helper uses the type-appropriate comparator
		// (bytes.Equal for the MacAddress []byte field).
		"bytes.Equal(a.FakeMac, b.FakeMac)",
	}
	notWantFragments := []string{
		// Removed in the D5 refactor; ensure the helper does not creep
		// back in.
		"func mustParseOID",
	}
	for _, w := range wantFragments {
		if !strings.Contains(src, w) {
			t.Errorf("emitted source missing fragment %q\n--- src ---\n%s", w, src)
		}
	}
	for _, w := range notWantFragments {
		if strings.Contains(src, w) {
			t.Errorf("emitted source contains forbidden fragment %q\n--- src ---\n%s", w, src)
		}
	}
}
