// Code generated by src/common/smi/internal/catalog/gen; DO NOT EDIT.
//
// The diagnostic table in internal/catalog is the source of truth.
// Append a row there and run `go generate ./src/common/smi/...`.

package diag

import "go.aledante.io/FlowSeer/src/common/errs"

// The diagnostic codes, one per catalog row. A code is a wire
// contract: append-only, never renamed, never reused for a different
// condition. Severity is not part of a code's identity and may be
// regraded; the code may not.
var (
	// ErrCodeBinaryStringNotOctets marks a binary string literal whose
	// digit count is not a multiple of eight, so its last octet is short
	// of bits.
	ErrCodeBinaryStringNotOctets = errs.NewCode("smi/binary-string-not-octets")

	// ErrCodeClauseOutOfOrder marks a clause written out of its macro's
	// fixed order, whose meaning is unambiguous and which is therefore
	// kept.
	ErrCodeClauseOutOfOrder = errs.NewCode("smi/clause-out-of-order")

	// ErrCodeContentAfterEnd marks text following the last module's END,
	// which is dropped rather than costing the file because a trailer says
	// nothing about the modules already read.
	ErrCodeContentAfterEnd = errs.NewCode("smi/content-after-end")

	// ErrCodeDefaultNotPermitted marks a default value on a type RFC 2578
	// gives no default form for, such as a counter whose value only ever
	// means a difference.
	ErrCodeDefaultNotPermitted = errs.NewCode("smi/default-not-permitted")

	// ErrCodeDialectValueMismatch marks a clause value only one of the two
	// SMI dialects defines, written in a module read as the other one,
	// which is graded and kept because the value still says what its
	// author meant.
	ErrCodeDialectValueMismatch = errs.NewCode("smi/dialect-value-mismatch")

	// ErrCodeDisplayHintMalformed marks a display hint that does not read
	// as either of RFC 2579's two forms, which leaves nothing to render a
	// value with.
	ErrCodeDisplayHintMalformed = errs.NewCode("smi/display-hint-malformed")

	// ErrCodeDisplayHintNotPermitted marks a display hint on a syntax RFC
	// 2579 gives no hint forms for, where nothing could act on the hint.
	ErrCodeDisplayHintNotPermitted = errs.NewCode("smi/display-hint-not-permitted")

	// ErrCodeDisplayHintSeparator marks a display-hint separator that
	// cannot be told apart from the octet count or repeat indicator of the
	// specification after it.
	ErrCodeDisplayHintSeparator = errs.NewCode("smi/display-hint-separator")

	// ErrCodeDuplicateClause marks a clause repeated in a macro that
	// allows it once, where keeping the first occurrence is the only
	// choice a reader can predict.
	ErrCodeDuplicateClause = errs.NewCode("smi/duplicate-clause")

	// ErrCodeDuplicateModule marks one module name defined by two files,
	// where the first in canonical order wins because a module name has to
	// mean one thing.
	ErrCodeDuplicateModule = errs.NewCode("smi/duplicate-module")

	// ErrCodeHyphenSeparator marks a hyphen run whose length is 1 mod 4,
	// which pairs off into comments and leaves one stray minus token
	// behind.
	ErrCodeHyphenSeparator = errs.NewCode("smi/hyphen-separator")

	// ErrCodeImportCycle marks an IMPORTS cycle, which is broken at the
	// back edge rather than costing either module because both of them
	// still define everything they define.
	ErrCodeImportCycle = errs.NewCode("smi/import-cycle")

	// ErrCodeLimitExceeded marks a declared resource limit being reached,
	// which costs the whole file so that pathological input costs bounded
	// work.
	ErrCodeLimitExceeded = errs.NewCode("smi/limit-exceeded")

	// ErrCodeMissingClause marks a declaration without a clause its macro
	// requires, which leaves the declaration unresolved and visible rather
	// than dropping it.
	ErrCodeMissingClause = errs.NewCode("smi/missing-clause")

	// ErrCodeMissingImport marks a symbol used with no IMPORTS clause
	// naming it, which resolves anyway because refusing a spelling the
	// corpus writes by the thousand would cost far more than it reports.
	ErrCodeMissingImport = errs.NewCode("smi/missing-import")

	// ErrCodeMissingModuleHeader marks a file with no module header, which
	// costs the whole file because there is no module to attribute a
	// declaration to.
	ErrCodeMissingModuleHeader = errs.NewCode("smi/missing-module-header")

	// ErrCodeModuleNotFound marks an IMPORTS clause naming a module no
	// search path holds, which leaves the symbols it was to supply to the
	// fallback lookup or to nothing at all.
	ErrCodeModuleNotFound = errs.NewCode("smi/module-not-found")

	// ErrCodeNegativeSize marks a negative bound in a SIZE constraint,
	// which describes no string this or any other implementation can hold.
	ErrCodeNegativeSize = errs.NewCode("smi/negative-size")

	// ErrCodeNonConformingOIDDefault marks an OID default spelled as bare
	// sub-identifiers, a form the RFC does not define but whose meaning is
	// plain enough to keep.
	ErrCodeNonConformingOIDDefault = errs.NewCode("smi/non-conforming-oid-default")

	// ErrCodeOddHexString marks a hexadecimal string literal with an odd
	// digit count, whose trailing nibble has no byte to land in.
	ErrCodeOddHexString = errs.NewCode("smi/odd-hex-string")

	// ErrCodeOverlappingRange marks two range alternatives covering a
	// value twice, which RFC 2578 forbids and whose union is still the set
	// the author described.
	ErrCodeOverlappingRange = errs.NewCode("smi/overlapping-range")

	// ErrCodePairedCommentMode marks a file that only reads cleanly under
	// paired -- comment termination, recording which rule produced the
	// result.
	ErrCodePairedCommentMode = errs.NewCode("smi/paired-comment-mode")

	// ErrCodeRangeNotAscending marks a range written backwards, which
	// names no value and whose author's intent cannot be recovered from
	// the two bounds alone.
	ErrCodeRangeNotAscending = errs.NewCode("smi/range-not-ascending")

	// ErrCodeRangeOutsideBaseType marks a subtype bound the base type
	// could never take, which leaves the constraint describing values the
	// object cannot carry.
	ErrCodeRangeOutsideBaseType = errs.NewCode("smi/range-outside-base-type")

	// ErrCodeTrailingHyphenIdentifier marks an identifier ending in a
	// hyphen, which RFC 2578 forbids and which a stricter lexer reads as
	// the start of a comment.
	ErrCodeTrailingHyphenIdentifier = errs.NewCode("smi/trailing-hyphen-identifier")

	// ErrCodeUnexpectedToken marks a token the grammar has no place for,
	// which the parser skips past to the next clause keyword inside the
	// same declaration.
	ErrCodeUnexpectedToken = errs.NewCode("smi/unexpected-token")

	// ErrCodeUnknownClause marks a clause keyword belonging to some other
	// macro, which costs the clause and leaves the rest of the declaration
	// readable.
	ErrCodeUnknownClause = errs.NewCode("smi/unknown-clause")

	// ErrCodeUnrecognizedDeclaration marks a declaration the framer could
	// not classify, which costs that declaration and nothing around it.
	ErrCodeUnrecognizedDeclaration = errs.NewCode("smi/unrecognized-declaration")

	// ErrCodeUnresolvedDeclaration marks a declaration one of whose
	// references did not resolve, reported once on the declaration so that
	// a single missing name costs one diagnostic per dependent rather than
	// one per site.
	ErrCodeUnresolvedDeclaration = errs.NewCode("smi/unresolved-declaration")

	// ErrCodeUnterminatedComment marks a comment running to end of file,
	// which costs the whole file because no declaration boundary after it
	// can be trusted.
	ErrCodeUnterminatedComment = errs.NewCode("smi/unterminated-comment")

	// ErrCodeUnterminatedString marks a quoted string running to end of
	// file, one of the few conditions that costs the whole file because
	// nothing after the opening quote can be framed.
	ErrCodeUnterminatedString = errs.NewCode("smi/unterminated-string")
)
