// Code generated by src/protocol/smi/internal/catalog/gen; DO NOT EDIT.
//
// The diagnostic table in internal/catalog is the source of truth.
// Append a row there and run `go generate ./src/protocol/smi/...`.

package smi

import "go.aledante.io/FlowSeer/src/protocol/smi/internal/diag"

// The diagnostic codes, one per catalog row. A code is a wire
// contract: append-only, never renamed, never reused for a different
// condition. Severity is not part of a code's identity and may be
// regraded; the code may not.
var (
	// ErrCodeBinaryStringNotOctets marks a binary string literal whose
	// digit count is not a multiple of eight, so its last octet is short
	// of bits.
	ErrCodeBinaryStringNotOctets = diag.ErrCodeBinaryStringNotOctets

	// ErrCodeClauseOutOfOrder marks a clause written out of its macro's
	// fixed order, whose meaning is unambiguous and which is therefore
	// kept.
	ErrCodeClauseOutOfOrder = diag.ErrCodeClauseOutOfOrder

	// ErrCodeContentAfterEnd marks text following the last module's END,
	// which is dropped rather than costing the file because a trailer says
	// nothing about the modules already read.
	ErrCodeContentAfterEnd = diag.ErrCodeContentAfterEnd

	// ErrCodeCurlyQuotedString marks a string a word processor re-quoted
	// into Windows-1252, read as a string because a file quoted that way
	// throughout has no readable declaration left otherwise.
	ErrCodeCurlyQuotedString = diag.ErrCodeCurlyQuotedString

	// ErrCodeDefaultNotPermitted marks a default value on a type RFC 2578
	// gives no default form for, such as a counter whose value only ever
	// means a difference.
	ErrCodeDefaultNotPermitted = diag.ErrCodeDefaultNotPermitted

	// ErrCodeDialectValueMismatch marks a clause value only one of the two
	// SMI dialects defines, written in a module read as the other one,
	// which is graded and kept because the value still says what its
	// author meant.
	ErrCodeDialectValueMismatch = diag.ErrCodeDialectValueMismatch

	// ErrCodeDisplayHintMalformed marks a display hint that does not read
	// as either of RFC 2579's two forms, which leaves nothing to render a
	// value with.
	ErrCodeDisplayHintMalformed = diag.ErrCodeDisplayHintMalformed

	// ErrCodeDisplayHintNotPermitted marks a display hint on a syntax RFC
	// 2579 gives no hint forms for, where nothing could act on the hint.
	ErrCodeDisplayHintNotPermitted = diag.ErrCodeDisplayHintNotPermitted

	// ErrCodeDisplayHintSeparator marks a display-hint separator that
	// cannot be told apart from the octet count or repeat indicator of the
	// specification after it.
	ErrCodeDisplayHintSeparator = diag.ErrCodeDisplayHintSeparator

	// ErrCodeDuplicateClause marks a clause repeated in a macro that
	// allows it once, where keeping the first occurrence is the only
	// choice a reader can predict.
	ErrCodeDuplicateClause = diag.ErrCodeDuplicateClause

	// ErrCodeDuplicateModule marks one module name defined by two files,
	// where the first in canonical order wins because a module name has to
	// mean one thing.
	ErrCodeDuplicateModule = diag.ErrCodeDuplicateModule

	// ErrCodeDuplicateOID marks two descriptors registered at one OBJECT
	// IDENTIFIER value, where only one of them can be the node a walk
	// arrives at.
	ErrCodeDuplicateOID = diag.ErrCodeDuplicateOID

	// ErrCodeEnumerationRefinementConflict marks a SYNTAX clause that
	// renames or renumbers the enumeration it refines instead of narrowing
	// it, which leaves two contradictory readings of the same wire value.
	ErrCodeEnumerationRefinementConflict = diag.ErrCodeEnumerationRefinementConflict

	// ErrCodeHyphenSeparator marks a hyphen run whose length is 1 mod 4,
	// which pairs off into comments and leaves one stray minus token
	// behind.
	ErrCodeHyphenSeparator = diag.ErrCodeHyphenSeparator

	// ErrCodeImportCycle marks an IMPORTS cycle, which is broken at the
	// back edge rather than costing either module because both of them
	// still define everything they define.
	ErrCodeImportCycle = diag.ErrCodeImportCycle

	// ErrCodeLimitExceeded marks a declared resource limit being reached,
	// which costs the whole file so that pathological input costs bounded
	// work.
	ErrCodeLimitExceeded = diag.ErrCodeLimitExceeded

	// ErrCodeMissingClause marks a declaration without a clause its macro
	// requires, which leaves the declaration unresolved and visible rather
	// than dropping it.
	ErrCodeMissingClause = diag.ErrCodeMissingClause

	// ErrCodeMissingImport marks a symbol used with no IMPORTS clause
	// naming it, which resolves anyway because refusing a spelling the
	// corpus writes by the thousand would cost far more than it reports.
	ErrCodeMissingImport = diag.ErrCodeMissingImport

	// ErrCodeMissingModuleHeader marks a file with no module header, which
	// costs the whole file because there is no module to attribute a
	// declaration to.
	ErrCodeMissingModuleHeader = diag.ErrCodeMissingModuleHeader

	// ErrCodeModuleNotFound marks an IMPORTS clause naming a module no
	// search path holds, which leaves the symbols it was to supply to the
	// fallback lookup or to nothing at all.
	ErrCodeModuleNotFound = diag.ErrCodeModuleNotFound

	// ErrCodeNegativeSize marks a negative bound in a SIZE constraint,
	// which describes no string this or any other implementation can hold.
	ErrCodeNegativeSize = diag.ErrCodeNegativeSize

	// ErrCodeNonConformingOIDDefault marks an OID default spelled as bare
	// sub-identifiers, a form the RFC does not define but whose meaning is
	// plain enough to keep.
	ErrCodeNonConformingOIDDefault = diag.ErrCodeNonConformingOIDDefault

	// ErrCodeOddHexString marks a hexadecimal string literal with an odd
	// digit count, whose trailing nibble has no byte to land in.
	ErrCodeOddHexString = diag.ErrCodeOddHexString

	// ErrCodeOverlappingRange marks two range alternatives covering a
	// value twice, which RFC 2578 forbids and whose union is still the set
	// the author described.
	ErrCodeOverlappingRange = diag.ErrCodeOverlappingRange

	// ErrCodePairedCommentMode marks a file that only reads cleanly under
	// paired -- comment termination, recording which rule produced the
	// result.
	ErrCodePairedCommentMode = diag.ErrCodePairedCommentMode

	// ErrCodeRangeNotAscending marks a range written backwards, which
	// names no value and whose author's intent cannot be recovered from
	// the two bounds alone.
	ErrCodeRangeNotAscending = diag.ErrCodeRangeNotAscending

	// ErrCodeRangeOutsideBaseType marks a subtype bound the base type
	// could never take, which leaves the constraint describing values the
	// object cannot carry.
	ErrCodeRangeOutsideBaseType = diag.ErrCodeRangeOutsideBaseType

	// ErrCodeTrailingHyphenIdentifier marks an identifier ending in a
	// hyphen, which RFC 2578 forbids and which a stricter lexer reads as
	// the start of a comment.
	ErrCodeTrailingHyphenIdentifier = diag.ErrCodeTrailingHyphenIdentifier

	// ErrCodeUnderscoreInDescriptor marks an underscore inside a
	// descriptor, which the RFC leaves out of the character set and which
	// the corpus writes anyway, read as one name because ending the name
	// at the underscore costs the declaration every member after it.
	ErrCodeUnderscoreInDescriptor = diag.ErrCodeUnderscoreInDescriptor

	// ErrCodeUnexpectedToken marks a token the grammar has no place for,
	// which the parser skips past to the next clause keyword inside the
	// same declaration.
	ErrCodeUnexpectedToken = diag.ErrCodeUnexpectedToken

	// ErrCodeUnknownClause marks a clause keyword belonging to some other
	// macro, which costs the clause and leaves the rest of the declaration
	// readable.
	ErrCodeUnknownClause = diag.ErrCodeUnknownClause

	// ErrCodeUnrecognizedDeclaration marks a declaration the framer could
	// not classify, which costs that declaration and nothing around it.
	ErrCodeUnrecognizedDeclaration = diag.ErrCodeUnrecognizedDeclaration

	// ErrCodeUnresolvedAugments marks an AUGMENTS clause naming a row that
	// no loaded module declares, so the augmenting table carries no
	// augmented link and no inherited key.
	ErrCodeUnresolvedAugments = diag.ErrCodeUnresolvedAugments

	// ErrCodeUnresolvedDeclaration marks a declaration one of whose
	// references did not resolve, reported once on the declaration so that
	// a single missing name costs one diagnostic per dependent rather than
	// one per site.
	ErrCodeUnresolvedDeclaration = diag.ErrCodeUnresolvedDeclaration

	// ErrCodeUnresolvedIndexPart marks an INDEX part naming a column that
	// no loaded module declares or whose type did not resolve, so the
	// table keeps the part flagged and nothing may decode a row key from
	// it.
	ErrCodeUnresolvedIndexPart = diag.ErrCodeUnresolvedIndexPart

	// ErrCodeUnterminatedComment marks a comment running to end of file,
	// which costs the whole file because no declaration boundary after it
	// can be trusted.
	ErrCodeUnterminatedComment = diag.ErrCodeUnterminatedComment

	// ErrCodeUnterminatedString marks a quoted string running to end of
	// file, one of the few conditions that costs the whole file because
	// nothing after the opening quote can be framed.
	ErrCodeUnterminatedString = diag.ErrCodeUnterminatedString
)
