package catalog

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

// commentWidth is where a generated doc comment wraps, chosen to match
// what the rest of the tree's comments look like by eye.
const commentWidth = 68

// RenderCodes returns the Go source for package smi's diagnostic code
// variables, one per row, formatted as gofmt would leave it.
//
// The generator writes the result to disk and a test in package smi
// compares the committed file against a fresh call, so a hand-edited
// constant and a forgotten regeneration fail the same way.
func RenderCodes(rows []Entry) ([]byte, error) {
	if err := Validate(rows); err != nil {
		return nil, fmt.Errorf("catalog is invalid: %w", err)
	}

	var b bytes.Buffer

	b.WriteString("// Code generated by src/common/smi/internal/catalog/gen; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// The diagnostic table in internal/catalog is the source of truth.\n")
	b.WriteString("// Append a row there and run `go generate ./src/common/smi/...`.\n\n")
	b.WriteString("package smi\n\n")
	b.WriteString("import \"go.aledante.io/FlowSeer/src/common/errs\"\n\n")
	b.WriteString("// The diagnostic codes, one per catalog row. A code is a wire\n")
	b.WriteString("// contract: append-only, never renamed, never reused for a different\n")
	b.WriteString("// condition. Severity is not part of a code's identity and may be\n")
	b.WriteString("// regraded; the code may not.\n")
	b.WriteString("var (\n")

	for i, r := range rows {
		if i > 0 {
			b.WriteString("\n")
		}

		name := "ErrCode" + r.Tag
		for _, line := range wrapComment(name+" marks "+r.Description+".", commentWidth) {
			fmt.Fprintf(&b, "\t// %s\n", line)
		}
		fmt.Fprintf(&b, "\t%s = errs.NewCode(%q)\n", name, r.Code)
	}

	b.WriteString(")\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated source: %w", err)
	}

	return src, nil
}

// wrapComment greedily breaks text into lines of at most width bytes. A
// word longer than width gets its own line rather than being split.
func wrapComment(text string, width int) []string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return nil
	}

	lines := []string{words[0]}
	for _, w := range words[1:] {
		last := len(lines) - 1
		if len(lines[last])+1+len(w) <= width {
			lines[last] += " " + w

			continue
		}

		lines = append(lines, w)
	}

	return lines
}
