// Code generated by yanggen. DO NOT EDIT.
// generator: yanggen-2
// module: fixture-types revision: 2026-01-01
// source sha256: fc5f8bea19c2183c576c2d2d2e9ff71b37752361803b515ad7c0bc41a83fba5b

// Package fixturetypes binds the YANG module fixture-types.
package fixturetypes

import yang "go.aledante.io/FlowSeer/src/common/yang"

// Identity_Protocol is the fixture-types identity "protocol".
var Identity_Protocol = yang.Identity{
	Module: "fixture-types",
	Name:   "protocol",
}

// Identity_Tcp is the fixture-types identity "tcp".
var Identity_Tcp = yang.Identity{
	Module: "fixture-types",
	Name:   "tcp",
}

// Identity_Udp is the fixture-types identity "udp".
var Identity_Udp = yang.Identity{
	Module: "fixture-types",
	Name:   "udp",
}
