//go:build ignore

// gen_catalog.go is the catalog generator. It is invoked by the
// `go:generate` directive in gen.go:
//
//	go generate ./catalog/...
//
// It reads the registered behaviors and emits zz_generated_catalog.go as
// committed, byte-stable Go source. The generated file carries the "Code
// generated ... DO NOT EDIT" header per Go convention.
//
// Run it from the package directory. The generator imports the catalog
// package, so it lives behind a `//go:build ignore` tag to keep it out of
// the normal build.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"

	"go.aledante.io/FlowSeer/src/edge/netpen/catalog"
)

func main() {
	outPath := flag.String("output", "zz_generated_catalog.go", "generated Go source path")
	flag.Parse()
	entries := catalog.Entries()

	var b bytes.Buffer
	writeHeader(&b)
	writeTable(&b, entries)

	src, err := format.Source(b.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "format failed: %v\n--- source ---\n%s\n", err, b.String())
		os.Exit(1)
	}

	if err := os.WriteFile(*outPath, src, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *outPath, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stdout, "OK: generated %s (%d entries)\n", *outPath, len(entries))
}

func writeHeader(b *bytes.Buffer) {
	b.WriteString("// Code generated by gen_catalog.go; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Run `go generate ./catalog/...` to regenerate. The catalog is\n")
	b.WriteString("// extracted from behavior registrations in registrations.go.\n")
	b.WriteString("\n")
	b.WriteString("package catalog\n\n")
}

func writeTable(b *bytes.Buffer, entries []catalog.Entry) {
	b.WriteString("// GeneratedEntries is the generated attack catalog: one row per\n")
	b.WriteString("// (behavior, mode) pair, sorted by (Name, Mode). It is the data\n")
	b.WriteString("// view of the behavior registrations and the single source for\n")
	b.WriteString("// dispatch, help text, legs, preconditions, and durability classes.\n")
	b.WriteString("// Callers must treat this slice and its nested slices as read-only for\n")
	b.WriteString("// concurrent reads to be safe. Use Entries for an independently owned copy.\n")
	b.WriteString("var GeneratedEntries = []Entry{\n")

	for _, e := range entries {
		fmt.Fprintf(b, "\t{Name: %q, Mode: %q, Protocols: %s, Preconditions: %s, Legs: %s, Class: %s, Teardown: %q, Help: %q},\n",
			e.Name, e.Mode, quoteSlice(e.Protocols), quoteSlice(e.Preconditions),
			legsLiteral(e.Legs), classLiteral(e.Class), e.Teardown, e.Help)
	}

	b.WriteString("}\n")
}

func quoteSlice(s []string) string {
	if len(s) == 0 {
		return "nil"
	}
	out := make([]string, len(s))
	for i, v := range s {
		out[i] = fmt.Sprintf("%q", v)
	}
	return "[]string{" + strings.Join(out, ", ") + "}"
}

func classLiteral(c catalog.Durability) string {
	switch c {
	case catalog.NonDestructive:
		return "NonDestructive"
	case catalog.TransientDecay:
		return "TransientDecay"
	case catalog.TemporaryRestored:
		return "TemporaryRestored"
	case catalog.PermanentDestructive:
		return "PermanentDestructive"
	}
	return fmt.Sprintf("%q", string(c))
}

func legsLiteral(l catalog.Legs) string {
	switch l {
	case catalog.AttackOnly:
		return "AttackOnly"
	case catalog.WatchOptional:
		return "WatchOptional"
	case catalog.WatchRequired:
		return "WatchRequired"
	}
	return fmt.Sprintf("%q", string(l))
}
