// Code generated by gen_catalog.go; DO NOT EDIT.
//
// Run `go generate ./catalog/...` to regenerate. The catalog is
// extracted from behavior registrations in registrations.go.

package catalog

// GeneratedEntries is the generated attack catalog: one row per
// (behavior, mode) pair, sorted by (Name, Mode). It is the data
// view of the behavior registrations and the single source for
// dispatch, help text, legs, preconditions, and durability classes.
var GeneratedEntries = []Entry{
	{Name: "arpspoof", Mode: "", Protocols: []string{"arp"}, Preconditions: nil, Legs: AttackOnly, Class: TemporaryRestored, Teardown: "neighbor unicast repairs + ip_forward restore", Help: "ARP cache poisoning"},
	{Name: "arpsweep", Mode: "", Protocols: []string{"arp"}, Preconditions: nil, Legs: AttackOnly, Class: NonDestructive, Teardown: "", Help: "sweep a subnet for live hosts via ARP"},
	{Name: "camflood", Mode: "", Protocols: []string{"eth"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "CAM table ages out", Help: "flood the CAM table to force fail-open switching"},
	{Name: "daddos", Mode: "", Protocols: []string{"ipv6-nd"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "DAD window passes", Help: "duplicate-address denial via DAD"},
	{Name: "dhcpstarve", Mode: "", Protocols: []string{"dhcp"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "lease pool recovers", Help: "exhaust a DHCP server's lease pool"},
	{Name: "doubletag", Mode: "", Protocols: []string{"vlan"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "one-shot injected frames; nothing persists", Help: "VLAN double-tagging hop to another VLAN"},
	{Name: "dtp", Mode: "", Protocols: []string{"dtp"}, Preconditions: nil, Legs: AttackOnly, Class: TemporaryRestored, Teardown: "access-port restore armed by default", Help: "DTP trunk negotiation"},
	{Name: "dtp", Mode: "keep-trunk", Protocols: []string{"dtp"}, Preconditions: nil, Legs: AttackOnly, Class: PermanentDestructive, Teardown: "opt-in to keep the negotiated trunk", Help: "keep the negotiated trunk (no restore)"},
	{Name: "eigrp", Mode: "", Protocols: []string{"eigrp"}, Preconditions: nil, Legs: AttackOnly, Class: TemporaryRestored, Teardown: "goodbye/flush teardown", Help: "EIGRP route injection"},
	{Name: "etherchannel", Mode: "", Protocols: []string{"lacp", "pagp"}, Preconditions: nil, Legs: AttackOnly, Class: TemporaryRestored, Teardown: "port-channel release", Help: "EtherChannel (LACP/PAgP) attack"},
	{Name: "ghost", Mode: "", Protocols: []string{"arp"}, Preconditions: []string{"watch-leg"}, Legs: WatchRequired, Class: NonDestructive, Teardown: "", Help: "ghost-VLAN traversal evidence via the watch leg"},
	{Name: "glbp", Mode: "", Protocols: []string{"glbp"}, Preconditions: nil, Legs: AttackOnly, Class: TemporaryRestored, Teardown: "resign teardown", Help: "GLBP virtual-router hijack"},
	{Name: "gratarp", Mode: "", Protocols: []string{"arp"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "neighbor cache ages", Help: "gratuitous ARP to announce a MAC"},
	{Name: "hsrp", Mode: "", Protocols: []string{"hsrp"}, Preconditions: nil, Legs: AttackOnly, Class: TemporaryRestored, Teardown: "resign teardown", Help: "HSRP active-router hijack"},
	{Name: "icmpredirect", Mode: "", Protocols: []string{"icmp"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "victim route cache decays", Help: "ICMP redirect to poison routes"},
	{Name: "lldpspoof", Mode: "", Protocols: []string{"lldp"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "bounded bursts / holdtimes", Help: "generic LLDP spoofing"},
	{Name: "llmnr", Mode: "", Protocols: []string{"llmnr"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "spoofed answers expire", Help: "spoof LLMNR name resolution"},
	{Name: "mld", Mode: "", Protocols: []string{"mld"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "bounded bursts / holdtimes", Help: "MLD abuse flood"},
	{Name: "mvrp", Mode: "", Protocols: []string{"mvrp"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "MRP timers, minutes", Help: "MVRP VLAN registration flood"},
	{Name: "ndpspoof", Mode: "", Protocols: []string{"ipv6-nd"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "NUD / real master resumes", Help: "spoof IPv6 neighbor discovery"},
	{Name: "ospf", Mode: "", Protocols: []string{"ospf"}, Preconditions: nil, Legs: AttackOnly, Class: TemporaryRestored, Teardown: "goodbye/flush teardown", Help: "OSPF LSA injection"},
	{Name: "portsteal", Mode: "", Protocols: []string{"arp"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "CAM aging", Help: "port-steal ARP spoofing"},
	{Name: "portsteal", Mode: "relay", Protocols: []string{"arp"}, Preconditions: nil, Legs: AttackOnly, Class: TemporaryRestored, Teardown: "ip_forward restore armed", Help: "port-steal with relay enabled"},
	{Name: "raflood", Mode: "", Protocols: []string{"ipv6-nd", "ra"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "bounded bursts / holdtimes", Help: "RA-flood variant"},
	{Name: "raguard", Mode: "", Protocols: []string{"ipv6-nd", "ra"}, Preconditions: nil, Legs: WatchOptional, Class: NonDestructive, Teardown: "", Help: "observe forged RA handling under RA-Guard"},
	{Name: "roguedhcp", Mode: "", Protocols: []string{"dhcp"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "client leases ~1800s", Help: "rogue DHCPv4 server"},
	{Name: "roguedhcp6", Mode: "", Protocols: []string{"dhcpv6"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "~300s lifetime announced", Help: "rogue DHCPv6 server"},
	{Name: "roguera", Mode: "", Protocols: []string{"ipv6-nd", "ra"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "~1800s lifetime announced", Help: "rogue router advertisement"},
	{Name: "scan", Mode: "", Protocols: []string{"arp", "ipv6-nd"}, Preconditions: nil, Legs: WatchOptional, Class: NonDestructive, Teardown: "", Help: "passive/active segment discovery"},
	{Name: "stproot", Mode: "", Protocols: []string{"stp"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "engineered max_age~6s", Help: "claim STP root with superior BPDUs"},
	{Name: "vlanenum", Mode: "", Protocols: []string{"vlan", "stp"}, Preconditions: nil, Legs: AttackOnly, Class: NonDestructive, Teardown: "", Help: "enumerate VLANs from a trunk port"},
	{Name: "vlanhop", Mode: "", Protocols: []string{"vlan"}, Preconditions: nil, Legs: AttackOnly, Class: TemporaryRestored, Teardown: "active restore armed", Help: "VLAN hopping attack"},
	{Name: "vlanhop", Mode: "persist", Protocols: []string{"vlan"}, Preconditions: nil, Legs: AttackOnly, Class: PermanentDestructive, Teardown: "host-side persistence, flag is the opt-in", Help: "persistent VLAN hop"},
	{Name: "voicevlan", Mode: "", Protocols: []string{"vlan", "lldp"}, Preconditions: nil, Legs: AttackOnly, Class: TemporaryRestored, Teardown: "active restore armed", Help: "voice-VLAN hijack"},
	{Name: "voicevlan", Mode: "persist", Protocols: []string{"vlan", "lldp"}, Preconditions: nil, Legs: AttackOnly, Class: PermanentDestructive, Teardown: "host-side persistence, flag is the opt-in", Help: "persistent voice-VLAN hijack"},
	{Name: "vrrp", Mode: "", Protocols: []string{"vrrp"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "NUD / real master resumes", Help: "spoof VRRP to claim the virtual router"},
	{Name: "vtp", Mode: "", Protocols: []string{"vtp"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "revision-bump side effect recorded", Help: "VTP domain manipulation (SAFE mode default)"},
	{Name: "vtp", Mode: "set", Protocols: []string{"vtp"}, Preconditions: nil, Legs: AttackOnly, Class: PermanentDestructive, Teardown: "requires per-run opt-in", Help: "VTP VLAN-database overwrite"},
	{Name: "vtp", Mode: "wipe", Protocols: []string{"vtp"}, Preconditions: nil, Legs: AttackOnly, Class: PermanentDestructive, Teardown: "requires per-run opt-in", Help: "VTP VLAN-database wipe"},
	{Name: "wpad", Mode: "", Protocols: []string{"wpad", "llmnr"}, Preconditions: nil, Legs: AttackOnly, Class: TransientDecay, Teardown: "client proxy config residue, bound = TTL", Help: "rogue WPAD proxy"},
}
