// Code generated by yanggen. DO NOT EDIT.
// generator: yanggen-4
// module: fixture-grp revision: 2026-01-02
// source sha256: 8ff2534ef77448379309d602d3f51dcfb619c4a86b518aa085e94cdc746236b5

// Package fixturegrp binds the YANG module fixture-grp.
package fixturegrp
