// Code generated by yanggen. DO NOT EDIT.
// generator: yanggen-5
// module: fixture-grp revision: 2026-01-02
// source sha256: de340f185001daaec150dd3bf741bfce01b0266e78158593fc0d7cf047a87a42

// Package fixturegrp binds the YANG module fixture-grp.
package fixturegrp

import yang "go.aledante.io/FlowSeer/src/protocol/yang"

// moduleFixtureGrp identifies the fixture-grp YANG module.
var moduleFixtureGrp = &yang.Module{
	Name:      "fixture-grp",
	Namespace: "urn:flowseer:fixture-grp",
}
