package host_test

import (
	"bytes"
	"encoding/hex"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"go.aledante.io/FlowSeer/src/common/errs"
	"go.aledante.io/FlowSeer/src/modules/edgebus"
	"go.aledante.io/FlowSeer/src/services/device/internal/host"
)

// configIn is validConfig with its state directory pointed at a temporary one,
// which is where the generated pair lands.
func configIn(t *testing.T, stateDir string) *host.Config {
	t.Helper()
	body := strings.Replace(validConfig, `state_dir: "/var/lib/flowseer/device"`, `state_dir: "`+stateDir+`"`, 1)
	cfg, err := host.LoadConfig(writeConfig(t, body))
	if err != nil {
		t.Fatalf("LoadConfig: %v", err)
	}
	return cfg
}

func logTo(buf *bytes.Buffer) *slog.Logger {
	return slog.New(slog.NewJSONHandler(buf, nil))
}

// An edge accepts a chain only when its leaf's SPKI digest is one it was
// provisioned with. A service that generated a fresh key on every start would
// refuse every edge already in the field, with no way back but re-provisioning
// each one by hand — so the pair is written down and read back.
func TestARestartServesTheSameKeyTheEdgesWereProvisionedWith(t *testing.T) {
	stateDir := t.TempDir()
	cfg := configIn(t, stateDir)

	first, err := host.ObtainCertificate(cfg, logTo(&bytes.Buffer{}))
	if err != nil {
		t.Fatalf("first start: %v", err)
	}
	second, err := host.ObtainCertificate(configIn(t, stateDir), logTo(&bytes.Buffer{}))
	if err != nil {
		t.Fatalf("restart: %v", err)
	}

	if !bytes.Equal(first.SPKI, second.SPKI) {
		t.Fatalf("the restart served a different key: %x then %x", first.SPKI, second.SPKI)
	}
	if !bytes.Equal(first.TLS.Leaf.Raw, second.TLS.Leaf.Raw) {
		t.Fatal("the restart served a different certificate")
	}
}

// The digest is what an operator writes into every edge's provisioning, so it
// reaches the log at generation and the value logged is the one a peer would
// pin.
func TestGenerationLogsThePinAndOnlyAtGeneration(t *testing.T) {
	stateDir := t.TempDir()
	var generated bytes.Buffer
	certificate, err := host.ObtainCertificate(configIn(t, stateDir), logTo(&generated))
	if err != nil {
		t.Fatalf("first start: %v", err)
	}

	if !strings.Contains(generated.String(), hex.EncodeToString(certificate.SPKI)) {
		t.Fatalf("the generation log does not carry the pin: %s", generated.String())
	}
	if got := edgebus.SPKIDigest(certificate.TLS.Leaf); !bytes.Equal(got, certificate.SPKI) {
		t.Fatalf("reported pin %x, want the leaf's %x", certificate.SPKI, got)
	}

	var restarted bytes.Buffer
	if _, err := host.ObtainCertificate(configIn(t, stateDir), logTo(&restarted)); err != nil {
		t.Fatalf("restart: %v", err)
	}
	if strings.Contains(restarted.String(), hex.EncodeToString(certificate.SPKI)) {
		t.Fatalf("a restart logged the pin again: %s", restarted.String())
	}
}

// The private key is the service's identity to every edge in the field. It is
// written before the certificate and readable by nobody else: a crash between
// the two leaves a key with no certificate, which the next start replaces
// because no edge was ever told about it.
func TestTheGeneratedKeyIsWrittenPrivately(t *testing.T) {
	stateDir := t.TempDir()
	if _, err := host.ObtainCertificate(configIn(t, stateDir), logTo(&bytes.Buffer{})); err != nil {
		t.Fatalf("first start: %v", err)
	}

	info, err := os.Stat(filepath.Join(stateDir, "tls.key"))
	if err != nil {
		t.Fatalf("stat key: %v", err)
	}
	if perm := info.Mode().Perm(); perm != 0o600 {
		t.Fatalf("key mode = %#o, want 0600", perm)
	}
}

// The listeners' own addresses reach the certificate, so everything that does
// check names — an operator's browser, a probe, a proxy — reaches the service
// without an exception of its own. An edge checks none of this; it pins the
// key.
func TestTheGeneratedCertificateNamesWhatTheDeploymentBinds(t *testing.T) {
	body := strings.NewReplacer(
		`state_dir: "/var/lib/flowseer/device"`, `state_dir: "`+t.TempDir()+`"`,
		`api: "0.0.0.0:8443"`, `api: "central.example.test:8443"`,
		`bus: "0.0.0.0:8444"`, `bus: "10.0.0.7:8444"`,
	).Replace(validConfig)
	cfg, err := host.LoadConfig(writeConfig(t, body))
	if err != nil {
		t.Fatalf("LoadConfig: %v", err)
	}

	certificate, err := host.ObtainCertificate(cfg, logTo(&bytes.Buffer{}))
	if err != nil {
		t.Fatalf("ObtainCertificate: %v", err)
	}
	leaf := certificate.TLS.Leaf
	if err := leaf.VerifyHostname("central.example.test"); err != nil {
		t.Errorf("the api host is not named: %v", err)
	}
	if err := leaf.VerifyHostname("10.0.0.7"); err != nil {
		t.Errorf("the bus address is not named: %v", err)
	}
	if err := leaf.VerifyHostname("localhost"); err != nil {
		t.Errorf("loopback is not named: %v", err)
	}
}

// A deployment that brings its own chain gets it served rather than a
// generated one, and nothing is written into the state directory.
func TestASuppliedCertificateIsServedAsGiven(t *testing.T) {
	stateDir := t.TempDir()
	supplied := t.TempDir()
	generated, err := host.ObtainCertificate(configIn(t, supplied), logTo(&bytes.Buffer{}))
	if err != nil {
		t.Fatalf("generate a pair to supply: %v", err)
	}

	body := strings.NewReplacer(
		`state_dir: "/var/lib/flowseer/device"`, `state_dir: "`+stateDir+`"`,
		`bus: "0.0.0.0:8444"`, `bus: "0.0.0.0:8444"`+
			"\n  certificate_file: \""+filepath.Join(supplied, "tls.crt")+"\""+
			"\n  private_key_file: \""+filepath.Join(supplied, "tls.key")+"\"",
	).Replace(validConfig)
	cfg, err := host.LoadConfig(writeConfig(t, body))
	if err != nil {
		t.Fatalf("LoadConfig: %v", err)
	}

	served, err := host.ObtainCertificate(cfg, logTo(&bytes.Buffer{}))
	if err != nil {
		t.Fatalf("ObtainCertificate: %v", err)
	}
	if !bytes.Equal(served.SPKI, generated.SPKI) {
		t.Fatalf("served %x, want the supplied %x", served.SPKI, generated.SPKI)
	}
	if _, err := os.Stat(filepath.Join(stateDir, "tls.crt")); !os.IsNotExist(err) {
		t.Fatalf("a supplied certificate still wrote one into the state directory: %v", err)
	}
}

func TestASuppliedCertificateThatCannotBeReadIsRefused(t *testing.T) {
	stateDir := t.TempDir()
	body := strings.NewReplacer(
		`state_dir: "/var/lib/flowseer/device"`, `state_dir: "`+stateDir+`"`,
		`bus: "0.0.0.0:8444"`, `bus: "0.0.0.0:8444"`+
			"\n  certificate_file: \"/nowhere/tls.crt\"\n  private_key_file: \"/nowhere/tls.key\"",
	).Replace(validConfig)
	cfg, err := host.LoadConfig(writeConfig(t, body))
	if err != nil {
		t.Fatalf("LoadConfig: %v", err)
	}

	_, err = host.ObtainCertificate(cfg, logTo(&bytes.Buffer{}))
	if code, _ := errs.CodeOf(err); code != host.ErrCodeCertificate {
		t.Fatalf("error = %v, want code %v", err, host.ErrCodeCertificate)
	}
}
